### ISSUE TITLE
It would be more helpful if the values were presented as hex values

### ISSUE THREAD

**Issue by dunhor** [MicrosoftDocs/winrt-api#1009]
Since these values are masks and values are typically encountered as combinations of these masks, it would be helpful if their values were presented in hexadecimal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f5921-5d92-25d7-7d77-8a3dba8e5ecc
* Version Independent ID: 93feb2b9-d25f-2e57-a2ad-a39278b2f8fb
* Content: [AttributeTargets Enum (Windows.Foundation.Metadata) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.attributetargets#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.attributetargets.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.attributetargets.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by MikeHillberg** [comment]
Any enum with the [flags] attribute (System.Flags) should be displayed in hex.

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. The table of fields on this page is generated by our systems and isn't part of the content that we can control in markdown. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
