### ISSUE TITLE
Worthless boilerplate

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/winrt-api#1012]
This page:
https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.imediaplaybacksource
is indeed worthless.  We come here to find information, not anything as meaningless and opaque as "a marker interface".  Doesn't  belong within 5 miles of a Microsoft API reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8cb423-2ec0-a8b9-4a5e-0c7dc5ee9090
* Version Independent ID: 62f3ba37-51f7-004a-2da1-3b80e2d0508e
* Content: [IMediaPlaybackSource Interface (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.imediaplaybacksource#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.imediaplaybacksource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.imediaplaybacksource.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback. This is an unusual API. It's an interface with no members. It's purpose is to identify interfaces that inherit from it to the media framework so that the system knows that can perform private media playback operations on it. I've added a remark to the page to try to make this a little clearer and to let devs know that they aren't expected to use this interface directly.

**Comment by mrmsbarnes** [comment]
To Drew Batchelor

Thank you.  Remark helps a lot.  I’m getting to know video playback better.
