### ISSUE TITLE
Remark is missing important info

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/winrt-api#1017]
The first sentence is scary: "does not always guarantee durable and coherent storage of data". I even wonder why such method exist.

Also, the remark should propose what we should use instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e843a5e-8a83-0427-10e1-52366c4e09ea
* Version Independent ID: ec080505-b423-ad6e-d3ac-d47ac10e2fd2
* Content: [InMemoryRandomAccessStream.FlushAsync Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.inmemoryrandomaccessstream.flushasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.Streams.InMemoryRandomAccessStream.FlushAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.inmemoryrandomaccessstream.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.inmemoryrandomaccessstream.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for leaving feedback. I'll see if I can get that wording in the remarks section updated.

**Comment by knicholasa** [comment]
Alright, I checked in with the team that owns the API. The thing to be cautious about with this API is any race condition that might occur, since it is asynchronous. However, I'm going to remove that sentence from the remarks section, since it makes it sound like this specific API is uniquely problematic. 

If you'd like help finding an alternative API, please use our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). There you can ask for guidance with your specific development scenario.

**Comment by ArchieCoder** [comment]
Ok, it makes more sense now. There are a lot of methods that are asynchronous in UWP.

I would also recommend that the sentence: "It's generally recommended to avoid this method if possible." is also confusing. Thanks
