### ISSUE TITLE
Explain difference between MoveAsync(..., NameCollisionOption.ReplaceExisting) and StorageFile.MoveAndReplace

### ISSUE THREAD

**Issue by manuelroemer** [MicrosoftDocs/winrt-api#1027]
There is no indication what the difference between `StorageFile.MoveAsync(..., NameCollisionOption.ReplaceExisting)` and `StorageFile.MoveAndReplaceAsync` is.
Is the former atomic, i.e. less error prone? Does the latter not behave in the same way? Are they doing exactly the same? (And if so, why do we have two options here?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5f9867-2800-7596-24d1-3e46069c352f
* Version Independent ID: af51891d-f411-fea2-6b73-8d40e72abbf5
* Content: [StorageFile.MoveAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.moveasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, thanks for the feedback. I'll look into updating the doc so that this isn't ambiguous. However, feedback here is meant for documentation related issues and I suggest you reach out to our other developer support resources for a faster answer to your questions. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

**Comment by manuelroemer** [comment]
Hey, thanks for the heads up. I'll be sure to post in other places in the future in such cases.

A quick follow up question though: This case here really is something that I would like to see in the MSDN docs, so I thought that this was the right place to ask - would a post in the forum also lead to a doc update?
I'm asking because there are quite a few other undocumented points (regarding the UWP file API) that, in my opinion, really should be documented, because not knowing about them lead to quite a few hours of trial and error that I had to do, just to test what the API is doing in certain cases. I may get around to writing them up at some point - the question is, where I should post it then.

Nonetheless, thank you for your reply and thanks for looking into it!

**Comment by knicholasa** [comment]
Yeah, no problem! A forum post will not necessarily lead to a doc update. If you are confused by a doc, I'd love it if you'd post both on the forums and here. The forums will get you help, and your feedback here will be used to improve the docs. We definitely appreciate all the feedback we get here and we do use it, but currently we're not a support channel the same way those other resources are. 

If you can write up your feedback, I'd love to hear it. Since it's doc feedback, the best place to leave it would be as a GitHub issue on the most relevant page you can find, but feel free to tag me when you do.

**Comment by knicholasa** [comment]
Hi again, I investigated the docs a bit. The reason you have two options here is that those APIs are for different but overlapping use cases. From the docs: 

**MoveAsync(IStorageFolder, String, NameCollisionOption)**:

> Moves the current file to the specified folder and renames the file according to the desired name. This method also specifies what to do if a file with the same name already exists in the specified folder.

**StorageFile.MoveAndReplaceAsync(IStorageFile)**:

> Moves the current file to the location of the specified file and replaces the specified file in that location.

So **MoveAndReplaceAsync** _does not_ rename the file, and replaces the given file regardless of if they share the same name. **MoveAsync** renames the file, and only replaces a file in the new location if there is one that has the new name. 

Does that make sense?

**Comment by manuelroemer** [comment]
Hey, thanks for investigating! That does make a lot of sense. I think the confusion came mostly from me using **MoveAsync** like this: `file.MoveAsync(dest, file.Name, NameCollisionOption.Replace)`. This is just an alias for `MoveAndReplaceAsync`. That's why I was confused - why were there two ways for doing this? And I didn't really find anything in the docs for that, which is why I asked.

Again, thank you so much for your time and elaborate answers. I appreciate that very much. Have a nice weekend!
