### ISSUE TITLE
How can I use the 3D Printing API in a back end application?

### ISSUE THREAD

**Issue by artemzakharov** [MicrosoftDocs/winrt-api#1029]
I found out about the 3D printing API after coming across this web service:

https://tools3d.azurewebsites.net/

I would like to create my own back end service that can repair 3D files using this API, but I'm at a loss for how to do that - Universal Windows Apps seem to offer no support for being run as a back end application, being available only for desktops and devices. What I want has to be possible _somehow_ - the website above seems to send the file to a back end version of this api - but I can't figure it out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc84aee-0b27-e776-d54e-7693cbf06e6b
* Version Independent ID: 85887857-d411-9e16-5022-c3897c877030
* Content: [Windows.Graphics.Printing3D Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Printing3D#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing3d.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing3d.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see the [developer support page](https://developer.microsoft.com/windows/support) for your support options.
