### ISSUE TITLE
No Exception Information

### ISSUE THREAD

**Issue by Yortw** [MicrosoftDocs/winrt-api#1033]
I had some code working using this API but now when I call EnableTransferOwnership(Guid, SocketActivityConnectedStandByAction) I'm getting a System.Exception thrown with result code 0x80070490 and a message of "Element not found". I came to the API documentation to find out what exceptions are thown under what conditions... and there is no exception information here at all? I appreciate all the hard work on these docs, but missing exception information seems to be a common theme and is something I often refer to documentation specifically to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a549ff11-db0b-550c-4b97-0523cad413f3
* Version Independent ID: 5db057f6-c634-077d-4dba-16178641ada2
* Content: [StreamSocket.EnableTransferOwnership Method (Windows.Networking.Sockets) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocket.enabletransferownership#Windows_Networking_Sockets_StreamSocket_EnableTransferOwnership_System_Guid_Windows_Networking_Sockets_SocketActivityConnectedStandbyAction_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.sockets.streamsocket.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.sockets.streamsocket.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Yortw, thanks for filing this issue. I'll check with the devs about this particular exception that you're seeing; I suspect the Guid isn't found, but I'll go and confirm whether it's intentional. Generally speaking, the omission of exception info in the docs is by design. The reasoning is that Windows Runtime APIs return error HRESULTS (which are turned into an exception by your particular language project) only for errors in programming against the APIs (errors that can, and should, be found and fixed at development/debug time). For well-designed APIs, exceptions don't occur for general error conditions that the app needs to protect against in production. In other words, once your app is debugged and ready for prime-time, there's no need for exception handling in the code, and hence no need for info about exceptions (in fact, having it there would be misleading). However, on rare occasions an API does mistakenly throw an exception for things like "Id not found", rather than returning not-found info (perhaps just a bool) or an empty collection. If that's the case here, then it's good for the devs to be aware of it.

Thanks!
~Steve

**Comment by Yortw** [comment]
Thanks Steve, that's great, I appreciate the feedback and the efforts to improve things here. I had forgotten but understand the issues caused by the API's being available to multiple languages. However if exception information isn't appropriate, maybe a list of HRESULT codes and their meanings would be? That might be more cross language/platform friendly?

In this case I am seeing the error at debug time and trying to fix it, but I do not know how because the exception detail and docs aren't telling me what the problem is in detail.  I suspect like you say it's the GUID that is the problem (though I believe that came from another API for registering a background task, that succeeded, so no idea why it wouldn't be found). However it could be that the argument I'm passing for the 'wake' behaviour is an unknown enum value (changed API levels or something?) so I'm not certain. 

The larger issue is the API's can and do fail, and often for reasons that are hard to determine. Better documentation around likely faults would help, even if not in the form I initially asked for.

Thanks again, to you and the docs team. I don't always come across well in written communications, I am trying to provide helpful feedback and not just 'have a whinge' :)

**Comment by stevewhims** [comment]
I do appreciate the feedback, @Yortw, and this is helpful feedback. I'm not entirely sure how much we'll be able to meet your expectations, though. I'll keep following up with my contacts about this exception, and if the behavior is by design then I'll make a case for documenting it. If I can, then that'll satisfy this particular case. However, documenting all HRESULTS is unlikely to be something we'd be able to do across the entire docset. ~Steve

**Comment by stevewhims** [comment]
**UPDATE**: I'm still following up; no news yet.

**Comment by stevewhims** [comment]
Still following up; no news yet.

**Comment by stevewhims** [comment]
I just sent another reminder internally, asking for that info; no news yet.

**Comment by stevewhims** [comment]
UPDATE: I sent another reminder, asking for input on this.

**Comment by stevewhims** [comment]
Hi, @Yortw, so in this case we were able to gather info about the exception you're seeing. I've added more documentation and guidance around that, and the calling pattern that we recommend. You can see that in the "Remarks" section of this topic. I'll leave the issue open for a while to give you the chance to comment. Sorry for the delay in getting this updated!

~Steve

**Comment by Yortw** [comment]
Thank you, that makes a real difference to the usability of the documentation and I'm sure it will help others in future.
I am not sure that is my problem as I think my issue was intermittent on the same hardware, but I will need to recheck. I suspect, regardless though, you can close this ticket unless there are other causes of that exception that could be documented.

Thanks for your hard work on this.

**Comment by stevewhims** [comment]
Thanks, @Yortw! I'll go ahead and close, then. ~Steve
