### ISSUE TITLE
Incorrect return value in comments

### ISSUE THREAD

**Issue by dunhor** [MicrosoftDocs/winrt-api#1035]
The "Returns" portion says that the function returns "IReadOnlyList&lt;T&gt;", but that is only true for .NET and I have it set to show documentation for C++/WinRT. I'd expect it to say "IVectorView&lt;T&gt;" with a link to the documentation for IVectorView

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd8b7650-a2ee-b9b8-1a96-211049ddebd0
* Version Independent ID: a7c365fc-063b-90a2-8eb2-19f95d9e0f59
* Content: [IVector&lt;T&gt;.GetView Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivector-1.getview#Windows_Foundation_Collections_IVector_1_GetView)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivector_t_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivector_t_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello, sorry for the delayed response to your issue. The syntax blocks in our API reference pages are dynamically generated. It appears that since you opened this issue, the code generation has been fixed and so the C++/WinRT signature is now correct:

`IVectorView<T> GetView();`

Thank you for contributing to the quality and accuracy of our documentation!
