### ISSUE TITLE
Please provide full examples of compilable code (maybe after click)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [MicrosoftDocs/winrt-api#1047]
For example I have a few years of experience with Python, JS, some Go, but on this page looks like is not enough of code to compile and run it, and I do not know what wrapper code (maybe some imports) do I need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c481f71-1ea6-9ba9-e9ab-4849355b91b4
* Version Independent ID: acae4227-6c8c-2c13-7b9e-3d080153504d
* Content: [SpeechSynthesisStream Class (Windows.Media.SpeechSynthesis) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesisstream)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechsynthesis.speechsynthesisstream.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechsynthesis.speechsynthesisstream.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback on the documentation. Often common, non-feature-specific code is omitted from snippets in order to make them smaller and more readable. If you are looking for a complete sample, including UI and app template code, that can be compiled without changes, I recommend downloading the speech synthesis SDK sample: 

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SpeechRecognitionAndSynthesis

As a general tip, you can quickly discover the namespace and automatically add the required using statement for a particular API by using Visual Studio's *Show Potential Fixes* feature:

https://docs.microsoft.com/en-us/visualstudio/ide/quick-actions?view=vs-2019

Or the *Generate Usings* feature:

https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-usings?view=vs-2019
