### ISSUE TITLE
winjs support?

### ISSUE THREAD

**Issue by Linrstudio** [MicrosoftDocs/winrt-api#1058]
winjs support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b4a17c8-e018-560f-59a8-b0e097939f20
* Version Independent ID: 4f2ac5e2-6fc6-003d-26d4-fee0a50521d3
* Content: [HtmlUtilities(String) Class (Windows.Data.Html) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.html.htmlutilities#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.html.htmlutilities.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.html.htmlutilities.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay. Unfortunately, it isn't clear from the context what exactly your question is. If you're asking about JavaScript syntax and code examples for this API, it is by design that we no longer provide these items in JavaScript in our docs. Visual Studio 2019 has removed JavaScript support for UWP projects, and we have accordingly phased it out of our API docs. If you have other feedback, please feel free to reopen this issue with more details.
