### ISSUE TITLE
When using PDF format error is thrown

### ISSUE THREAD

**Issue by justindbaur** [MicrosoftDocs/winrt-api#1065]
An exception is being thrown when trying to set my scanners scan format to a PDF.  I am looking for more information about this error but I can't find any.  How can I scan directly to a PDF, I have drivers installed for my scanner that should allow this.  The exception that is being throws is not very descriptive.

Exception Message: The parameter is incorrect
Exception Stack Trace: at Windows.Devices.Scanners.ImageScannerFeederConfiguration.put_Format(ImageScannerFormat value)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3f52fa-23ae-7aff-9537-a74a796e0d3d
* Version Independent ID: de998431-0cb0-dfca-cfe8-ec8740841de6
* Content: [ImageScannerFormat Enum (Windows.Devices.Scanners) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners.imagescannerformat#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.scanners.imagescannerformat.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.scanners.imagescannerformat.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by justindbaur** [comment]
I would love more documentation on how or why the PDF format would throw an error and how it can be resolved.

**Comment by stevewhims** [comment]
Hi, @justindbaur. Thanks for filing this issue, and my apologies for the long delay in responding.

Except in rare cases, we don't document exceptions (I'll explain the reasons below). So, it might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

One reason we don't document exceptions is that a well-designed API throws only under conditions where the API isn't being used correctly. So, those conditions can (and should) be found and fixed at development/debug time. So, for a well-designed API, it'd be unnecessary to write production code that catches exceptions. The idea of this design is that for a condition such as an unplugged ethernet cable, where that's not a programming error, the API should not be throwing exceptions; but rather APIs should be able to communicate that condition in parameters or return values (if possible).

The other reason is that a Windows Runtime API itself indicates success/failure by returning an HRESULT value, and certain values result in programming-language-specific exceptions. So while we can document HRESULTs (and we do so for COM APIs), it's not that straightforward for Windows Runtime APIs.

If an API is not following these rules, then hopefully that'll be discovered as part of a support case. If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Sorry that I couldn't be of more immediate help here.
-Steve
