### ISSUE TITLE
Why no media stream source support?

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/winrt-api#1067]
Why randomly skip the "SetMediaStreamSource" method? this would be nice to use in combination with media binder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600e30fd-3d95-8c8e-aa01-b3ca1820c05f
* Version Independent ID: 72d568e6-e65f-ac15-b2ef-8cd11781b4d5
* Content: [MediaBindingEventArgs Class (Windows.Media.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediabindingeventargs#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediabindingeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediabindingeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
