### ISSUE TITLE
What is the behavior in non UWP apps?

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1085]
This says that Package.Current isn't supported in UWP apps. Does that mean that it throws an exception for a desktop app, or that it returns null?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3099bc3-1eb7-77f0-29ea-d1ce01f4dfa7
* Version Independent ID: f25364e8-33ca-d30a-f718-f14636d615f4
* Content: [Package.Current Property (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Package.Current)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. You'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.

**Comment by perennialmind** [comment]
This strikes me as a reasonable enhancement request. "Unsupported" implies undefined behavior: it's free eat your face or set your desktop on fire. Committing to a `InvalidOperationException` or `NotImplementedException` or whatever the matches the current observable behavior would be a real improvement for us API consumers.
