### ISSUE TITLE
what does these different values actually mean?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/winrt-api#1091]
What system policy?  Where do I set it?
How can the Revoked event have an argument with a value of Resumed? Can the application be stopped without receiving the Revoked event, and then first when it is restarted it is told about it??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57334b4-96d1-4285-bb3a-d0197cb3a0b6
* Version Independent ID: c3e46f1d-ff41-f213-10d8-b5ca414413dc
* Content: [ExtendedExecutionForegroundRevokedReason Enum (Windows.ApplicationModel.ExtendedExecution.Foreground) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundrevokedreason)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundrevokedreason.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundrevokedreason.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out. Those are good questions. To get the fastest answer, I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

**Comment by Bartolomeus-649** [comment]
Ok,could you please provide the location/source/site/documentation where users in the forums and on StackOverflow get their information from?

**Comment by knicholasa** [comment]
https://docs.microsoft.com/ is the primary place to go for documentation. The people on the forums will search the docs, but if they can’t find a solution and are Microsoft staff, they may reach out to the feature teams responsible and ask them directly. If you need a different level of support, you can check out the options on the [support page](https://support.microsoft.com/hub/4343728/support-for-business). 

I should also say that we do use the feedback here to update our docs - I'm providing these other links because we aren't a direct support channel.
