### ISSUE TITLE
Id can also be "computer"

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#1092]
I just received the other value "computer" for the Id, not only Local, Network or OneDrive.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b9c825f6-87e4-caf4-2876-b0838b511e44
* Version Independent ID: 41fb3f15-cd3a-611b-1af2-f2e2e6e97419
* Content: [StorageProvider.Id Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/fr-fr/uwp/api/windows.storage.storageprovider.id#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storageprovider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storageprovider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for bringing this to my attention, I will reach out to the team that owns this area and update the docs.

**Comment by knicholasa** [comment]
Turns out there are some bit fields that are not part of this API's set but which might show up since they represent [Win32 file type attributes](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=netframework-4.8) and are not filtered out. The team is aware of this issue and is tracking it internally. Thanks for raising awareness. Closing the issue now.
