### ISSUE TITLE
Is this curve25519 algorithm officially supported? 

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1097]
I get exception for following code as "The request is not supported. (Exception from HRESULT: 0x80070032)". Anything wrong I am doing OR curve25519 is yet to be supported by Windows UWP? Kindly clarify. 

            // Open the algorithm provider for the specified asymmetric algorithm.
            AsymmetricKeyAlgorithmProvider objAlgProv = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithmNames.EcdsaSha256);

            // Create an asymmetric key pair.
            CryptographicKey keyPair;
            try
            {
                //keyPair = objAlgProv.CreateKeyPair(512);
                keyPair = objAlgProv.CreateKeyPairWithCurveName(EccCurveNames.Curve25519);
            }
            catch(Exception ex)
            {
                keyPair = null;
            }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca863cb-9069-f28a-2245-11ac7edeb5a4
* Version Independent ID: a43b508e-197a-dce9-97ae-620c08fde1e8
* Content: [EccCurveNames.Curve25519 Property (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.ecccurvenames.curve25519#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.ecccurvenames.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.ecccurvenames.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **misatran**

**Comment by hkhmsft** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
