### ISSUE TITLE
File.Attributes can be 1056 !

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#1102]
I have the File.Attributes equal to 1056 with files locally stored on PC mirrored from OneDrive. Decomposition is 32 (archive) and 1024 which is none of the attributes listed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6496c5da-0a8e-a982-57e3-a45ea0f33fa9
* Version Independent ID: fc24102a-70c7-e97c-5186-51ca5f11501b
* Content: [FileAttributes Enum (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.FileAttributes)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileattributes.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileattributes.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, thanks for reaching out with your feedback. I've contacted the team that owns this area and they're now tracking this issue internally. It sounds like you may be able to see bit fields that do not correspond to values in this enum because the bit fields match the [Win32 file type attributes](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=netframework-4.8), but this enum only includes values for fields that are relevant for this set of UWP APIs.

**Comment by knicholasa** [comment]
Closing the issue. If you need further technical support, please checkout our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Or check out [the developer support page](https://developer.microsoft.com/windows/support) for other support options.
