### ISSUE TITLE
Does the API contract need to be updated here.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#1135]
Hi,

Just to explain the angle I'm coming from ..  I use both CoreApp and XamlApp templates in my C# game and related work (with SharpDX interop for DX). I have to manually write the CoreApp template because VS doesn't provide a C# version. I'm looking to move my UWP game engine/framework from being a UWP library to a .Net Standard library. I'm investigating if that's the right course of action and if it's possible in terms of compatible API's / app models etc.

As I understand this IFrameworkView API, it's a projection from WinRT. I notice in the docs here the device family and API contracts are as follows ..

Device family = Windows 10 (introduced v10.0.10240.0) 
API contract = Windows.Foundation.UniversalApiContract (introduced v1)

Is this still correct or is there some information missing here or elsewhere on this page when considering  Microsoft.Windows.SDK.Contracts for consuming WinRT from .Net Core.

And to raise some specific queries I have regarding this API ..

1. Is the IFrameworkView app template, or at least the API and app model as used in UWP now available in .Net Core?
2. Likewise can I use the Xaml app model from UWP (not Xaml Islands) in .Net Core? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a05178-aff3-7f67-305e-2eba49cb17da
* Version Independent ID: 72c12587-21c1-5a98-5538-b0b1d5f23dbc
* Content: [IFrameworkView Interface (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Core.IFrameworkView)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.iframeworkview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.iframeworkview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by aeloros** [comment]
inline below...

> Hi,
> 
> Just to explain the angle I'm coming from .. I use both CoreApp and XamlApp templates in my C# game and related work (with SharpDX interop for DX). I have to manually write the CoreApp template because VS doesn't provide a C# version. I'm looking to move my UWP game engine/framework from being a UWP library to a .Net Standard library. I'm investigating if that's the right course of action and if it's possible in terms of compatible API's / app models etc.
> 
> As I understand this IFrameworkView API, it's a projection from WinRT. I notice in the docs here the device family and API contracts are as follows ..
> 
> Device family = Windows 10 (introduced v10.0.10240.0)
> API contract = Windows.Foundation.UniversalApiContract (introduced v1)
> 
> Is this still correct or is there some information missing here or elsewhere on this page when considering Microsoft.Windows.SDK.Contracts for consuming WinRT from .Net Core.

This is the correct information.  CoreApplication, IFrameworkView, IFrameworkViewSource are all UWP APIs.  The two interfaces in the list above are the extension points you need to implement in order to use CoreApplication to show UI when you don't have a framework that already implements them for you.  For instance XAML implements these interfaces in order to provide you the more curated XAML Application object.

> And to raise some specific queries I have regarding this API ..
> 
> 1. Is the IFrameworkView app template, or at least the API and app model as used in UWP now available in .Net Core?

As long as you're building a UWP app, these interfaces are available.  I'm not sure if we have a VS template for using them from .NET Core, but it shouldn't be too hard to write from scratch (by following what the other templates look like).  I feel like the DirectX 11 template in VS is a decent one to copy if you follow how the App class is constructed.

> 2. Likewise can I use the Xaml app model from UWP (not Xaml Islands) in .Net Core?

I'm unaware of any restrictions around using XAML from .NET Core.  I'll find out for sure and respond here.

Thanks
--Scott
