### ISSUE TITLE
User.FindAllAsync docs should say which users can be discovered by this method

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/winrt-api#1144]
The Windows.System.User.FindAllAsync() static method's documentation page says it "finds all users asynchronously", and the documentation for that method's overloads with parameters says those overloads find "all" users meeting certain criteria.

Unfortunately, it's not clear what "all users" means for User.FindAllAsync. While I'm not sure precisely what "all" means, I do know that it doesn't actually mean _all_ user accounts stored or ever used on the device. In particular, User.FindAllAsync() can only return information about "real people" (interactive users) _currently signed in_ to the same [Remote Desktop session](https://docs.microsoft.com/en-us/windows/desktop/termserv/terminal-services-sessions) as the calling application. On Windows desktop devices, this means User.FindAllAsync() can find at most one user, since only one user can be signed in to a given session. By contrast, on Xbox One devices, User.FindAllAsync() can find multiple users, because the Xbox One OS allows multiple users to be signed in to the same session (and in fact Xbox only allows 1 session).

Please review and clarify the documentation for User.FindAllAsync to clarify what users it can enumerate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da76212a-227c-89ff-959c-863b65f29519
* Version Independent ID: d46251a4-bb38-88ef-7f39-4c20c2281935
* Content: [User.FindAllAsync Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.user.findallasync#Windows_System_User_FindAllAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.user.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.user.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
