### ISSUE TITLE
How to hang up?

### ISSUE THREAD

**Issue by Aarklendoia** [MicrosoftDocs/winrt-api#1145]
Neither the documentation nor the PhonCall example explains how to hang up. Do you have more information about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53bab3ed-3de8-27eb-a261-ae41abb790a2
* Version Independent ID: 9190cd24-95ba-1627-ffb1-b77d115f9a7e
* Content: [PhoneLine Class (Windows.ApplicationModel.Calls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.phoneline#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.phoneline.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.phoneline.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the mean time you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
