### ISSUE TITLE
Method signature has incorrect const parameter

### ISSUE THREAD

**Issue by Alex-Rose** [MicrosoftDocs/winrt-api#1154]
The parameter `index` should not be const and I also believe that parameter `T` is a const reference. The signature should read: `bool IndexOf(T const& value, uint32_t& index) const;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d728b7-7156-0b95-87aa-ad91cf5819cd
* Version Independent ID: 820479aa-3aa5-710b-b877-7d1bfb2eb6a9
* Content: [IVectorView&lt;T&gt;.IndexOf(T, UInt32) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivectorview-1.indexof#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivectorview_t_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivectorview_t_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Sorry for the delayed response to this issue. The syntax block in our API reference are generated dynamically using reflection over the source files. It seems that since you opened this issue, the syntax generation has been fixed: 

`bool IndexOf(T const& value, [Out] uint32_t & index);`

Thank you for contributing to the accuracy of our documentation!
