### ISSUE TITLE
How to change MinLiveOffset

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/winrt-api#1172]
I want to set LiveOffset to 0. But MinLiveOffset is always about 18s (delay 18s to web browser) and I cannot change it.
Please help (or let it be changeable)!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9272b4d8-952e-a5f3-463c-4cd878aa8405
* Version Independent ID: 06dd4f7d-daeb-edf6-2cdc-f92b00853b4a
* Content: [AdaptiveMediaSource.MinLiveOffset Property (Windows.Media.Streaming.Adaptive) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.streaming.adaptive.adaptivemediasource.minliveoffset#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.streaming.adaptive.adaptivemediasource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.streaming.adaptive.adaptivemediasource.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reaching out, but this feedback mechanism is specifically for documentation issues. Unfortunately, we are not able to provide general technical assistance for development issues.  For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
