### ISSUE TITLE
GetThumbnailsAsync and GetThumbnailAsync returns different results

### ISSUE THREAD

**Issue by tesar-tech** [MicrosoftDocs/winrt-api#1173]
[GetThumbnailsAsync](https://docs.microsoft.com/en-us/uwp/api/windows.media.editing.mediacomposition.getthumbnailsasync) returns different thumbnails then method with single `TimeSpan` as input parameter ([GetThumbnailAsync](https://docs.microsoft.com/en-us/uwp/api/windows.media.editing.mediacomposition.getthumbnailasync)). It should not. Frames from `GetThumbnailsAsync` are "smoother", some of them are same and they should not be. It is similar issue as https://github.com/MicrosoftDocs/winrt-api/issues/309 .

I have created [test project](https://github.com/tesar-tech/GettingThumbnailsTest) that proves inconsistency between these thumbnail getting methods. It is simple UWP app with method that compares bytes from streams returned by GetThumbnails method..

Why is it issue for me? GetThumbnailsAsync **returns wrong results** and GetThumbnailAsync is slow in loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9bf69aa-9f83-5806-4572-79bd12549822
* Version Independent ID: 14fce80a-7ef0-2955-f196-36ff7e2b019b
* Content: [MediaComposition.GetThumbnailsAsync(IIterable&lt;TimeSpan&gt;, Int32, Int32, VideoFramePrecision) Method (Windows.Media.Editing) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.editing.mediacomposition.getthumbnailsasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.editing.mediacomposition.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.editing.mediacomposition.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
