### ISSUE TITLE
MediaFrameSourceGroup.FindAllAsync Method does not return the depth camera.

### ISSUE THREAD

**Issue by lookunder** [MicrosoftDocs/winrt-api#1184]
When calling MediaFrameSourceGroup.FindAllAsync, I do not get the depth camera for the Razer Stargazer, only the color camera. This uses the Intel RealSense2 SR300 driver which I can see installed in the Device Manager under Imaging Devices. The camera works properly with the Intel RealSense Viewer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e3bb9e-8901-f4db-82f3-e28b97b6f3df
* Version Independent ID: 336a4e71-b0e3-ef85-4c45-4b5ed65bc7f8
* Content: [Windows.Media.Capture Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Capture#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reaching out with your feedback. This channel is specifically for issues in the documentation. For technical support support you should consult our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
