### ISSUE TITLE
AccessDeniedException -> System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by samyun** [MicrosoftDocs/winrt-api#1186]
Various APIs in this package reference AccessDeniedException , but that exception doesn't exist. It's actually System.UnauthorizedAccessException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad2072a-e249-6d75-7770-8e9f05917f63
* Version Independent ID: 36891e06-dd39-14fb-8559-5bbf6e4f7574
* Content: [PackageManager.FindPackageForUser(String, String) Method (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackageforuser)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by alvinashcraft** [comment]
Hi @samyun. I'm going through some older docs issues that used to belong to another writer. Could this one be a case where in C++ WinRT apps, you get an AccessDeniedException but for C# apps, it's System.UnauthorizedAccessException?

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
