### ISSUE TITLE
FailIfExists returns E_Fail when renaming file from lower case to upper case

### ISSUE THREAD

**Issue by avknaidu** [MicrosoftDocs/winrt-api#1190]
I would like to rename a file from Lowercase to upper case. So i use the Enum "FailIfExists" for that. But when ever i do that, it throws an exception. Looks like this method is looking for case 
sensitive file name somewhere. Is that expected behavior? or is it a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b2d9c2-5eab-2060-b880-6a21002e9915
* Version Independent ID: b9088e43-907f-8408-7ef5-2e0c6a6b6eaa
* Content: [NameCollisionOption Enum (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.namecollisionoption#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.namecollisionoption.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.namecollisionoption.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by lukeblevins** [comment]
The RenameAsync method does seem to check the case of the new name and compare it to the old one almost as if it creates a new item entirely.

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. Comments here are meant for documentation-specific feedback. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
