### ISSUE TITLE
Argument error handling

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/winrt-api#1195]
What happens when I specify an ID for which a user doesn't exist? Will there be an exception? If yes, what kind of exception? If not, how does the return value look like? Is it 'null'? 

Please specify such information in the documentation. I shouldn't have to write test code to find out how invalid input is handled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b9e1c38-801f-c7d6-11fd-5373a5ec8fde
* Version Independent ID: 3b975e77-d86b-7117-2e50-1a9044455e7b
* Content: [User.GetFromId(String) Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.user.getfromid#Windows_System_User_GetFromId_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.user.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.user.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
