### ISSUE TITLE
Can we please have a cppwirt sample?

### ISSUE THREAD

**Issue by antmor** [MicrosoftDocs/winrt-api#1204]
thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b61186a-4d53-8e97-fbbe-5c46562a65b8
* Version Independent ID: 06bebe97-9d58-94ee-0c14-c6e763e87dc4
* Content: [ToastNotification Class (Windows.UI.Notifications) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotification.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotification.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mijacobs**
* Microsoft Alias: **mijacobs**

**Comment by Karl-Bridge-Microsoft** [comment]
Due to the lack of issue reported here, and the sheer volume of of feedback in this repo requires us to prioritize new issues, we're closing this one due to age and lack of activity.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.
