### ISSUE TITLE
Missing GATT Service "Weight Scale"

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#1209]
In the [GattServiceUuids ](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceuuids) Class it misses the Weight Scale service.

The [Weight Scale service specification](https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Services/org.bluetooth.service.weight_scale.xml)

**Comment by stevewhims** [comment]
Hi, @TimHi, and thanks for filing this issue. I've passed this feedback along to the feature team.

Note that this channel is for feedback about the documentation itself. Here, the docs are correct; I believe that your feedback is that there's no WeightScale member on the type.

You have the option (for questions/feedback about APIs, not about the documentation) to click **Send feedback about** \> **This product**, and you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Just FYI, here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you ever receive assistance via any support resource, and you believe that information would help us improve the docs, then please let us know via this channel.

Thanks!
-Steve
