### ISSUE TITLE
appDiagnostics Capability not required

### ISSUE THREAD

**Issue by vineeththomasalex** [MicrosoftDocs/winrt-api#1215]
I don't think appDiagnostics Capability is required to access AppInfo class. That is probably only required to access the AppInfo property for AppDiagnosticInfo class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e617ca3-d599-55db-4017-b9554bcd5c2f
* Version Independent ID: e740d334-bc23-a021-e9db-7cae750a91da
* Content: [AppInfo Class (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinfo#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.appinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.appinfo.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
