### ISSUE TITLE
VP9 supports for AdaptiveMediaSource?

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/winrt-api#1219]
When I use DASH/HLS with VP9 formated video, MediaPlayer doesn't load

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. In the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
