### ISSUE TITLE
Please update the Application resources and localization sample

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#1234]
The sample link points to a Windows 8 sample, although many of the API's might be consumed the same, this is a UWP API document and the linked sample is not applicable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe82c8a-a9fb-64ab-cfdb-6c27724089f5
* Version Independent ID: 162c916f-aa48-2b28-f807-796f0056e097
* Content: [ResourceMap Class (Windows.ApplicationModel.Resources.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.core.resourcemap#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.resources.core.resourcemap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.resources.core.resourcemap.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
