### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/winrt-api#1250]
This class could use some documentation in how to use it. The API isn't all that hard to understand, but I don't get the content info restoring between launches. What is the value of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a89e182-6fc5-013e-9c50-5216fc0ebd87
* Version Independent ID: 5d93aa6b-dde7-22fd-3fc0-6f837c80a914
* Content: [UserActivityContentInfo Class (Windows.ApplicationModel.UserActivities) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.useractivities.useractivitycontentinfo#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.useractivities.useractivitycontentinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.useractivities.useractivitycontentinfo.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
