### ISSUE TITLE
How do we use CoreWindow in .Net Core

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#1260]
As I understand it, Microsoft.Windows.SDK.Contracts should allow me to build a CoreWindow application in .Net Core, but there is no VS template for .Net Core Desktop application, I only see WPF, WinForms and Libraries. How can we setup a project for .Net Core to target WinRT (UWP) Desktop and employ the CoreWindow application model?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c6426d-2108-e3ab-9e7d-a84736487f85
* Version Independent ID: aa9c7f7b-27b1-e875-d3c6-2fa5908d0289
* Content: [CoreWindow Class (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corewindow.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corewindow.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by adrientetar** [comment]
Currently UWP only runs on .NET Native.

**Comment by Gavin-Williams** [comment]
So CoreWindow is part of UWP and not part of WinRT? 

If I look at https://docs.microsoft.com/en-us/uwp/api/ it is clearly stated at the top of the page ..

**Windows UWP Namespaces**
This section provides detailed information about the Windows Runtime (WinRT) APIs. These APIs are for UWP app development on Windows 10.

So these are the WinRT API's. And they include Windows.UI namespace

It's difficult to see why one WinRT API is regarded as broadly WinRT and another is regarded as the UWP subset of WinRT - they are both Windows 10 technologies. They are very tightly integrated. I see no reason why CoreWindow should be arbitrarily put under UWP banner alone. In usage, it looks like WinRT. It is described as being part of the Windows Runtime.

This (API Contract = Windows.Foundation.UniversalApiContract (introduced v1)) describes the API as being part of the UWP contract, but presumably it says nothing about which concrete API provides the implementation. That would come from the WinRT API Windows.UI.Core.CoreWindow

Also look at the GameChat2 package for example on nuget, It's both WinRT and UWP. 
Microsoft.Xbox.Game.Chat.2.WinRT.UWP

It's not clear why one is WinRT+UWP and the other is a restricted WinRT only available via the UWP contract. 

On the Windows.SDK.Contracts page :  https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts/ it says 'This package includes all the supported Windows Runtime APIs up to Windows 10 version 1903' - Windows.UI.Core is a supported WinRT API isn't it?

I know that there is a lot of work being done to bring the .net's back together, so I'm not oblivious to the potential issues that have arisen while the platforms have been separated - that's the whole point of bringing them back together. I just wanted to bring attention to this particularly frustrating experience as a UWP game/productivity developer trying to see how .net core is at all relevant to me. As it's not even possible to do basic things like build a Windows 10 desktop app in .net core - and I say that almost facetiously, knowing that .net cores supports Winforms and WPF, because CoreWindow and XamlWindow are glaringly absent.

I hope this inconsistency is resolved over the next 12 months.

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams. I'm not sure I can resolve the thread, nor answer the question, but here's some info (FWIW) according to my understanding of the platform(s).

The way Windows APIs are implemented, and called, has evolved over time. From C-based APIs (Win32), through to COM-based APIs, to managed (.NET), and now to Windows Runtime APIs (which are, under the covers, COM-based, although a more highly evolved version of COM). WinRT is short for Windows Runtime.

The Universal Windows Platform (UWP), on the other hand (which arose at around the same time as WinRT, so it's easy to conflate the two), is more about a type of application than it is about APIs. The idea was that you would write an application that was "universal" in the sense that it *could* (if you wrote it in a particular way) run on desktop devices, mobile devices, IoT devices, and so on. So, the UWP (as a platform) was created in order to allow you to write these UWP applications. For UWP applications, Windows Runtime APIs were the natural choice of APIs to call. Within the sphere of UWP applications, there are C++ UWP applications, .NET UWP applications, JavaScript UWP applications.

However, you can call WinRT APIs from other kinds of apps, too, not just UWP apps. You can call WinRT APIs from Win32 apps, for example. Or you can create a .NET (that's not also a UWP app), and consume WinRT APIs from that. Consuming WinRT APIs from a .NET app doesn't necessarily make it a UWP .NET app.

Now, closing the loop back to the Windows.UI.Core.CoreWindow class requires talking about classifying applications into the UI stack that they use. If you're writing a Win32 app, you can choose to use GDI for your UI, or DirectX, and you'd use C++. For an app like that, it's entirely up to you whether you consume any WinRT APIs, but (apart from exceptions such as XAML islands), you wouldn't consume WinRT's UI types. If you're writing a UWP app (which implies that you're consuming WinRT APIs), then you can directly use the CoreWindow WinRT type for your UI (such an app is known as a "Core App"), or you can use XAML (a "XAML app"). To write that UWP app, you could use C++ or you could use C# (and any other language supported by Windows Runtime APIs). And if you use C# then you'd know you were creating a .NET UWP app, because in Visual Studio you'd use the "Blank App (Universal Windows)" project template. If you're writing a .NET-that's-not-a-UWP-app (you're using some other VS project template than the one I just mentioned), then you wouldn't be using WinRT types in your UI. Even if you're using XAML in that .NET app, you still wouldn't be using WinRT UI types.

Which introduces a final wrinkle: that XAML and the UI framework are often conflated. XAML is a markup language; it's basically an object hierarchy serialized into text. Those objects can be WPF UI types, or they can be WinRT UI types (or they can even be other types, not even necessarily UI types). So, "XAML islands" is further subdivided down into WinRT-XAML islands, and WPF-XAML islands.

So, now, coming back to this topic (the Windows.UI.Core.CoreWindow class). This class is a WinRT type, and it's intended to be used from a UWP app. If your language of choice is C#, then you think of a UWP as being synonymous with one of the "Xxx (Universal Windows)" project templates in VS. If you're creating some other kind of .NET app, then it's probably not a UWP app. In which case Windows.UI.Core.CoreWindow won't apply, because you'll be using some other UI stack.

I don't know whether any of this is helpful, but I hope so!
-Steve

**Comment by Gavin-Williams** [comment]
I suppose it depends on the scope of WinUI. Currently CoreWindow is within Windows.UI. Does Microsoft.UI (WinUI) intend to have complete coverage of Windows.UI or just Windows.UI.Xaml.

I should also mention that CoreApplication, CoreApplicationView, IFrameworkView & IFrameworkViewSource are in Windows.ApplicationModel.Core. And there has been no communication as to whether these namespaces will be brought over to .Net 5 (.Net Core X). 

I have window initialization, input and app event code written around the UWP core app (CoreWindow) model. I hope I can eventually use this code in .Net 5 without rewriting it. It would be a convenience. Unless we are going to get a new application / window model that supercedes both UWP and .Net Framework app models?

There is still no way to write a modern UWP/WinRT desktop application without Xaml on .Net Core (ie. outside of the UWP framework). So how do we get UWP games onto other stores?

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. Since this feedback channel is for feedback about the documentation, I'll go ahead and close this issue now, since there's no action I can see to take in the documentation.

If further discussion is needed, we recommend one of these channels:

- [Microsoft Q&A](https://docs.microsoft.com/answers/index.html)
- To engage with the XAML product team or file a product bug, you can [open an issue in the WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) on GitHub.
