### ISSUE TITLE
Missing precondition documentation

### ISSUE THREAD

**Issue by vgromfeld** [MicrosoftDocs/winrt-api#1263]
This method is throwing is `IsEnabled` is false. This should be added to the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4baacf-66ef-063e-5af7-d13f3fd50ee5
* Version Independent ID: deefe87f-5615-b4c9-6000-5540cd6f6fe3
* Content: [MediaPlaybackSphericalVideoProjection.HorizontalFieldOfViewInDegrees Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksphericalvideoprojection.horizontalfieldofviewindegrees)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksphericalvideoprojection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksphericalvideoprojection.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, thanks for your feedback on the documentation. WinRT APIs are designed such that exceptions are intended to provide feedback during app development and should not be caught at runtime. This is one reason our convention is not to document exceptions for WinRT APIs. The exception type and message should be sufficient to let you know the necessary changes in your code. In this example, your code should check the IsEnabled value before trying to set the HorizontalFieldOfViewInDegrees, rather than catching the exception at runtime.

**Comment by vgromfeld** [comment]
I still think that this should be documented. If we do not want to document the exception, there should still be a note saying that the projection must be enabled before trying to change HorizontalFieldOfViewInDegrees.

With the current documentation, we don't know if we should do:
- `IsEnabled = true` then `HorizontalFieldOfViewInDegrees = xx` 
or 
- `HorizontalFieldOfViewInDegrees = xx` then `IsEnabled = true`

We can deduce this by running the app and receiving the exception but things are much easier and less time consuming when the intended usage is clearly documented.
