### ISSUE TITLE
Clarify precision of Point

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#1267]
Can you clarify whether Point always has the precision of float, even when used in C#. The 'projection' in C# says the fields are doubles, but I think that the underlying precision is float, even if I just use it locally. I'm not sure though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14ce5ec-ce18-b937-a1cd-8777faf1750a
* Version Independent ID: 3a181634-c365-6903-e1f8-79cb79201452
* Content: [Point Struct (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.point)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.point.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.point.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. As the last section of this doc says, the Point coordinates are doubles for the .NET projections. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!

**Comment by benstevens48** [comment]
Hi, the issue is that the data is actually stored as single-precision values (I know this for certain now). This means if you construct a point with double-precision values, then precision may be lost, which may be important in some cases. For example, you cannot use a Point to store accurate GPS coordinates. This should be detailed in the documentation since it is not expected and is highly confusing.
