### ISSUE TITLE
Document typical invalidation for IVectorView and IIterator

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1269]
In every conforming implementation I've seen for `IVector`, when the vector contents are modified, it will invalidate all previously obtained views (`IVectorView`) and iterators (`IIterator`), causing them to return `E_CHANGED_STATE` on subsequent operations.

This `HRESULT` is projected as:
- `winrt::error_changed_state` in C++/WinRT
- `Platform::ChangedStateException` in C++/CX
- `System.InvalidOperationException` in .NET/C#

It would be extremely helpful to note this as the typical behavior, as well as providing guidance for implementers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 373e61cf-6eb1-6908-0f87-1fb25449fbed
* Version Independent ID: d2c31fce-5750-c7fd-4fa4-f28bcb202b6f
* Content: [IIterator&lt;T&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.iiterator_t_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.iiterator_t_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.iiterator_t_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by ChrisGuzak** [comment]
#1271 is related

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. There are several related IVectorView issues that I'm consolidating into one internal work item. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
