### ISSUE TITLE
IVector<T>::GetView() does not return a snapshot, page needs to be updated

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#1271]
A snapshot implies a stable copy. The view object returned is not stable if the vector it was created from changes. In that case methods return `E_CHANGED_STATE`.

Update this page to remove the word snapshot and describe the dependency on the underlying vector not changing.

Note, this is also the behavior IIterator<T>,IEnumerator<T>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3a77292-7445-89f6-1c96-d891019afde2
* Version Independent ID: 3d5f2314-f6d6-d778-ecf5-325da7aa119b
* Content: [IVector&lt;T&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivector_t_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivector_t_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivector_t_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
