### ISSUE TITLE
ScrollViewer.IsVerticalScrollChainingEnabled

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/winrt-api#1272]
What is the justification for disabling the scroll chaining? In my project I get blurry list items when setting this. While I can't rule out that it's a self-caused error, it also doesn't happen if I leave this off. Some additional remarks would be beneficial here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10905bc5-b5b3-a7af-5ef1-cde5935dfdc0
* Version Independent ID: 4e7aa8c5-3bf1-dd98-e619-8dbe09b31c72
* Content: [SemanticZoom Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.SemanticZoom#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.semanticzoom.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.semanticzoom.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@adamhewitt627 I'm not sure the reason behind this, but if you are seeing a bug when following this guidance please file a bug on our repo (https://github.com/microsoft/microsoft-ui-xaml).

I've asked @rbrid to explain where this guidance comes from.

**Comment by jwmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
