### ISSUE TITLE
please, either allow System.IO all over HDD, or drastically improve speed of StorageFolder queries

### ISSUE THREAD

**Issue by jtorjo** [MicrosoftDocs/winrt-api#1276]
[uwp] allow System.IO all over HDD or drastically improve speed of StorageFolder queries

My preference would clearly be to just have access to System.IO, once I've requested 
	<rescap:Capability Name="broadFileSystemAccess"/>

This is clearly possible, since a Destkop Bridge app uses System.IO and can do as it pleases. It would clearly be the best case scenario.

Otherwise, StorageFolder queries should become insanely faster. 

I have a 7200rpm HDD, and a folder with 797 pictures. Using System.IO to enumerate the files and get their length is <1ms.

Using a StorageFolder query is simply worse than javascript from 20 years ago - it takes **over 9 seconds**.

### That is >9000 slower.

No matter how you slice or dice it, I don't even have words for how slow this is. 

	StorageFileQueryResult query_result = last_query_;
	if (dir != last_dir_) {
		var folder = await StorageFolder.GetFolderFromPathAsync(dir);

		// https://blogs.msdn.microsoft.com/adamdwilson/2017/12/20/fast-file-enumeration-with-partially-initialized-storagefiles/
		// note: does not seem to be any big diff compared to .GetFilesAsync()
		QueryOptions query = new QueryOptions() {
			FolderDepth = FolderDepth.Shallow,
			//Filter out all files that have WIP enabled on them
			ApplicationSearchFilter = "System.Security.EncryptionOwners:[] ",
			IndexerOption = IndexerOption.UseIndexerWhenAvailable,
			SortOrder = { new SortEntry { AscendingOrder = false, PropertyName = "System.DateModified" }}
		};
		query.SetPropertyPrefetch(PropertyPrefetchOptions.BasicProperties, new List<string>());
		query_result = folder.CreateFileQueryWithOptions(query);
		last_query_ = query_result;
	}

	uint start = 0, len = uint.MaxValue;
	foreach (var f in (await query_result.GetFilesAsync(start,len))) {
		media.Add(new media_info {
			full_file_name = f.Path,
			is_video = is_video(f.Path),
			name = f.Name,
			write_date = f.DateCreated.Date,
			width = 0, height = 0, 
			thumbnail_source = null,
			file_size = (long) await f.GetSizeAsync()
		});
	}

**Comment by lukeblevins** [comment]
This is a very important issue for my app scenario, a file explorer.
Here's a Feedback Hub ticket I filed: https://aka.ms/AA6dgqz

There is a great need my UWP app to have access to System.IO as expected (pictured below)
![image](https://user-images.githubusercontent.com/20365014/67246722-3fa51580-f42d-11e9-9c83-f1f9bcdb1eaa.png)

Otherwise, the speed of Windows.Storage needs to improve since its current state is noticeably worse.

**Comment by lukeblevins** [comment]
Furthermore, I have long been awaiting a formal response from Microsoft regarding the planned improvements to this space. @jwmsft

**Comment by jtorjo** [comment]
Guys, this has been going on for ages. Access to files is paramount - it should be as fast as it gets. How can we develop UWP apps that are slower than written in javascript?

https://www.reddit.com/r/WPDev/comments/4vp7mw/uwp_returning_files_and_folders_incredibly_slow/
https://stackoverflow.com/questions/32668822/faster-way-to-get-files-of-a-folder-than-storagefolder-getfilesasync
https://stackoverflow.com/questions/52214932/uwp-recursive-file-search-in-c-sharp-is-awfully-slow

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and for filing a Feedback Hub submission. However, this feels not so much like feedback specifically about the documentation but rather like a support request. We hope that through your submission you can receive the response you are looking for. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by lukeblevins** [comment]
@lastnameholiu Oh, I see. We needed to report this to feedback hub, so it will be ignored by Microsoft.
