### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by GGDR** [MicrosoftDocs/winrt-api#1294]
Hi, I'm trying to use "LaunchFullTrustProcessForCurrentAppAsync(String)" in Unity3D to launch other exe, it launch exe, but without parameters i needed. I modified manifest, but still no result. Can you help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa090d4-c14c-59fc-6f2a-b33d63f02804
* Version Independent ID: ac019009-73f0-24c6-ef90-446a1bdf9de1
* Content: [FullTrustProcessLauncher.LaunchFullTrustProcessForCurrentAppAsync Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.fulltrustprocesslauncher.launchfulltrustprocessforcurrentappasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.fulltrustprocesslauncher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.fulltrustprocesslauncher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. In the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
