### ISSUE TITLE
 DnssdRegistrationResult doesn't seem to implement IStringable

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/winrt-api#1295]
I have a minimal C++/WinRT application that does Dnssd advertising:

```
IAsyncAction Advertise()
{
	m_socketListener = StreamSocketListener();
	m_socketListener.ConnectionReceived([]
		(StreamSocketListener const& /*sender*/, StreamSocketListenerConnectionReceivedEventArgs const& /*args*/)
	{
		OutputDebugStringW(L"somebody connected to us!");
	});
	co_await m_socketListener.BindServiceNameAsync(m_defaultPort);

	auto hostnames = NetworkInformation::GetHostNames();
	HostName hostName{ nullptr };

	//OG C# code did: NetworkInformation.GetHostNames().FirstOrDefault(x =&gt; x.Type == HostNameType.DomainName && x.RawName.Contains("local"))
	for (auto&& name : hostnames)
	{
		if (name.Type() == HostNameType::DomainName)
		{
			std::wstring_view raw_view = name.RawName();
			if (raw_view.find(L"local") != std::wstring::npos)
			{
				hostName = name;
				break;
			}
		}
	}

	auto portStr = m_socketListener.Information().LocalPort();
	int32_t port = std::stoi(portStr.c_str());

	m_serviceInstance = DnssdServiceInstance(m_dnssdServiceName, hostName, static_cast&lt;uint16_t&gt;(port));

	DnssdRegistrationResult result = co_await m_serviceInstance.RegisterStreamSocketListenerAsync(m_socketListener);
	DnssdRegistrationStatus status = result.Status();
	if (status == DnssdRegistrationStatus::InvalidServiceName)
	{
		OutputDebugStringW(L"DnssdRegistrationStatus: InvalidServiceName\n");
	}
	else if (status == DnssdRegistrationStatus::SecurityError)
	{
		OutputDebugStringW(L"DnssdRegistrationStatus: SecurityError\n");
	}
	else if (status == DnssdRegistrationStatus::ServerError)
	{
		OutputDebugStringW(L"DnssdRegistrationStatus: ServerError\n");
	}
	else if (status == DnssdRegistrationStatus::Success)
	{
		OutputDebugStringW(L"DnssdRegistrationStatus: Success\n");

                auto serviceRecord = result.ToString();
		OutputDebugStringW(serviceRecord.c_str());
	}
}
```

Result is always successful, but the app always crashes when calling `result.ToString()`. I've stepped through the code and the call to QueryInterface returns a nullptr even though the class is declared as supporting `IStringable`.
Also, not sure if related, but the `IPAddress` property is always null.

Can you tell me why this doesn't work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff98b4b-9850-ece2-2e83-faa03c89e9ff
* Version Independent ID: ba7069a5-1c62-d27f-1f6e-40c64239ae6c
* Content: [DnssdRegistrationResult.ToString Method (Windows.Networking.ServiceDiscovery.Dnssd) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd.dnssdregistrationresult.tostring#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.servicediscovery.dnssd.dnssdregistrationresult.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.servicediscovery.dnssd.dnssdregistrationresult.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Holo-Krzysztof, it would make me suspect that the docs were incorrect if the report here were simply that ToString always returns an empty string. But, given that the report is of a crash, PLUS another property is always null, makes this feel more like a product question/feedback and/or a support request (rather than feedback about the documentation).

So I'd recommend pursuing this as a support request, or as a question about the product. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Sorry that I couldn't be of more immediate help here.
-Steve
