### ISSUE TITLE
examples with all flavors or just one.

### ISSUE THREAD

**Issue by ergan89** [MicrosoftDocs/winrt-api#1297]
I wonder if you ought to make the snippets show only the variant that i'm interested or all the variants. ie. if i selected winrt, I only wanna see examples for winrt but i see C++/winrt & C++ & JavaScript. Also, C++ is misleading without /CX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61bf27d-d169-da09-5c90-25a4448488a4
* Version Independent ID: ccc5fdef-a25a-6eba-5a91-64d1eae4484c
* Content: [DataReader Class (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
We're working on improving all our sample code as time permits. We are also changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
