### ISSUE TITLE
keyMaterial explanation is misleading.

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#1322]
It is completely useless to create a hash if you can't re-create the hash later on to test it against. Therefore the 'keyMaterial' provided should be known data. It could be random data, but then you'd have to make sure you stored the random data so you could use it again to create the same hash. The remarks should make it clear that using the same 'keyMaterial' will result in the same hashes being produced by the returned CryptographicHash for the same input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108134fc-3906-41f8-cf9f-18c1bda18028
* Version Independent ID: 99534d07-db48-d4f0-1c33-7e0cd896cd46
* Content: [MacAlgorithmProvider.CreateHash(IBuffer) Method (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.macalgorithmprovider.createhash#Windows_Security_Cryptography_Core_MacAlgorithmProvider_CreateHash_Windows_Storage_Streams_IBuffer_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.macalgorithmprovider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.macalgorithmprovider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @benstevens48 , thanks for submitting your feedback. I'll go ahead and add a work item to clarify and expand the explanation for keyMaterial.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since shortly after the creation of this Issue, so I went ahead and created an internal work item to incorporate your suggestions. The changes should appear on the live site later today. I will go ahead and close this, but I will circle back if any issues arise with the publishing. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
