### ISSUE TITLE
This property doesn't appear to be normalized to 1024

### ISSUE THREAD

**Issue by Ryken100** [MicrosoftDocs/winrt-api#1330]
In practice, this property doesn't appear to be normalized to 1024. When using this property, I'm only able to set a value between 0 and 1, going outside of this range causes the InputInjector to stop functioning completely, even for non-pen inputs.

Additionally, the pressure seems to be scaled from 0 to 0.25, meaning when the Pressure property is set to 1, the injected input that other apps receive will only have a pressure of 0.25. When the Pressure property is 0.5, apps receive a pressure of 0.125. Is it possible for me to get full pen pressure out of this API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5522ad3-7a08-6d3f-e8b8-d37385caad1f
* Version Independent ID: 01efc933-26d4-7515-c335-83001b8d2b82
* Content: [InjectedInputPenInfo.Pressure Property (Windows.UI.Input.Preview.Injection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.injectedinputpeninfo.pressure#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.preview.injection.injectedinputpeninfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.preview.injection.injectedinputpeninfo.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
This feedback is not specifically about the documentation, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
