### ISSUE TITLE
Add Support for Multi-Image HEIF Containers

### ISSUE THREAD

**Issue by moutasem1989** [MicrosoftDocs/winrt-api#1337]
The[ HEIF Bitmap-Decoder ](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmapdecoder.heifdecoderid#Windows_Graphics_Imaging_BitmapDecoder_HeifDecoderId)under Windows.Graphics.Imaging can only decode the main page in the HEIC Image Container. Please add support to extract other pictures, meta data from this file format. the [HEIC File Format Extension](https://www.microsoft.com/de-de/p/heif-bilderweiterungen/9pmmsr1cgpwg?activetab=pivot:overviewtab) in the store is paid and should contain all the features.

**Comment by drewbatgit** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
