### ISSUE TITLE
MidiMessage from Raw

### ISSUE THREAD

**Issue by medwedby** [MicrosoftDocs/winrt-api#1338]
Hi, Is it possible to create MidiMessage objects from Raw data or any other way to save and load these objects, Thanks!

**Comment by hkhmsft** [comment]
Hey @medwedby , thanks for reaching out with your feedback. Is there anything you'd like to see on our documentation that could potentially help solve your roadblock? If else, I'm thinking there might be answers to your specific issue on our developer resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
