### ISSUE TITLE
Is CastingSource a must for this method call?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/winrt-api#1339]
What I am understanding from the description. It seems that the connection can be established without a casting source. Is it correct?

Actually, I am developing an app to directly cast the whole desktop to Sink device, not specific to any media source. How can I do it?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 335e5d34-e109-c941-3271-3eeb1f6cefd1
* Version Independent ID: 23b6fac5-ce6b-aa50-9baa-e4558e55aa1d
* Content: [CastingConnection.RequestStartCastingAsync(CastingSource) Method (Windows.Media.Casting) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.casting.castingconnection.requeststartcastingasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.casting.castingconnection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.casting.castingconnection.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
