### ISSUE TITLE
StoreAsync doesn't make sense for folks coming from DataWriter streams on other languages

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/winrt-api#1342]
I burnt well over an hour on this, taking knowledge from other languages like Java and C# where you just Write and then Flush a writer to get it to write to a stream. But for some weird reason, Windows.Storage.Streams also requires you to `Store`. But only sometimes? That's super wacky. Why can't this just be a construction variable or property set on the Writer to make it more sensible like other frameworks without this weird extra step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f9098f-5c80-77eb-f11c-212997cb8554
* Version Independent ID: 1a69f9cd-e2d0-97d9-27e2-96177baad85f
* Content: [DataWriter.StoreAsync Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datawriter.storeasync#Windows_Storage_Streams_DataWriter_StoreAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datawriter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datawriter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like product feedback. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
