### ISSUE TITLE
How to evaluate between Duplicate Values in VirtualKey enum

### ISSUE THREAD

**Issue by StevenEdwardWood** [MicrosoftDocs/winrt-api#1343]
VirtualKey.Hangul and VirtualKey.Kana both have a ushort value of 21.
VirtualKey.Hanja and VirtualKey.Kanji both have a ushort value of 25.
How do we differentiate between these two when our app receives a value of 21 or 25? Is it language dependent? If so then what language determines which enum.  If not then what is the meaning of these characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf98772b-2d62-70f3-9a17-0e6bf58a236a
* Version Independent ID: d32568d4-d904-46e3-254d-43a240d2a37f
* Content: [VirtualKey Enum (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.System.VirtualKey?source=docs#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkey.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkey.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It is true that these enums share the same integer value, however they are still separate enums and will function the same as any other enum (except when casting from an int to an enum). See [this StackOverflow thread](https://stackoverflow.com/questions/8043027/non-unique-enum-values) for more information.

Please let me know if you have any other questions, otherwise I'll consider this issue closed.
