### ISSUE TITLE
maxNumberOfItems UInt32

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#1345]
maxNumberOfItems is of type UInt32 and it is said that -1 retrieve all files, but… -1 is not a UInt32 value and therefore cannot be set as is.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c3db85fe-ef65-74ee-2551-b7301c050993
* Version Independent ID: 806767cf-a970-6ea8-284d-2550674f7b3f
* Content: [StorageFileQueryResult.GetFilesAsync Method (Windows.Storage.Search) - Windows UWP applications](https://docs.microsoft.com/fr-fr/uwp/api/windows.storage.search.storagefilequeryresult.getfilesasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DFR-FR%26k%3Dk(Windows.Storage.Search.StorageFileQueryResult.GetFilesAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.storagefilequeryresult.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.storagefilequeryresult.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
