### ISSUE TITLE
Event never fired

### ISSUE THREAD

**Issue by fntc** [MicrosoftDocs/winrt-api#1353]
The PosPrinter StatusUpdated is never fired. Tried with different machines and OPOS implementations behind but never got the event. Same for PosPrinter.Status which always says Online no matter what the power status of the printer is.

For a CashDrawer i get a StatusUpdated however.

With Microsoft Pos for .net 1.14.1 Events from printer can be received

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f77f860-4c55-13ec-c1ca-3fef3cab3578
* Version Independent ID: e4147f9e-fbf5-9c1b-1d0d-40194f700bbb
* Content: [PosPrinter.StatusUpdated Event (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.posprinter.statusupdated#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.posprinter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.posprinter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @fntc, thanks for filing this issue. Since this isn't feedback specifically about the documentation, I'd recommend you pursue it as a support request, or as a question about the product.

You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Sorry that I couldn't be of more immediate help here.
-Steve
