### ISSUE TITLE
FindLocationsAtAsync return wrong CountryCode for Switzerland

### ISSUE THREAD

**Issue by marquisolivier** [MicrosoftDocs/winrt-api#1359]
This code with 47.0 and 8.0 (in Switzerland) :
```
static async Task TestCountryCode()
{
    IReadOnlyList<MapLocation> locations = await PlatformGetPlacemarksAsync(47, 8);
    string wrongCountryCode = locations.FirstOrDefault().Address.CountryCode;
}

static async Task<IReadOnlyList<MapLocation>> PlatformGetPlacemarksAsync(double latitude, double longitude)
{
    Geopoint point = new Geopoint(new BasicGeoposition { Latitude = latitude, Longitude = longitude });
    MapLocationFinderResult queryResults = await MapLocationFinder.FindLocationsAtAsync(point);
    return queryResults?.Locations;
}
```
returns SWZ. It should be CHE for Switzerland.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70eb31d7-f370-1216-1887-1486309d2ad5
* Version Independent ID: 303ca933-8e83-7808-0db3-3c06ba0277bf
* Content: [Windows.Services.Maps Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.services.maps)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.maps.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.maps.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
