### ISSUE TITLE
SavingData only allowed when suspending?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1373]
ExtendedExecutionSession in a running app scenario is always denied it seems, if SavingData is used as the reason; while the Unspecified ends up Allowed. It is not clear if this behavior is specific to particular test device, or will also have effect for the entire Universal Platform.
If SavingData case is reserved for certain specific scenarios, rather than as an abstract Reason categorizer, that should probably be reflected in the documentation to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2753ab-6324-eec9-5690-0bda0bc7752f
* Version Independent ID: 821568c4-ada4-08db-a7b7-0f3d308afbac
* Content: [ExtendedExecutionReason Enum (Windows.ApplicationModel.ExtendedExecution) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.extendedexecution.extendedexecutionreason)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.extendedexecutionreason.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.extendedexecutionreason.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
