### ISSUE TITLE
Using StepForwardOneFrame throws exception

### ISSUE THREAD

**Issue by Diolk** [MicrosoftDocs/winrt-api#1375]
I've noticed inaccurate positioning in my application. Therefore tried using the above StepForwardOneFrame directly after Pause. This throws an exception:

Exception thrown: 'System.Exception' in SimplePdfViewer.exe
System.Exception: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at Windows.Media.Playback.MediaPlayer.StepForwardOneFrame()
   at SimplePdfViewer.MainPage.PauseMediaPlayer(MediaPlayer mp)

The message 'Catastrophic failure' isn't exactly helpfull in determining what is going on. 
When catching the Exception, everything seems to work fine further in the application, however I'm still confused if positioning is accurate now.

I think a working example on this page would be very helpfull.

Coding isolated:
        private void PauseMediaPlayer(MediaPlayer mp)
        {
            mp.Pause();
            // According to documentationn StepForwardOneFrame is necessary after pause for accurate positioning
            // For some reason the framework throws an exception (which is not documented)
            try { mp.StepForwardOneFrame(); } catch (Exception ex) { Debug.WriteLine(ex.ToString()); }
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96fc0f6-3226-9c44-d5ff-b869d0f4b441
* Version Independent ID: b144f7b7-e19f-c924-323c-03b59a52a540
* Content: [MediaPlaybackSession.Position Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksession.position#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksession.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, I made a quick sample app and tested your scenario and was unable to reproduce your issue. Generally speaking, the WinRT APIs are designed so that your code shouldn't have to handle exceptions at runtime. The fact that this was a "catastrophic error" means that something unusual occurred that isn't related to the specific API, like a disk failure, for example. It's possible that there could be something about your video file or your device that is causing this error, or you may have found a bug.

GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
