### ISSUE TITLE
AddOrReplace(String, IStorageItem) -> Parameter is incorrect exception

### ISSUE THREAD

**Issue by jtorjo** [MicrosoftDocs/winrt-api#1380]
[Enter feedback here]
This is BEYOND STUPID.
Besides the fact that this whole API is idiotic, AddOrReplace will **actually throw** if I use the path of the StoredItem as a token 

    StorageFile f = ...;
    StorageApplicationPermissions.FutureAccessList.AddOrReplace(f.Path, f);
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6053945-bd5c-4385-e702-ba70654d5e16
* Version Independent ID: 6a285f7b-46de-efa2-752a-a63bfb6a6571
* Content: [StorageItemAccessList.AddOrReplace Method (Windows.Storage.AccessCache) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist.addorreplace)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
