### ISSUE TITLE
How To Use This Interface?

### ISSUE THREAD

**Issue by NickWPF** [MicrosoftDocs/winrt-api#1383]
&lt;desktop3:CustomStateHandler Clsid="f0c9de6c-6c76-44d7-a58e-579cdf7af263"/&gt;
            &lt;desktop3:ThumbnailProviderHandler Clsid="3d781652-78c5-4038-9999-ec5940ab560a"/&gt;
            &lt;desktop3:ExtendedPropertyHandler Clsid="3d781652-78c5-4038-5555-ec5940ab560a"/&gt;
            &lt;desktop3:BannersHandler Clsid="3d781652-78c5-4038-4444-ec5940ab560a"/&gt;
            &lt;desktop3:CloudFilesContextMenus&gt;
              &lt;desktop3:Verb Id="Command1" Clsid="165cd069-d9c8-42b4-8e37-b6971afa4494" /&gt;
            &lt;/desktop3:CloudFilesContextMenus&gt;
            &lt;desktop4:ContentUriSource Clsid="97961bcb-601c-4950-927c-43b9319c7217"/&gt;
          &lt;/desktop3:CloudFiles&gt;

I don't know how to register it, somebody help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9156a30d-8bcc-a431-e482-3cc25d06c0b7
* Version Independent ID: 7a0c9b5d-3028-75bb-ae2c-b31cebcae22a
* Content: [IStorageProviderPropertyCapabilities Interface (Windows.Storage.Provider) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.istorageproviderpropertycapabilities)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.provider.istorageproviderpropertycapabilities.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.provider.istorageproviderpropertycapabilities.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
