### ISSUE TITLE
Bug BasicProperties.Size is 0 when using bulk access

### ISSUE THREAD

**Issue by Ponant** [MicrosoftDocs/winrt-api#1400]
BasicProperties.Size is oftentimes zero when accessing this property from a FileInformation. It is also zero when using 
await FileInformation.GetBasicPropertiesAsync(). Other properties, such as the file name, or Dimensions from the ImageProperties return the correct result.
This is most likely a bug in the API? The only way to get the correct result is to access it via a storage file,
        BasicProperties basicProperties = await file.GetBasicPropertiesAsync();
where file is a StorageFile and not a FileInformation.
https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.basicproperties

**Edit**
Renaming the folder containing the file seems to resolve the issue, so this is a rather strange issue.
Any help appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39252bac-9f39-e7f3-7622-6d63e6a98b03
* Version Independent ID: 4fd0a13e-2248-7bd6-2b3a-d7bb56b02b88
* Content: [FileInformation.BasicProperties Property (Windows.Storage.BulkAccess) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.bulkaccess.fileinformation.basicproperties#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.bulkaccess.fileinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.bulkaccess.fileinformation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @Ponant , we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
