### ISSUE TITLE
DHCP support when assignedClientIPv4list and assignedClientIPv6list are set to NULL

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1406]
I tried setting v4 and v6 assigned IP to null. However, there was no DHCP request seen going out from the system via VPN plugin callbacks. 
I would expect encapsulate callback to be called with a DHCP request generated by the system. Am i missing anything here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dfc8f2c-fc91-a4c2-7706-c50f3c96d4d6
* Version Independent ID: fb7bc7b7-aa5f-e645-1364-5939a2a22ec4
* Content: [VpnChannel.StartWithMainTransport(IVectorView&lt;HostName&gt;, IVectorView&lt;HostName&gt;, VpnInterfaceId, VpnRouteAssignment, VpnDomainNameAssignment, UInt32, UInt32, Boolean, Object) Method (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnchannel.startwithmaintransport)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnchannel.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnchannel.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @defaultshr, and thanks for filing this issue.

This is the right channel for feedback about the actual documentation (missing or incorrect info, for example). But I think it'd be better pursuing this issue as a question about the product, rather than as feedback about the documentation.

You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Sorry that I couldn't be of more immediate help here.
-Steve
