### ISSUE TITLE
Need C++/WinRT Examples

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/winrt-api#1434]
Even when I have "C++/WinRT" selected as the language, the examples are still in C#.  Please add examples in C++/WinRT for this and many other XAML pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ad25f2-d06e-135c-240c-99c8a0cfa728
* Version Independent ID: eccc6b3a-5607-158c-2ed6-949293923f2d
* Content: [TextBlock Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textblock#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textblock.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textblock.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @dr-eck, and thanks for filing this issue.

Providing in-topic code examples illustrating usage of individual Windows APIs, and patterns of API usage including cross-feature patterns, is an important and ongoing workstream that's driven by priorities (those priorities are in turn influenced by customer input such as this issue, and the fact that you're asking about this). Our priorities come in tiers of increasing urgency. If you take a topic that has *no* code examples, then as a priority we'd want to provide a code example in *one* language. After that, in more than one language. Ultimately, in *all* languages. Another priority is that if a topic has C++/CX code examples, then the same code examples should *also* appear in C++/WinRT.

This topic has C# code examples, and it doesn't have C++/CX examples, so it's not in the tier of highest priority for attention. So, I'll make a record of this ask, and put it onto my backlog. Since I don't have a schedule that I can share regarding when I might find time to convert the C# code here into C++/WinRT, I'll close this issue for the time being. We can revisit progress at some time in the future.

Until we have a C++/WinRT code example in this topic, one suggestion would be for you to study the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) documentation, which contains lots of code examples showing many different techniques for calling Windows Runtime APIs from C++/WinRT (including XAML UI types such as this one, and including a topic about porting from C#). It's likely that you'll learn enough there to convert the C# code here to C++/WinRT. In addition, any topic (across the Windows dev content) that has a C++/CX code example now also has a C++/WinRT code example.

Thanks!
Steve
