### ISSUE TITLE
JsonObject.HasValue is inaccessible due to its protection level

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-api#1444]
It seems like that `JsonObject.HasValue(string)` is not public anymore, since it cannot be called anymore:

![image](https://user-images.githubusercontent.com/16122379/74109829-421bae80-4b87-11ea-9d7d-726aa93564f9.png)

This happened on Windows Insider Preview 15559.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0647fb-d434-85ab-fc3b-127bfbfd7210
* Version Independent ID: 9aedde57-b902-015e-e829-ee34becb12b2
* Content: [JsonObject.HasKey(String) Method (Windows.Data.Json) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject.haskey#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.json.jsonobject.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.json.jsonobject.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
From C# code, please use the ContainsKey method instead of HasKey.

This is an unfortunate by-product of how .NET languages like C# behave in UWP apps. In this case, the JsonObject class implements [IMap](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.imap_k_v_). Notice the important note at the top of this article: in C# and other .NET languages IMap appears as as [IDictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2.containskey?view=netframework-4.8). Therefore, instead of using HasKey (which is part of IMap), you need to use ContainsKey (which is part of IDictionary).

The unfortunate fact that the JsonObject docs generates an article for HasKey instead of ContainsKey is a by-design behavior with how these docs get generated (technically speaking, HasKey is the correct method and is in fact method you'd call in a in a C++ UWP app). I'll add a note to point readers to ContainsKey, and in the future we hope to have an automated fix for this case across all our WinRT reference docs.

**Comment by marcelwgn** [comment]
Thank you for your fast response @mcleanbyron . I didn't know that C# in UWP would actually result in different API behaviors. If you want I can also create a PR to add a note to the page.

**Comment by mcleanbyron** [comment]
No need to add a note, I'm taking care of that myself - thanks! For a list of the UWP types that map to .NET types with a different name and/or namespace (for example, in this case IMap corresponds to IDictionary in .NET languages), see [this article](https://docs.microsoft.com/windows/uwp/winrt-components/net-framework-mappings-of-windows-runtime-types#uwp-types-that-map-to-net-types-with-a-different-name-andor-namespace).

**Comment by marcelwgn** [comment]
Thank you for the link to the article, that is extremely helpful!
