### ISSUE TITLE
Why is there a limit of 20 credentials per app?

### ISSUE THREAD

**Issue by andy-schmidt** [MicrosoftDocs/winrt-api#1460]
Sure Windows 10 devices have the resources to securely store more than 20 credentials per app. Why are you artificially limiting apps to 20 credentials?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63001b53-c7d5-2890-0e31-38b6827efcd0
* Version Independent ID: 670486a9-a969-3761-8ef2-d34049e24aab
* Content: [PasswordVault.Add(PasswordCredential) Method (Windows.Security.Credentials) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.passwordvault.add)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.credentials.passwordvault.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.credentials.passwordvault.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like product feedback. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by andy-schmidt** [comment]
The feedback is that the documentation is far too limited to understand how
to use the API correctly. For example, is there a 20 device limit because
storing the credentials securely uses a large amount of storage and CPU
resources?
