### ISSUE TITLE
Calling Package.CheckUpdateAvailabilityAsync() within an async method that returns a Task causes app to hang

### ISSUE THREAD

**Issue by gradyal** [MicrosoftDocs/winrt-api#1476]
I'm experiencing some really strange behavior with Package.CheckUpdateAvailabilityAsync(). Whenever I use it within an async method that returns a Task, as soon as it hits the line with Package.CheckUpdateAvailabilityAsync(), the app hangs. If I change the method to return void, it works.

It's a Winforms application running on .NET Framework 4.8. And my Windows version is 10.0.19041. 

Here is what I see in the Windows Application Event Logs within Event View:
The program MyWinformsApp.exe version 3.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 54dc
 Start Time: 01d5ee83cf44dc2e
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\IMSPolicy.local_1.0.33.0_neutral__3v2kfav467psa\App\MyWinformsApp.exe
 Report Id: 2c0a4885-0448-4947-888d-8e5f9257f28c
 Faulting package full name: MyApp.local_1.0.33.0_neutral__3v2kfav467psa
 Faulting package-relative application ID: App
 Hang type: Quiesce

And here is my code:
```csharp
public async Task CheckForUpdateAsync()
{
   try
   {
       var packageManager = new PackageManager();
       _currentPackage = packageManager.FindPackageForUser(string.Empty, Package.Current.Id.FullName);

       _logger.Info("Checking for updates...");
       var update = await _currentPackage.CheckUpdateAvailabilityAsync();

       /* Update app */
   }
   catch (Exception ex)
   {
       _logger.Error("An error occurred while attempting to update the package", ex);
   }
}
```

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by gradyal** [comment]
@lastnameholiu I've reported a problem through the developer community [here](https://developercommunity.visualstudio.com/content/problem/952407/calling-packagecheckupdateavailabilityasync-within.html). I linked back to this issue in case documentation needs to be adjusted. My guess is this is a bug, so you're probably right that no documentation changes are needed. Thanks!
