### ISSUE TITLE
SphericalVideoProjection not always up to date

### ISSUE THREAD

**Issue by HunterB06** [MicrosoftDocs/winrt-api#1486]
`MediaPlaybackSession.SphericalVideoProjection` seems to be populated after some event occured.
Depending on the moment when you try to read this value, you could end up with an unexpected (default?) value.

For example, if you open a spherical video and try to read this value in `NaturalDurationChanged` event, you could have a `FrameFormat` that is not `SphericalVideoFrameFormat.Equirectangular` whereas it will in `BufferedRangesChanged`.

This behaviour is not documented, thus we don't know when we can rely on the `SphericalVideoProjection` value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b8e2f3-7219-bf64-3cf9-bc045fc7be3c
* Version Independent ID: ea351592-bd99-4c72-7bd9-41804508ca62
* Content: [MediaPlaybackSession.SphericalVideoProjection Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksession.sphericalvideoprojection#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksession.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.

**Comment by HunterB06** [comment]
Hello,

I got the information I needed from the developers. Actually the properties I mentioned above are guaranteed correct after `MediaPlayer.MediaOpened` event has raised. Before that event, we can't know.

I think this information should be made explicit to the documentation as it can lead to undefined behaviours otherwise.
