### ISSUE TITLE
"Full Trust?"

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/winrt-api#1578]
It would be helpful to document what "full trust" means for this class. My guess is that this "full trust" naming is just creating awareness that the code is working around UWP's usual limitations, but one could be led to thinking that this launches a process with elevated privileges.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aa76ad-d68d-53a1-8821-526ae1f618e4
* Version Independent ID: a3a99abf-5843-057e-dcc9-027d524bcd37
* Content: [FullTrustProcessLauncher Class (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.FullTrustProcessLauncher)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.fulltrustprocesslauncher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.fulltrustprocesslauncher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mikben**
* Microsoft Alias: **mikben**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
