### ISSUE TITLE
Style "all in one page" is hard to read

### ISSUE THREAD

**Issue by jjakubovic** [MicrosoftDocs/winrt-api#160]
New style of the docs, where everything is in one page (class description, and detailed descriptions of all its properties, events, methods, ...) is hard to read. It's hard to get an overview from this layout, it's overwhelming. Structuring would help. Like in the old msdn docs, where you had class description on one page, together with table of properties, events, methods with SHORT description of each. And each property/event/method had separate page with detailed description.

Example of bad, "all in one page" documentation, FrameworkElement:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement

Example of good, structured documentation, IDirect3DDevice9:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb174336(v=vs.85).aspx

I wonder whose idea it was to ruin the good old msdn documentation like this... :-(. Pardon my expressive language.

**Comment by mattwojo** [comment]
Hi @jjakubovic - Thanks for sharing your experience with us. It was time to update the MSDN docs as the hosting environment had growing problems and a lot of limitations. We are mostly very happy with the new docs.microsoft environment, though there were some trade-offs and we're continuing to work on improvements. One trade-off was going with the longer doc pages... Your example is a good one of a page that is VERY long and hard to digest.  Unfortunately because of all of the automated tooling involved, it's not a simple fix for us, but **it is something we're aware of and actively working on.** 
One of the good things about the new system is that it's "OP" -- meaning that if you see something that isn't right and you know how to correct it or make it better, you can just click the "edit" button and do it. We're hoping that these contributions from our feature teams and from the community using the APIs will lead to better overall docs. It is a culture shift for us, but it seemed like the right thing to do. We're catching up with folks who have been working in open publishing for a long time, but trying hard to make this a good experience supporting all of our various sorts of developers. 

Thanks again for taking the time to point out this very needed area of improvement. I'd like to close this issue if it's alright with you as we are tracking it internally on the build system for docs.microsoft, but if there are any other areas for improvement that you are seeing --- please continue to point them out. We really do value it and want to make the Windows docs a good experience for our devs.

**Comment by ChrisGuzak** [comment]
I agree with @jjakubovic's feedback.  

A mitigation to consider... enable the parts of the page to be collapsed and add a "collapse all" button that puts the whole page into a summary/outline mode.

**Comment by mattwojo** [comment]
Thanks @ChrisGuzak - I'll be sure that the API Ref docs working group knows these concerns and suggestions.

**Comment by jjakubovic** [comment]
Thanks, Matt. You can close the issue if it's tracked internally.

And pardon me my last sentence, that was a bit expressive. I know a bit about angry customer feedback so I try not to act like this. I read API docs quite often and I was a bit frustrated from the new docs style that day.

**Comment by mattwojo** [comment]
Ha... thanks @jjakubovic.  We're just happy that your are reading the docs... and I'll take expressiveness over indifference any day! :)  Still tracking this, but going to resolve as it's in the internal tracking.
