### ISSUE TITLE
How to use this interface?

### ISSUE THREAD

**Issue by SuperDcer** [MicrosoftDocs/winrt-api#1612]
[Enter feedback here]
How to use this interface? I use a class to Implement this interface, but never trigger the 'OnMessageReceived' event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdd397-4787-ebfb-09da-66834ae500fb
* Version Independent ID: 4adeef8e-a45e-e0a4-ca2b-ab243cfc0728
* Content: [IGipGameControllerInputSink Interface (Windows.Gaming.Input.Custom) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.custom.igipgamecontrollerinputsink?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input.Custom/IGipGameControllerInputSink.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input.Custom/IGipGameControllerInputSink.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

[Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
