### ISSUE TITLE
Windows.Data.Html.HtmlUtilities.ConvertToText(inputString); <b></b><ul></ul> tags are not supported in UWP app

### ISSUE THREAD

**Issue by Uma-Raja-ZSCST0058** [MicrosoftDocs/winrt-api#1614]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26202847-c423-8281-763b-140244a9d5ee
* Version Independent ID: 867bc5f0-487f-1b0c-bf01-1ec01e676048
* Content: [HtmlUtilities.ConvertToText(String) Method (Windows.Data.Html) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.html.htmlutilities.converttotext?view=winrt-18362#Windows_Data_Html_HtmlUtilities_ConvertToText_System_String_)
* Content Source: [winrt-api-build/xml/Windows.Data.Html/HtmlUtilities.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Data.Html/HtmlUtilities.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. Can you please provide more information about how you learned this information? Did a member of a Microsoft product team pass this information to you, is this something that you discovered via testing, or something else?

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
