### ISSUE TITLE
Users of our Software get the same ID when calling GetSystemIdForPublisher()

### ISSUE THREAD

**Issue by bytefactory73** [MicrosoftDocs/winrt-api#1619]
We found a few collisions between users on different continents with different machines.

source: UEFI
identifier: LlPR8RAlAPgk-yF5UaJUv3-KyfWxl0pFiCCiOyio5c0= 

we asked the users for a cpu-z report:

user 1:
Mainboard Model 151-BE-E097 (0x0000025D - 0x0A74C7F0)
UEFI Yes
BIOS Vendor American Megatrends Inc.
BIOS MSG 63-0100-000001-00101111-091015-Chipset
BIOS Date 09/10/15
Mainboard Vendor 000001

user 2:
Mainboard Model Z87M Extreme4 (0x00000444 - 0xECE9B6D4)
UEFI Yes
BIOS Vendor American Megatrends Inc.
BIOS MSG 63-0100-000001-00101111-121015-Chipset
BIOS Date 12/10/15
Mainboard Vendor 000001

How could that happen?

The documentation clearly states:

The ID has the following characteristics:
* Unique for each system

Thx for looking into that.

**Comment by bytefactory73** [comment]
Additional Info, We have 60 users worldwide which return the same machine id.

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
