### ISSUE TITLE
Add Navigate(Type, object) and Navigate(Type, object, NavigationTransitionInfo) to INavigate

### ISSUE THREAD

**Issue by radujipa** [MicrosoftDocs/winrt-api#1622]
The Frame class implementation of this interface has two additional overloads on the Navigate method: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame.navigate?view=winrt-18362

For testing purposes, it would be really useful if the INavigate interface included those methods as it would simplify the creation of mocks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe15c910-f1ae-059e-96eb-e299450d067c
* Version Independent ID: 785ed16c-831c-5481-195d-3f5e66835675
* Content: [INavigate Interface (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.inavigate?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/INavigate.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/INavigate.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi @radujipa , it looks like your feedback is a feature request for the class, rather than about the documentation. To ensure that the correct team gets your feature request, please consider leaving product feedback. (You got here by clicking _Send feedback about > This page_. If you instead click _Send feedback about > This product_, then you'll be taken to the right channel to leave product questions/feedback. Or [click here](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) to open an issue in the microsoft-ui-xaml repo.
Thanks
