### ISSUE TITLE
RequestRateAndReviewAppAsync

### ISSUE THREAD

**Issue by MarcellusMusic** [MicrosoftDocs/winrt-api#1630]
Hi -  is RequestRateAndReviewAppAsync currently supported in WinRT for JavaScript?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcd68611-5213-ca2f-3798-1b3f2a020dbe
* Version Independent ID: b2f1b115-9e5d-5870-00e4-dd9859e403bc
* Content: [StoreContext.RequestRateAndReviewAppAsync Method (Windows.Services.Store) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.requestrateandreviewappasync?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Services.Store/StoreContext.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Services.Store/StoreContext.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jdannemann** [comment]
It is supported by WinRT on the JavaScript side of things.

**Comment by MarcellusMusic** [comment]
Great, @jdannemann! Thank you for confirming on your side!

**Comment by JudahGabriel** [comment]
Got a sample of that working? We tried [this code, no luck](https://github.com/pwa-builder/PWABuilder/issues/720#issuecomment-620282972).

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
