### ISSUE TITLE
Document thread-safety limits of observable collections (including ValueSet and PropertySet)

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1635]
`Windows.Foundation.Collections.ValueSet` and `Windows.Foundation.Collections.PropertySet` are thread-safe for keeping the collection consistent across multiple readers and writers as long as there are no subscribers to the notification events. Other implementations of `IObservableVector` and `IObservableMap` may also provide this safety, but it is not guaranteed.

However, as soon as observers come into play, this guarantee no longer holds up. `IVectorChangedArgs` does not carry the changed value, only the index of where the change occurred. Similarly, `IMapChangedArgs` only carries the key of the change, not the value. Due to this API design, when an observer receives a change event, it needs to retrieve the value at the specified index/key as part of the event handler.

This means that if a different thread performs another modification of the collection during an existing change notification, the observer runs the risk of retrieving a different or nonexistent value during the notification, which violates the implied contract of the change events.

Due to this reason, `ValueSet` and `PropertySet` (and other ostensibly thread-safe observable collections) will throw an error if the collection is modified while it is invoking changed event handlers. To avoid this error, collections with subscribed observers need to have their changes serialized onto a single thread, and we need to document this fact.

**Comment by metathinker** [comment]
#1644 is an example of the kind of question the docs requested by this bug would answer.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
