### ISSUE TITLE
Signature is lacking details on signing method

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/winrt-api#1700]
"Signature" is lacking details on signing method. 

Please provide details on the signing method and cryptographic keys used to generate this signature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d758b4f-a129-68a6-5b1f-00a640924202
* Version Independent ID: 92531220-57ac-7602-e2b8-ed1d20d8298d
* Content: [HardwareToken.Signature Property (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.hardwaretoken.signature?view=winrt-19041#Windows_System_Profile_HardwareToken_Signature)
* Content Source: [winrt-api-build/xml/Windows.System.Profile/HardwareToken.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Profile/HardwareToken.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
