### ISSUE TITLE
In what format are these certificates?

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/winrt-api#1701]
Without information on what format these certificates are in this documentation is not very helpful.

A remark, that this returns a certificate chain and not a single certificate might also be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953a303a-4854-66f5-1140-8052bf8bc652
* Version Independent ID: 87ff3b8d-f12a-6403-e4d3-1006a190f8d9
* Content: [HardwareToken.Certificate Property (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.hardwaretoken.certificate?view=winrt-19041#Windows_System_Profile_HardwareToken_Certificate)
* Content Source: [winrt-api-build/xml/Windows.System.Profile/HardwareToken.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Profile/HardwareToken.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
