### ISSUE TITLE
Task entry point described as required when it is not

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1706]
The page says
>The task must have ... a task entry point for the Register method to succeed.

but setting entry point is not required (and makes no sense?) for an in-process background task.
See https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-an-inproc-background-task#register-your-background-task-trigger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a105604-59a7-6f1f-eb51-88e6eff2af65
* Version Independent ID: 7f7671c5-383b-10f4-2d51-2bf74ce77db3
* Content: [BackgroundTaskBuilder.Register Method (Windows.ApplicationModel.Background) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.backgroundtaskbuilder.register?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Background/BackgroundTaskBuilder.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Background/BackgroundTaskBuilder.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks and resolve this doc bug. I'm creating a PR for the change today, and the update doc should be live this week. So, I will go ahead and close this today. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
