### ISSUE TITLE
Build fail with SDK 10.0.19041.0 for FindPackages

### ISSUE THREAD

**Issue by supercairos** [MicrosoftDocs/winrt-api#1713]
Hi, 

When I try to build with the latest SDK, build fail with error:
error C3779: 'winrt::impl::consume_Windows_Foundation_Collections_IIterable<winrt::Windows::Foundation::Collections::IIterable<winrt::Windows::ApplicationModel::Package>,T>::First' :  a function that returns 'decltype(auto)' cannot be used before it is defined
        with
        [
            T=winrt::Windows::ApplicationModel::Package
        ]
see declaration: 'winrt::impl::consume_Windows_Foundation_Collections_IIterable<winrt::Windows::Foundation::Collections::IIterable<winrt::Windows::ApplicationModel::Package>,T>::First'
        with
        [
            T=winrt::Windows::ApplicationModel::Package
        ]

Here is an example of the bug. 
https://github.com/supercairos/FindPacakgesBugWinSDK

Changing in general option of the projet Windows SDK from 10.0.18362.0 to 10.0.19041.0 show the bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 708a3ece-610f-6481-ac54-59e49359fb1d
* Version Independent ID: f15dc0e2-c450-0bef-bde0-2de09f784f15
* Content: [PackageManager.FindPackages Method (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackages?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Management.Deployment/PackageManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Management.Deployment/PackageManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mcleanbyron** [comment]
I'm sorry you're running into an issue with this API. This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
