### ISSUE TITLE
Missing documentation for System.Devices.PhoneLineTransportDevice.Connected

### ISSUE THREAD

**Issue by nimazure** [MicrosoftDocs/winrt-api#1715]
System.Devices.PhoneLineTransportDevice.Connected is a property used with the DeviceInformation APIs to see if a PhoneLineTransportDevice is connected. Without the documentation of this property, app developers will not be able to deterministically know when a PhoneLineTransportDevice is connected. Please add documentation for this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68b59878-a4b2-85de-d0ec-b1c07bcad978
* Version Independent ID: 5c0304ae-113b-30dd-5848-a31866d31370
* Content: [PhoneLineTransportDevice Class (Windows.ApplicationModel.Calls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.phonelinetransportdevice?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Calls/PhoneLineTransportDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Calls/PhoneLineTransportDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Hi @nimazure. In which version(s) of the SDK does PhoneLineTransportDevice have a Connected property? Is it public? I don't see that property on the object when I create a UWP project and use Object Browser in VS.

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. There is currently no Connected or DeviceStatus property in the available APIs.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
