### ISSUE TITLE
Section referenced, does not exist

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1728]
COMException description says "see the Error Codes section below" but there is no Error Codes section anywhere on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0645ed9f-c0d8-a8a2-5d1d-8fc16fea0690
* Version Independent ID: 071bbfc6-4522-38e8-4074-4c94471060cb
* Content: [UploadOperation.StartAsync Method (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.uploadoperation.startasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.BackgroundTransfer/UploadOperation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.BackgroundTransfer/UploadOperation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @avakhrushev, and thanks for filing this issue. This problem was present in three topics, and I have fixes for them going through the publishing pipeline now. I have a TODO in my notes to check periodically to make sure that the changes go live, so I'll go ahead and close the issue now.

Thanks again!
Steve
