### ISSUE TITLE
Section referenced, does not exist

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1729]
COMException description says "see the Error Codes section below" but there is no Error Codes section anywhere on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfbf6f6a-e8a1-1683-f9fc-93054c911c6b
* Version Independent ID: f8466491-c957-a6dd-baca-bf45df1cd4e7
* Content: [DownloadOperation.AttachAsync Method (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.downloadoperation.attachasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.BackgroundTransfer/DownloadOperation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.BackgroundTransfer/DownloadOperation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @avakhrushev, and thanks for filing this issue. This problem was present in three topics, and I have fixes for them going through the publishing pipeline now. I have a TODO in my notes to check periodically to make sure that the changes go live, so I'll go ahead and close the issue now.

Thanks again!
Steve
