### ISSUE TITLE
Document IIterator.GetMany() more thoroughly

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1732]
Unlike IIterator.Current, GetMany advances the iterator once for each element retrieved.

In addition, it doesn't retrieve *all* the elements in the collection. The number of elements retrieved is the lesser of:
- The number of elements remaining between the current iterator position and the end of the collection (inclusive)
- The number of elements the output array can hold.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cdf9b35-2563-ca23-bffc-20f83828bbd8
* Version Independent ID: d33e833a-4188-2595-98e2-9c0f1c230055
* Content: [IIterator&lt;T&gt;.GetMany(T\[\]) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.iiterator-1.getmany?view=winrt-19041#Windows_Foundation_Collections_IIterator_1_GetMany__0___)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IIterator`1.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IIterator`1.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
