### ISSUE TITLE
Miracast

### ISSUE THREAD

**Issue by luojc123** [MicrosoftDocs/winrt-api#1739]
[Enter feedback here]
How can Win32 use MiracastSDK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdc18356-805d-3a43-d008-b6ba87010fb6
* Version Independent ID: 54db1584-d0fd-aca5-18c5-24ea1958fa95
* Content: [Windows.Media.Miracast Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.miracast?view=winrt-19041)
* Content Source: [winrt-api-build/xml/ns-Windows.Media.Miracast.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Media.Miracast.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
