### ISSUE TITLE
User::FindAllAsync(...): Which user is the "current" one for this process?

### ISSUE THREAD

**Issue by twhall-umich** [MicrosoftDocs/winrt-api#1742]
The documentation for the deprecated UserInformation class leads us here, to User::FindAllAsync(...) for Windows 10.  But there's nothing here that says how to determine which user in the returned vector is the "current user" -- the owner of this process.  It was suggested to me elsewhere to specify the arguments Windows::System::UserType::LocalUser and Windows::System::UserAuthenticationStatus::LocallyAuthenticated.  But what if there are multiple LocallyAuthenticated LocalUsers -- e.g., from one or more "Switch user" occurrences?  That should be documented here.  Also, specifying those arguments in an app running on the HoloLens 2 while authenticated via a Microsoft account caused FindAllAsync(...) to return an empty vector; I had to remove both restrictions to get a non-empty vector.

And how does any of this relate to the system id returned by

    System::Profile::SystemIdentification::GetSystemIdForUser(nullptr).Id();

for which the documentation says "pass null into this method, which gets the current user's ID."  There doesn't appear to be any way to use that system ID to determine which user, among the vector returned by FindAllAsync(...), is the "current user".

These are some critical details missing from the C++/WinRT documentation in regard to getting reliably the identity of the user that owns the process.  It ought to be a simple task.  I seek only the AccountName and DisplayName, to support a collaboration feature in our app -- the equivalent of GetUserNameW(_, _); and GetUserNameExW(_, _, _); in non-UWP Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da76212a-227c-89ff-959c-863b65f29519
* Version Independent ID: d46251a4-bb38-88ef-7f39-4c20c2281935
* Content: [User.FindAllAsync Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.user.findallasync?view=winrt-19041#Windows_System_User_FindAllAsync_Windows_System_UserType_Windows_System_UserAuthenticationStatus_)
* Content Source: [winrt-api-build/xml/Windows.System/User.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/User.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
