### ISSUE TITLE
How to get properties of the "current user"?

### ISSUE THREAD

**Issue by twhall-umich** [MicrosoftDocs/winrt-api#1743]
The documentation says, "pass null into this method, which gets the current user's ID."  But there's no documented way to use the returned system ID to obtain the properties of the "current user."  I cannot get a User object from this system ID, therefore I cannot get any other properties.  In particular, I seek the login ID and display name for the "current user" -- the owner of this process -- for a collaboration feature in our app.

I can get a list of users from System::User::FindAllAsync(...), but how do I determine which of those users is the "current user"?  I tried iterating through that vector, calling GetSystemIdForUser(user).id() for each, and comparing with the value returned by GetSystemIdForUser(nullptr).id(), but none of them compared equal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd2dc05-fa79-6ac6-ee32-0be55fc989e6
* Version Independent ID: 018fe01b-738f-1f0f-e91f-784fed8e641d
* Content: [SystemIdentification.GetSystemIdForUser(User) Method (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforuser?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System.Profile/SystemIdentification.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Profile/SystemIdentification.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
