### ISSUE TITLE
Please change whitelist to allow list

### ISSUE THREAD

**Issue by GossiTheDog** [MicrosoftDocs/winrt-api#1744]
Hi - please align whitelist to allow list as part of race-insensitive language work.

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7673988-90bd-d4f7-6b34-12139d25f5e8
* Version Independent ID: 93301ddf-7a0c-7286-8e2b-1f9eab9f3f0d
* Content: [ProcessLauncher.RunToCompletionAsync Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.processlauncher.runtocompletionasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System/ProcessLauncher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/ProcessLauncher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the extremely delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and resolved this doc bug. The changes should be pushed live sometime today, so I will go ahead and close this issue. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
