### ISSUE TITLE
xxxProperty properties from parent classes not being pull down

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1746]
Properties like "IsChecked" are being pulled down from the parent class, but "IsCheckedProperty" are not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132e9b09-3ca4-67ce-69ea-e92a38c04b1d
* Version Independent ID: 425dfac1-9bd8-c56a-e41e-4d983adcb43f
* Content: [CheckBox Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.checkbox?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.CheckBox)%3Bk(VS.XamlEditor)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=winrt-19041#properties)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/CheckBox.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/CheckBox.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
I think this depends on the language; not all languages/projections inherit static members.

**Comment by jwmsft** [comment]
Thanks for the feedback. This behavior is by design to keep the properties lists on class pages from being twice as long as they already are. For inherited properties, only the actual property is shown in the properties list, but not the dependency property identifier (xxxProperty). When you click (for example) IsChecked, you're taken to the property on the parent class, ToggleButton.IsChecked. On ToggleButton, you'll find both IsChecked and IsCheckedProperty, because they aren't inherited in that context.
