### ISSUE TITLE
Add possible return values of the string 

### ISSUE THREAD

**Issue by BillCarlson** [MicrosoftDocs/winrt-api#1747]
I would love to have the information about possible values being returned - for example "Windows.Xbox", "Windows.Mobile", "Windows.Desktop" and other potentials, and under what circumstances they are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c62c532-03ab-7ceb-f17c-2071b848e696
* Version Independent ID: 40064398-4737-7eeb-be33-5ba52b0acf3c
* Content: [AnalyticsVersionInfo.DeviceFamily Property (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.analyticsversioninfo.devicefamily?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System.Profile/AnalyticsVersionInfo.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Profile/AnalyticsVersionInfo.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
