### ISSUE TITLE
Documentation is Incomplete

### ISSUE THREAD

**Issue by tuggernuts** [MicrosoftDocs/winrt-api#1755]
The documentations states that EnsureSuccessStatusCode "will throw an exception if the server doesn't return a successful HttpStatusCode..." The documentation does not say what kind of exception, which is good to know and program against.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13879c56-9f47-db7a-916a-02fd13c1a96a
* Version Independent ID: 673df973-430e-e878-2420-4466a3463f5f
* Content: [HttpResponseMessage.EnsureSuccessStatusCode Method (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.ensuresuccessstatuscode?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Web.Http/HttpResponseMessage.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web.Http/HttpResponseMessage.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, and thanks for filing this issue. I'll contact the feature team to try to find out how this method is supposed to be used. And I'll get back to you here.

This isn't straightforward for me to answer because, except in rare cases, we don't document exceptions for a couple of reasons.

One reason is that a well-designed API throws only under conditions where the API isn't being used correctly. So, those conditions can (and should) be found and fixed at development/debug time. So, for a well-designed API, it'd be unnecessary to write production code that catches exceptions. The idea of this design is that for a condition such as an unplugged ethernet cable, where that's not a programming error, the API should not be throwing exceptions; but rather APIs should be able to communicate that condition in parameters or return values (if possible).

The other reason is that a Windows Runtime API itself indicates success/failure by returning an HRESULT value, and certain values result in programming-language-specific exceptions. So while we can document HRESULTs (and we do so for COM APIs), it's not that straightforward for Windows Runtime APIs.

We do have rare examples of APIs not following this prescription, and so we can document HRESULT values there.

As I say, I'll try to find out and get back to you.

-Steve

**Comment by tuggernuts** [comment]
Thanks, Steve.

If you look at the method in question, its whole purpose is to throw an exception. So in this case, the API is designed to throw an exception when a certain condition isn’t met. One wouldn’t call it without expecting it to throw. Thus, production code has to anticipate the exception, handle it, and move on.

Thanks for looking into it, and I look forward to the response from the feature team.

Jerry

**Comment by PeterSmithRedmond** [comment]
The actual exception thrown is a little vague, on purpose. Underneath, the actual code that implements this just returns an error HRESULT -- for example, it might return 0x80190194. That in turn gets converted into an exception in a way that depends entirely on the language projection. For C#, a System.Exception is thrown. That system.exception, in turn, includes the original HRESULT.

As a handy tip: the HRESULT encodes the original HTTP error. Just strip off the 0x8019 and you get 0x0194 -- which in decimal is 404.

You've probably already noticed that there's an IsSuccessStatusCode  property that merely returns a boolean that says if the return code is a success code (2xx series) or not; if you don't want to deal with exceptions, it's a great way to get the same functionality.

**Comment by tuggernuts** [comment]
That is great info & very helpful. Thank you Peter.

Have a great weekend.

Jerry

**Comment by stevewhims** [comment]
Thanks for the info, all! I have updates in the pipeline that add these details to the topic. I'll make sure those changes make it to the live site.

Thanks again!
Steve
