### ISSUE TITLE
`string.Empty` response is not documented

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/winrt-api#1763]
There is no documentation to explain what an empty string response means.
Is it the same as for [showaddappointmentasync](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appointments.appointmentmanager.showaddappointmentasync?view=winrt-19041)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a3ec88d-5578-52e8-957d-d8adcad1586c
* Version Independent ID: 11cf9865-6b5f-7b9e-4dc4-0a0d413bcace
* Content: [AppointmentManager.ShowEditNewAppointmentAsync(Appointment) Method (Windows.ApplicationModel.Appointments) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appointments.appointmentmanager.showeditnewappointmentasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Appointments/AppointmentManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Appointments/AppointmentManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Hi Matt @mrlacey. Thanks for submitting your feedback and we apologize for the very late response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item resolve this doc bug. I found the spec for this API and the string.Empty response does indicate the same result as the other API. I'm updating the wording on this page to match the other, and the changes should be merged and live later today.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
