### ISSUE TITLE
No C++ examples

### ISSUE THREAD

**Issue by cycollins** [MicrosoftDocs/winrt-api#1771]
Regardless of the language chosen in the header, the sample, which is pretty much the entire documentation, is always in C#. As someone who had done the conversion to WinRT C++, I can say with confidence that is a non-trivial task to make all the C#->C++ mappings, including the idiosyncrasies of co_await, IAsyncOperation, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7d92f04-6d6c-54e0-dcaf-0c2b3b63b2ac
* Version Independent ID: 32ad8a6f-2de7-2f1b-2ef7-b5d0ea69b6e4
* Content: [DataProtectionProvider Class (Windows.Security.Cryptography.DataProtection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.dataprotection.dataprotectionprovider?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography.DataProtection/DataProtectionProvider.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography.DataProtection/DataProtectionProvider.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Thanks, @cycollins, and sorry about the long delay in responding.

That language picker affects only the syntax block. It's not intended to filter code examples. API reference isn't the best place for code examples, anyway, since typically a code example shows several APIs working in concert; and not just how to use one particular API.

Providing code examples in C# is the first priority. Then, usually if the scenario would especially benefit from it, we try to provide a C++/WinRT version also. For example, the [Win2D "Hello, World!" quickstart](https://learn.microsoft.com/windows/apps/develop/win2d/hellowin2dworld) does have a C++/WinRT version. There are many hundreds of similar cases across the docs.

However, that wouldn't be good ROI for every code example. Many of them are quite mechanical to port to C++, once you've followed the specific pattern a few times. So for those cases, we have resources such as the [C++/WinRT](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/) content in general, and then the [Porting the Clipboard sample to C++/WinRT from C#—a case study](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp) and [Move to C++/WinRT from C#](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp) topics in particular.

So I'll close this issue for now.

-Steve
