### ISSUE TITLE
Making windows hello prompt more user friendly

### ISSUE THREAD

**Issue by giregk** [MicrosoftDocs/winrt-api#1780]
I'm using Windows.Security.Credentials.UI/UserConsentVerifier in my UWP app. I have two problems with this API:

- first, the windows hello prompt always opens a window that does not have the focus. The window is opened bellow all other windows which make it completely unusable for my users: they don't understand what to do and for those who do, an extra click is required which is extremely annoying. I suggest the windows hello prompt always appears on top of everything else, or at least on top of the app that calls it.

- Second, I would like to prevent the fallback to the windows hello pin code in case the facial or biometric recognition fails since I already have a password mechanism in my app. Could you add an option for this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a08974-c0bf-fb28-17af-182c3e5182eb
* Version Independent ID: 35d34b8d-9d0d-76b5-f5d7-9c6b1999545d
* Content: [UserConsentVerifier Class (Windows.Security.Credentials.UI) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.ui.userconsentverifier?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Credentials.UI/UserConsentVerifier.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Credentials.UI/UserConsentVerifier.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. It seems your Issue leans more towards product feedback rather than specific documentation fixes. 

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
