### ISSUE TITLE
ASHWID description

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/winrt-api#1783]
There is a page describing *ASHWID* technical details, but it is in "outdated" state - https://docs.microsoft.com/en-us/previous-versions/windows/apps/jj553431(v=win.10)?redirectedfrom=MSDN
Has the *ASHWID* format changed?

And a related question - can *ASHWID* contain more than one `CPU` record?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7fe9a0-1527-9b5f-e795-c1280c2d9efc
* Version Independent ID: 668c6c9d-0779-98d6-6685-064c1ed09518
* Content: [HardwareIdentification Class (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.hardwareidentification?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System.Profile/HardwareIdentification.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Profile/HardwareIdentification.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
