### ISSUE TITLE
sealed class in WinRT for C++

### ISSUE THREAD

**Issue by PerArneS68** [MicrosoftDocs/winrt-api#1786]
[Enter feedback here]

Documentation for colors describes the colors class as a sealed class. Should this be "final" instead of "sealed"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8443d66a-2f59-9d31-5d6f-ca1f3e8438c7
* Version Independent ID: bcb2374c-572b-ecb4-d989-0cd1f300e3cf
* Content: [Colors Class (Windows.UI) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.colors?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI/Colors.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI/Colors.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @PerArneS68, and thanks for filing this issue. Yes, that's an issue with the content build system. The keyword should be "final" for the C++/WinRT language projection. I filed a bug on this in August and it's currently assigned to a developer.

I'll continue to track the bug internally, so I'll go ahead and close this issue since we're already aware of the bug, and working on it.

Thanks again!
Steve
