### ISSUE TITLE
Device Enumeration does not respect mDNS TTL

### ISSUE THREAD

**Issue by FredeJ** [MicrosoftDocs/winrt-api#1799]
It should probably be noted in the documentation that the current implementation of device enumeration, when used with mDNS based services does not respect the TTL.

This means that where one would expect the `Removed` event to be fired after 30 seconds if the service broadcasts a TTL of 30, it is instead fired after 120 seconds (the default). This is surprising behavior which should either be documented or fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999c2404-3f05-6f6d-e99c-4a7ba2fd4937
* Version Independent ID: 6a83b396-e999-e8d7-ddd2-55e18d83b526
* Content: [DeviceWatcher.Removed Event (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher.removed?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Enumeration/DeviceWatcher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Enumeration/DeviceWatcher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by stevewhims** [comment]
Thanks, @FredeJ. This one sounds in a gray area between "this is definitely wrong with the docs" and "this is definitely wrong with the product". And this one does sound like a potential product issue, I'd say. 

For feedback or questions about the product/feature/APIs, like this, you can click **Submit and view feedback for** \> **This product** (instead of **This page**), and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
-Steve
