### ISSUE TITLE
Missing ImageBrush Properties in Sidebar

### ISSUE THREAD

**Issue by robloo** [MicrosoftDocs/winrt-api#1800]
It seems the SideBar does not have properties other than ImageSource listed for the ImageBrush. In the article content all properties are listed though. I guess this might be expected behavior as they are inherited properties. Still it's strange not to see them listed in this case.

![image](https://user-images.githubusercontent.com/17993847/92028646-6234da00-ed32-11ea-9647-d6f437ecddeb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14996b47-2e38-8307-f366-b9ac86720a9b
* Version Independent ID: 214851f8-8273-c865-da02-ca5bf1ef7b9c
* Content: [ImageBrush Class (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imagebrush?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Media/ImageBrush.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Media/ImageBrush.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi @robloo, you're correct that it's by design that inherited properties aren't shown in the sidebar. 

While it would make sense to show all properties for a case like ImageBrush, which has a fairly limited number of properties, a typical XAML control like [CalendarView](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.calendarview) has well over 100 inherited properties. It quickly becomes unusable to put them all in the sidebar, so the decision was to only list inherited properties in the page content.

**Comment by robloo** [comment]
Ok, understood. At first look I didn't see the properties were inherited but after I noticed it made some sense. I'll go ahead and close this then. Thanks!
