### ISSUE TITLE
Can you mention the dll name or nuget package somewhere ?

### ISSUE THREAD

**Issue by benjisanders** [MicrosoftDocs/winrt-api#1802]
Can you mention the dll name or nuget package somewhere ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a4349a-7559-a295-6734-fca2d63f5b87
* Version Independent ID: bd544b90-08e8-611a-5566-24c9abff1e02
* Content: [Windows.System.UserProfile Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile?view=winrt-19041)
* Content Source: [winrt-api-build/xml/ns-Windows.System.UserProfile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.System.UserProfile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing other new feedback. These WinRT APIs are all included with the Windows SDK and not individually downloaded. If you believe your feedback is still valuable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
