### ISSUE TITLE
Why the return value of "AccessibilitySettings.HighContrastScheme" is not in English? Why? 

### ISSUE THREAD

**Issue by YellingSky** [MicrosoftDocs/winrt-api#1815]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43f27b91-2c8d-3e16-791b-2ea7b1db1361
* Version Independent ID: be6f110d-58d7-19e1-95d8-816d94863420
* Content: [AccessibilitySettings.HighContrastScheme Property (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.accessibilitysettings.highcontrastscheme?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.ViewManagement/AccessibilitySettings.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.ViewManagement/AccessibilitySettings.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by YellingSky** [comment]
I need use the API to get the system highContrastScheme, but the response of the API is not in English, This causes me to be unable to judge the return value in my code.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @YellingSky, can you be more specific? Please provide an example of the return value you're getting.

**Comment by YellingSky** [comment]
> 
Below is my code sample:

this.windowsObj = this.Windows.UI.ViewManagement.AccessibilitySettings();
const highC = this.windowsObj.highContrast;
		if (highC) {
			const highCC = this.windowsObj.highContrastScheme;
			console.log(`highContrastScheme ${highCC}`);
		}

my system language is Chinese simple, and the "highContrastScheme" api return a Chinese string instead of English string, so I can not use it in my code.

**Comment by YellingSky** [comment]
![HighContrastScheme](https://user-images.githubusercontent.com/62685597/93586324-ba2e3a80-f9da-11ea-8cf8-1b6ac0c9272c.png)
@Karl-Bridge-Microsoft  it my code screenshot

**Comment by YellingSky** [comment]
@Karl-Bridge-Microsoft 
Do you have any update for it?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @YellingSky  - This feedback is not specifically about the documentation, but rather a support request. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.

Here is a list of other developer support resources that might be able to help with your issue:

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
