### ISSUE TITLE
Generated C++/WinRT code references guid incorrectly

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/winrt-api#1817]
The sample code/prototype refers to `Guid` when it's actually (`winrt::`)`guid`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f946a825-3818-f531-f83c-e2579e5109c4
* Version Independent ID: eb85de1a-9187-74f8-4b01-14e3506c5904
* Content: [DisplayModeInfo.Properties Property (Windows.Devices.Display.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaymodeinfo.properties?view=winrt-19041#Windows_Devices_Display_Core_DisplayModeInfo_Properties)
* Content Source: [winrt-api-build/xml/Windows.Devices.Display.Core/DisplayModeInfo.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Display.Core/DisplayModeInfo.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rpavlik, and thanks for filing this issue. I've created a bug internally with the content engineering team, and I'll continue to monitor that bug for progress. For issues with the syntax block, like this, the folks writing the documentation can't control that, nor fix it. It's the build system owned by the content engineers that controls the syntax block, so we work with that team to fix issues such as this.

Since I'm tracking this issue internally, I'll go ahead and close this. But I have a note of the new bug on my bug-tracking list and I have a record of this GitHub issue next to that, so I'll be able to come back here with an update as soon as the bug is fixed.

Thanks again!
Steve

**Comment by stevewhims** [comment]
UPDATE: The fix for this bug is live.

-Steve
