### ISSUE TITLE
DispatcherQueueTimer sample should use DispatcherQueue.GetForCurrentThread()

### ISSUE THREAD

**Issue by scott-moore-ms** [MicrosoftDocs/winrt-api#1827]
The code sample for DispatcherQueueTimer uses DispatcherQueueController.CreateOnDedicatedThread() to create a new DispatcherQueue just for that timer instance, which isn't something anyone would do and is confusing.

The canonical usage for this API would be to create a timer on the dispatcher associated with the currently running thread - the sample should use DispatcherQueue.GetForCurrentThread() to fetch the DispatcherQueue from the current thread and then call CreateTimer() on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de717875-912f-6404-1f6e-f25048f74ac2
* Version Independent ID: f25562b6-df93-b31b-b362-54533fe5be73
* Content: [DispatcherQueueTimer Class (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuetimer?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
