### ISSUE TITLE
TryGetChangeTracker throws FileNotFoundException

### ISSUE THREAD

**Issue by HunterB06** [MicrosoftDocs/winrt-api#1847]
I tried using `TryGetChangeTracker` but I always get a `FileNotFoundException` whereas it is never mentioned in the documentation that it can throw.
The guilty line is this one:

```C#
KnownFolders.MusicLibrary.TryGetChangeTracker();
```

I joined a very simple solution so that you can reproduce the issue.

[TryGetChangeTrackerTest.zip](https://github.com/MicrosoftDocs/winrt-api/files/5379486/TryGetChangeTrackerTest.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e1cfca-48a7-65ab-6d8e-1389ffb1b2a2
* Version Independent ID: b4166c41-9885-df9e-5582-4902f39e609c
* Content: [StorageFolder.TryGetChangeTracker Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.trygetchangetracker?view=winrt-19041#Windows_Storage_StorageFolder_TryGetChangeTracker)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFolder.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFolder.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by ChrisGuzak** [comment]
this is a bug. Try APIs should not throw given correct usage.

**Comment by hkhmsft** [comment]
Thanks for letting us know about this @HunterB06 and sorry you're experiencing this. You can try the following resources if you need additional tech support. @ChrisGuzak is there anything actionable on the documentation end? If so, let me know and I'll reopen this thread and look further into it.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
