### ISSUE TITLE
Page mentions a non-existing section

### ISSUE THREAD

**Issue by angela-yan** [MicrosoftDocs/winrt-api#1853]
There are a few methods in this page (Eg. FromBluetoothAddressAsync(UInt64) etc) mentions 'Remarks' section, but there is no Remarks section in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a05df98-9097-754c-4f8e-0a3b277ed5a7
* Version Independent ID: 405cca73-bc63-ce19-69ec-8a460156857a
* Content: [BluetoothLEDevice Class (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @angela-yan, and thanks for filing this issue. Yes, the problem here is that those descriptions (the descriptions that include "See Remarks") are authored on the individual member topics themselves, and they're referring to the Remarks section of the individual member topics themselves. However, those descriptions are also copied out of the individual topics by the content build system and displayed in the table that you're seeing on the class topic. So when you read that copy of the description, it's not clear which Remarks section is being referenced.

I've published a fix to make it clear that we're referring to the Remarks section in the member topic, rather than the class topic ("See **Remarks** in the member topic").

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue, since it looks like it's resolved now.

Thanks again!
Steve
