### ISSUE TITLE
How to use IStorageProviderItemPropertySource

### ISSUE THREAD

**Issue by Dmitriyverkhov** [MicrosoftDocs/winrt-api#1872]
Hi!
I have created a class StorageProviderItemPropertySource : IStorageProviderItemPropertySource and implemented method GetItemProperties.
Can my implementation be registered in registry and used by system ?
If yes, how can I trigger the system to call method from my implementation ?

Regards,
Dmitriy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5673872c-21d1-8139-96f9-f090078bdcca
* Version Independent ID: 8af4a74b-a3dc-0a0c-28c2-0c98e460d4ba
* Content: [StorageProviderItemProperties Class (Windows.Storage.Provider) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovideritemproperties?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage.Provider/StorageProviderItemProperties.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Provider/StorageProviderItemProperties.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. I think your best bet would be to post this question over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html), since our scope covers specific doc fixes.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by tangp3** [comment]
Facing the same [issue here](https://learn.microsoft.com/en-us/answers/questions/1011885/how-to-use-istorageprovideritempropertysourcegetit.html).

Searching for documentation how to use IStorageProviderItemPropertySource::GetItemProperties.

@Dmitriyverkhov, were you able to address this issue ?
