### ISSUE TITLE
Please add header files to the generated documentation

### ISSUE THREAD

**Issue by joshtriplett** [MicrosoftDocs/winrt-api#1879]
Generated documentation pages for WinRT types, such as https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networksecuritysettings?view=winrt-19041 , list the namespace (`     Windows.Networking.Connectivity `), but don't document what header file to include for that namespace (`#include <winrt/Windows.Networking.Connectivity.h>`). When trying to debug missing include files (related to https://devblogs.microsoft.com/oldnewthing/20190530-00/?p=102529 and https://github.com/microsoft/xlang/pull/427 ), as far as I can tell, you just have to know the conventional pattern and infer the corresponding header name based on the namespace.

Given that the documentation is generated, please consider automatically generating a full `#include` line for the right header file to use, alongside the `Namespace:` line. That would be convenient for copy-pasting, and for helping people learn the conventions from the documentation.

cc @ilmatic (ran into this when working with them to debug an issue)

**Comment by stevewhims** [comment]
Hi, @joshtriplett, and thanks for filing this issue.

I'll start a conversation internally and if this is felt to be the right spec then I'll work with the content engineers to make it happen.

Btw, the include pattern is basically: for every type you use, include the header for the namespace the type is in. That pattern is described in the "Important" section toward the middle of the [Get started with C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/get-started) topic. And then it's repeated occasionally across the the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/) content. Once folks are familiar with that simple pattern, I wonder whether they'll then consider the "#include" clue in the syntax block to be noisy and/or redundant, since it's essentially a copy (albeit transformed a little) of the namespace that's shown a couple lines higher on the page. So, if we do this, for any given topic we'll be using the same namespace that's already there, and applying the same transform every time. There won't be anything in the value-add that's unique to the topic. Just a thought.

But, as I say, I'll start a discussion and see what folks think. :)

Thanks again!
Steve

**Comment by joshtriplett** [comment]
@stevewhims When you call functions that return other types, and elide all the types using `auto`, you often won't end up thinking about what namespace something lives in. This would help people learn that pattern; people don't always start with the introductory documentation.

Perhaps eventually, this could live within `C++` example code, alongside the `C#` example code which won't need to list it.

**Comment by stevewhims** [comment]
@joshtriplett, thanks! So, I've filed an internal work item to consider this feature. Since we're tracking the work internally, and if it's actioned then it's likely to be a substantial length of time before that happens (since this feature requires more parts of the page to be a function of the chosen language than just the syntax block, and that's something the infrastructure doesn't support yet), I'll go ahead and close this issue if you don't mind. This new work item is on a list of items whose progress I look at from time to time, so rest assured that it will be tracked going forward. Here's the description of the new feature being requested:

In WinRT API reference topics, when the selected language is C++/WinRT (and only then), add a new button to the right of the namespace name as illustrated in this PNG. 

![copy-cpp-include-directive](https://user-images.githubusercontent.com/31261191/99738323-1404bc80-2a7f-11eb-990b-751b1264e0a5.png)

When the button is clicked, the namespace name is taken, transformed (as specified below), and placed onto the Clipboard.

Here's the transform. Let's say the namespace is Windows.X.Y. Then transform that into the following include directive:

#include <winrt/Windows.X.Y.h>

Thanks!
Steve

**Comment by joshtriplett** [comment]
@stevewhims Thank you! And no objections to closing this issue. If possible, it would be nice if this issue gets a notice if the internal issue ends up changing status (declined or accepted).

**Comment by stevewhims** [comment]
@joshtriplett, yes, I'll do that. The internal work item has a link to this issue, so they're connected, and I'll come back here when we know the status of the internal work item.

Thanks!
Steve
