### ISSUE TITLE
C++/WinRT syntax blocks shouldn't show "abstract" and "sealed"

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1897]
Neither of these are C++ keywords. Take the example of [`Windows.Foundation.PropertyValue`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.propertyvalue?view=winrt-19041). The C# syntax block doesn't show these keywords:
```c#
public static class PropertyValue
```
so why does the C++/WinRT syntax block show these?
```c++
class PropertyValue abstract sealed
```

I've noticed that it seems to be static classes like `PropertyValue` and `Windows.Foundation.GuidHelper` that are getting the `abstract` keyword. I speculate this bug may have something to do with them having no instance methods, only static methods?

**Comment by stevewhims** [comment]
I've turned the "abstract" part of this into a work item for the content engineers. https://ceapex.visualstudio.com/Engineering/_workitems/edit/344651. And we're tracking the "sealed" issue in https://ceapex.visualstudio.com/Engineering/_workitems/edit/285648. I'll go ahead and close this issue, since we'll use that work item for tracking. Please feel free to make any necessary edits to those work items.

-Steve
