### ISSUE TITLE
Please mention/reference AsAsyncOperation and AsAsyncAction extension methods on the IAsyncOperation<TResult> page

### ISSUE THREAD

**Issue by ZodmanPerth** [MicrosoftDocs/winrt-api#1905]
When writing unit tests for my UWP app became necessary to NSubstitute UWP methods that return IAsyncOperation<>, but it isn't possible to do so.  After days of toil I discovered [AsAsyncOperation](https://docs.microsoft.com/en-us/dotnet/api/system.windowsruntimesystemextensions.asasyncoperation) with which I could create mock objects that implement UWP interfaces and return IAsyncOperation<>.

The existence of [AsAsyncOperation](https://docs.microsoft.com/en-us/dotnet/api/system.windowsruntimesystemextensions.asasyncoperation) and [AsAsyncAction](https://docs.microsoft.com/en-us/dotnet/api/system.windowsruntimesystemextensions.asasyncaction?view=dotnet-plat-ext-3.1) extension methods needs to be more widely discoverable in the online documentation.  Having them mentioned and/or referenced from this page would be a great start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8185deb3-7051-d16f-df31-e71f2476e17f
* Version Independent ID: c99958b5-712d-a4ee-9d1d-f3978a4ce9a3
* Content: [IAsyncOperation&lt;TResult&gt; Interface (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation-1?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Foundation/IAsyncOperation`1.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation/IAsyncOperation`1.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created a PR to incorporate your suggestions. The changes have been merged and should appear on the live site soon, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
