### ISSUE TITLE
Link to "Properties" tab for ResolutionScale enum links to incorrect page 

### ISSUE THREAD

**Issue by AriKrumbein** [MicrosoftDocs/winrt-api#1910]
On the page for [DisplayInformation::ResolutionScale](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.resolutionscale?view=winrt-19041#Windows_Graphics_Display_DisplayInformation_ResolutionScale), if you click the Button to go to Properties on the DisplayInformation class, 
![image](https://user-images.githubusercontent.com/11276745/102406682-cc028800-3f9f-11eb-9342-5f562363f73a.png)
it leads to [the wrong page] (https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.autorotationpreferences?view=winrt-19041). It should direct [here](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation?view=winrt-19041#properties) instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd4a6b76-b5ac-d343-f20b-1841380fbc99
* Version Independent ID: 59b6019f-3cf0-6fb7-fc46-f714bb877a6c
* Content: [DisplayInformation.ResolutionScale Property (Windows.Graphics.Display) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.resolutionscale?view=winrt-19041#Windows_Graphics_Display_DisplayInformation_ResolutionScale)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Display/DisplayInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Display/DisplayInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @ackrumb, and thanks for filing this issue. It seems like the system is mistaking the first item under each API kind (methods, properties, events, etc.) as the landing page for that API kind.

As well as your repro, there's additional evidence for that because if you select that first item, then the second-last breadcrumb is plain text and not a hyperlink.

Since this isn't something writers can control, I'll track this as a bug with our content engineers. And since we're tracking it internally, and don't want to double-track it, I'll go ahead and close this issue. Leave it with me and I'll keep an eye on the issue. I've recorded this GitHub issue's ID in the bug so that there's a trail back here so that we'll be able to update this GitHub Issue with the outcome.

Thanks again!
Steve

**Comment by AriKrumbein** [comment]
Hey Steve,
thanks for that. I must've accidentally done this on my personal Github
instead of my corporate account. Would you mind sending the ADO bug to my
alias, arkrumbe@microsoft.com?

Thanks!

**Comment by stevewhims** [comment]
Hi, @ackrumb! Yes--sent via email. :)

-Steve
