### ISSUE TITLE
IAsyncAction does not "inherit" from IAsyncInfo

### ISSUE THREAD

**Issue by billti** [MicrosoftDocs/winrt-api#1911]
This page, and types similar to it, all state the below:

```
IAsyncAction inherits IAsyncInfo. Types that implement IAsyncAction also implement the interface members of IAsyncInfo:

  Cancel method
  Close method
  ErrorCode property
  Id property
  Status property
```

However this isn't true. If you look in the MIDL you can see that IAsyncAction just inherits from IInspectable, but __requires__ that runtime classes _also_ implement IAsyncInfo.

```
        [contract(Windows.Foundation.FoundationContract, 1.0)]
        [uuid(5A648006-843A-4DA9-865B-9D26E5DFAD7B)]
        interface IAsyncAction : IInspectable
            requires
                IAsyncInfo
        {
            [propput] HRESULT Completed([in] Windows.Foundation.AsyncActionCompletedHandler* handler);
            [propget] HRESULT Completed([out] [retval] Windows.Foundation.AsyncActionCompletedHandler** handler);
            HRESULT GetResults();
        }
```

I hit exactly the same issue as the user at <https://stackoverflow.com/questions/40201439/how-to-cancel-asynchronous-callback-function-in-c-wrl>, namely when using WRL (which I'm using as my projects can't use language extensions or exceptions, which rules out C++/CX or C++/WinRT), the sample code shown doesn't work, as you can't directly access IAsyncInfo members such as Status on the IAsyncAction interface, you need to do something like:

```
auto workItem = Callback<Implements<RuntimeClassFlags<Delegate>, IWorkItemHandler, FtmBase>>(
	[](IAsyncAction* asyncAction) -> HRESULT {
		ComPtr<IAsyncInfo> asyncInfo;
		CheckHR(asyncAction->QueryInterface(asyncInfo.GetAddressOf()));

		AsyncStatus status;
		CheckHR(asyncInfo->get_Status(&status));
		// etc..
```

It would have save me (and others like the StackOverflow poster) time and frustration if these docs were correct here. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488677fc-ecca-cd81-4913-d3a8865dab9d
* Version Independent ID: e84e1eb8-09b4-b5d9-46b3-5fe695759827
* Content: [IAsyncAction Interface (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IAsyncAction?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Foundation/IAsyncAction.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation/IAsyncAction.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by reflectronic** [comment]
While it's true that all Windows Runtime interfaces all inherit directly from `IInspectable`, the idea is that required interfaces are transformed into an inheritance hierarchy by language projections; you can access all members of `IAsyncInfo` on an `IAsyncAction` instance from C# or C++/WinRT. Because the Windows Runtime supports multiple interface inheritance (of course, COM does not), they had to implement it this way at the ABI layer.

I think it is just the expectation that people using WRL should understand how the Windows Runtime's classy type system is translated to COM interfaces. Terminology like "required interfaces" is unknown and unhelpful to almost all developers using WinRT APIs.

**Comment by billti** [comment]
While I think it is reasonable to expect a certain level of knowledge, the docs are flat out wrong. At best, this is confusing. At worst, it is misleading. They state:

> IAsyncAction inherits IAsyncInfo. Types that implement IAsyncAction also implement the interface members of IAsyncInfo

IAsyncAction __does not__ inherit IAsyncInfo. Interfaces are also types, so the second part is also wrong. (If the first sentence was true, then the second one would be also). i.e. the type `ComPtr<IAsyncAction>` does __NOT__ implement the interface members of `IAsyncInfo`.

Something like `Runtime objects that implement IAsyncAction also implement IAsyncInfo` would be correct and useful, without being wrong or misleading, in my opinion.

**Comment by jaigak** [comment]
All Windows Runtime interfaces inherit from Windows.Foundation.IInspectable however IAsyncAction requires the class to implement IAsyncInfo so you safely QueryInterface and always expect to get an IAsyncInfo pointer for that class. Also all language projections that I'm aware of automatically allow you call IAsyncInfo methods if you have an IAsyncAction so the documentation shows it as an inheritance relationship which is correct if you use language projections. Since you're using the ABI layer directly, it isn't an inheritance relationship

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates to the docs have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with the product dev team, find the best answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. I have captured the original issue text as well as all of the discussion on this issue. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
