### ISSUE TITLE
Function "RawGameController.GetCurrentReading" throws "ArgumentException" on .NET 5.0 desktop application.

### ISSUE THREAD

**Issue by W11cE** [MicrosoftDocs/winrt-api#1914]
### Problem:
Function "RawGameController.GetCurrentReading" throws this exception, when used on .NET 5.0 desktop application.
**_System.ArgumentException: 'Object contains non-primitive or non-blittable data. Arg_ParamName_Name'_**

### Minimalistic Code Sample:
Create a new .NET WPF application and change the project file to:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
```
Edit "MainWindow" class like this:
```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            RawGameController.RawGameControllerAdded += RawGameController_RawGameControllerAdded;
        }

        private void RawGameController_RawGameControllerAdded(object sender, RawGameController e)
        {
            bool[] buttons = new bool[e.ButtonCount];
            GameControllerSwitchPosition[] switches = new GameControllerSwitchPosition[e.SwitchCount];
            double[] axes = new double[e.AxisCount];

            e.GetCurrentReading(buttons, switches, axes); // Throws here
        }
    }
```
After a controller is connected to the pc, this line will throw the exception:
_e.GetCurrentReading(buttons, switches, axes);_

This should work on desktop applications, right? Could it be that the bool array marshaling is not handled inside the function correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010c28ba-ca95-3878-b3b7-8a31aed9ca21
* Version Independent ID: 07d4cab6-e3e3-a86a-0e14-f33d967a75e6
* Content: [RawGameController.GetCurrentReading(Boolean\[\], GameControllerSwitchPosition\[\], Double\[\]) Method (Windows.Gaming.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.rawgamecontroller.getcurrentreading?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input/RawGameController.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input/RawGameController.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @W11cE  - This feedback is not specifically about the documentation, but rather a support request. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.

Here is a list of other developer support resources that might be able to help with your issue:

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
