### ISSUE TITLE
When is this event called?

### ISSUE THREAD

**Issue by adras** [MicrosoftDocs/winrt-api#1916]
The MaxPduSize property has only a get accessor, therefore it can't be set. Therefore the question is, how this event is triggered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a5e08f-82da-01a1-0c98-b4803aab11b9
* Version Independent ID: b89c68a9-b758-d107-8872-dc44dd7123da
* Content: [GattSession.MaxPduSizeChanged Event (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsession.maxpdusizechanged?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattSession.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattSession.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @adras, and thanks for filing this issue. I've added the following info to the topic:

**MaxPduSizeChanged** is raised whenever the negotiated MTU for the Attribute Protocol (ATT) is changed. And that can be changed or negotiated by a remote Bluetooth peripheral. As a developer, you can't change the value used by Windows itself, since that's fully managed by the operating system.

That update is now live, so I'll close this issue.

Thanks!
-Steve
