### ISSUE TITLE
Add 'Wireless frequency band'-Option to WiFi-Direct Legacy Settings

### ISSUE THREAD

**Issue by Lgum** [MicrosoftDocs/winrt-api#1919]
Build 19041 added the possibility to specify the wifi frequency band in the 'NetworkOperatorTetheringAccessPointConfiguration' class. Is it possible to enable this in the wifi direct legacy settings as well? Most legacy devices work only in the 2.4 ghz range and changing the frequency band in the device manager is cumbersome.

**Comment by stevewhims** [comment]
Hi, @Lgum, and thanks for filing this issue.

This feels like a feature request about the product (the APIs, in this case), rather than feedback that's specifically about the *documentation* for a given API. I've included some links below that might be appropriate for you.

Incidentally, for specific feedback about the documentation in a particular topic, you can visit that topic, and click **Send feedback about** \> **This page**. For example, if you believe that the documentation in that topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions/support/suggestions regarding the product itself (how APIs or the operating system function, for example) then one option is to visit a documentation topic and click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve
