### ISSUE TITLE
Cannot add assembly reference because assembly name is not documented

### ISSUE THREAD

**Issue by Niko-O** [MicrosoftDocs/winrt-api#1923]
**What I expect:**
In my current project, the `System.Numerics.BigInteger` class is not found. I want to use it, so I have to add a reference to the assembly it resides in. I type "System.Numerics.BigInteger" into Google and open the docs.microsoft.com page for that class: https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger?view=net-5.0
I select the "Version" that matches my project, which is ".NET Framework 4.0": https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger?view=netframework-4.0
At the top it says "Assembly: System.Numerics.dll"
In my project settings in Visual Studio I add a reference to System.Numerics.dll and now I can use the System.Numerics.BigInteger class.

**What actually happens:**
In my current project, the `Windows.Devices.Bluetooth.BluetoothDevice` class is not found. I want to use it, so I have to add a reference to the assembly it resides in. I type "Windows.Devices.Bluetooth.BluetoothDevice" into Google and open the docs.microsoft.com page for that class: https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothdevice?view=winrt-19041
I select the "Version" that matches my project, which is "Windows 10 Build 16299": https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothdevice?view=winrt-16299
**At the top, the line that says "Assembly: <something>.dll" is missing.**
In my project settings in Visual Studio I **cannot add a reference because I don't know which assembly to reference** and I **cannot** use the Windows.Devices.Bluetooth.BluetoothDevice class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06da93f4-8c39-3517-91df-f36e5ec5dcbe
* Version Independent ID: 46915b73-3dde-6eb0-6ae3-80e339149acd
* Content: [BluetoothDevice Class (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothdevice?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Niko-O, and thanks for filing this issue.

If you create a Universal Windows Platform (UWP) project, then (for Windows Runtime types such as Windows.Devices.Bluetooth.BluetoothDevice) you don't need to add assembly references (but see [Programming with extension SDKs](https://docs.microsoft.com/uwp/extension-sdks/device-families-overview)). It's possible that your project isn't a UWP one.

However, this feels like a request for support with your scenario, rather than feedback that's specifically about the documentation in this particular topic.

I've included some links below that might be appropriate for you.

Incidentally, for specific feedback about the documentation in a particular topic, you can visit that topic, and click **Send feedback about** \> **This page**. For example, if you believe that the documentation in that topic is incorrect, or that info needed to succeed with a common scenario is missing (a specific common scenario related to that topic, rather than more broad programming guidance).

For questions/support/suggestions regarding the product itself (how APIs or the operating system or tools function, for example) then one option is to visit a documentation topic and click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve
