### ISSUE TITLE
The cache is not adequately described. 

### ISSUE THREAD

**Issue by tony-gutierrez** [MicrosoftDocs/winrt-api#1928]
What happens if you request a service/char with cache mode, but the requested service/char is not present in the cache? Does it fall back to retrieval from the device? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef1a204-e7f5-2424-d0d5-a3331de022dc
* Version Independent ID: 73aa1eba-bd66-d4fd-ac78-a3ac1d9f00fb
* Content: [BluetoothCacheMode Enum (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothcachemode?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothCacheMode.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothCacheMode.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tony-gutierrez, I've reached out for confirmation. I'll update this thread when I have more info.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'm still seeking clarification about this internally. I'll respond when I have all the info.

Thanks again!
Steve

**Comment by stevewhims** [comment]
UPDATE: The feature team is talking about this internally. I just pinged the thread to get it moving again. Hope to have an answer soon.

Thanks for your patience.

-Steve

**Comment by stevewhims** [comment]
So, I'll go ahead and close this issue for now since we're not yet ready with a response nor with documentation updates. I've asked the feature team to let me know when we're ready for doc updates here, and then I'll be able to come back and make them. You can still respond to the thread while it's closed. Thanks for your patience.

-Steve

**Comment by tony-gutierrez** [comment]
Uhhhh... Seems to me that those are all good reasons for the issue to remain open?

**Comment by stevewhims** [comment]
@tony-gutierrez, I've added more details to the **Fields** section of the topic.

-Steve

**Comment by tony-gutierrez** [comment]
Thanks! I am not sure this jives with the behavior I am seeing, but I'll investigate further. 

@stevewhims If you have any voice in the UWP Bluetooth world, the scanning timings result in very poor scan performance compared to other platforms. You can get the jist of it here: https://docs.microsoft.com/en-us/answers/questions/39802/windows-ble-scanning-interval-issue.html

Would love to see the ability to change the timings in a future api.

**Comment by stevewhims** [comment]
Thanks, @tony-gutierrez!

It looks like the issue you link to there is in the right place. [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question. From that thread, I see that the question/issue has made its way to Microsoft engineers, so the channel is working.

Btw, you can visit a topic in the documentation and for questions (or requests for help) regarding a specific scenario related to that topic, you can click **Send feedback about** \> **This product**, and you'll be taken to Microsoft Q&A.

Threads such as this one (created through **Send feedback about** \> **This page**, instead of **This product**) are for feedback about the documentation in the topic. For example, if the documentation in the topic is incorrect, or if info needed to succeed with a common scenario is missing.

Thanks again!
Steve
