### ISSUE TITLE
Nothing about C++/WinRT

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/winrt-api#1931]
Remarks on this page specify how Close() should be handled with respect to C++/CX, but do not detail whether the same comments apply to C++/WinRT.

It might also be worthwhile to distinguish between what Close() means with regard to object lifetime versus what close means in the sense of an AppServiceConnection that is not opened, or has been closed by the other side. If a connection is closed by a UWP background service, for instance, can the AppServiceConnection later be re-opened for use, or does it need to be disposed and re-created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e96d2625-7ac1-292a-c930-86f8aff3de0b
* Version Independent ID: 8b6678dc-3b22-1489-4888-5f0c2c49af91
* Content: [AppServiceConnection.Close Method (Windows.ApplicationModel.AppService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appservice.appserviceconnection.close?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.AppService/AppServiceConnection.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.AppService/AppServiceConnection.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by stevewhims** [comment]
Hi, @druske. I'm investigating whether this Close really is an implementation of IClosable::Close. If it is, then this applies: [Do I need to call IClosable::Close on runtime classes that I consume?](https://docs.microsoft.com//windows/uwp/cpp-and-winrt-apis/faq#do-i-need-to-call-iclosableclose-on-runtime-classes-that-i-consume). But then if it is, I'm not sure why it isn't documented just like Dispose is. So I'm looking into it.

-Steve

**Comment by stevewhims** [comment]
Hi, @druske. I have an update to the topic in the pipeline. That should be live in the next 24 hours.

Meanwhile, FYI, here's the info that I added to the topic.

**C++/WinRT** : You don't *need* to call **Close** from C++/WinRT because the object will be closed and destructed naturally when all references are released. But you might choose to call **Close** if you want to stop the app service regardless of outstanding references to the app service connection. After calling **Close** in a situation like that, we recommend that you consider the object to be invalid, and not to use it further. Specifically, consider that the **AppServiceConnection** object isn't reusable nor re-openable after **Close** is called. Also see [Do I need to call IClosable::Close on runtime classes that I consume?](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/faq#do-i-need-to-call-iclosableclose-on-runtime-classes-that-i-consume).

Thanks!
Steve
