### ISSUE TITLE
FileOpenPickerContinuationEventArgs obsolete?

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/winrt-api#1938]
19041 with min of 18362 is warning this as obsolete...

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'FileOpenPickerContinuationEventArgs' is obsolete: 'FileOpenPickerContinuationEventArgs is deprecated and might not work on all platforms. For more info, see MSDN.'	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1397fc62-abca-a051-f814-d233874168ea
* Version Independent ID: 8337bab4-8747-2c6d-3831-c8bef16f3b17
* Content: [FileOpenPickerContinuationEventArgs Class (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Activation.FileOpenPickerContinuationEventArgs?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Activation/FileOpenPickerContinuationEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Activation/FileOpenPickerContinuationEventArgs.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Hi @kcovert. Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks and resolve this doc bug. These file/folder continuation APIs are no longer relevant with the discontinuation of Windows Phone (they were deprecated in v19041). I will add a note to this content and other related pages today. The changes should be live sometime this week. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
