### ISSUE TITLE
Help with StorageFile class or struct?

### ISSUE THREAD

**Issue by MattSA-01** [MicrosoftDocs/winrt-api#1979]
I am working on the project: https://docs.microsoft.com/en-us/windows/win32/direct2d/save-direct2d-content-to-an-image-file.
It makes use of the StorgaeFile type in C++CX with a handle operator:

task<StorageFile^> fileTask(savePicker->PickSaveFileAsync());

I am working in C++/WinRT, so I cannot use the hat operator. I would like to create an instance of the StorageFile type, then a pointer to it. Something like:

StorageFile file = StorageFile();
StorageFile* filep = &file;

Intellisense says that StorageFile object is a structure, while documentation says its a class. Trying to use a parameterless constructor will not work. Any help appreciated.

MattSA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4cb107-8295-b904-c1ca-728848351fe0
* Version Independent ID: 0e8b60c5-e4ae-a743-b5aa-f97b22fb78e0
* Content: [StorageFile Class (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageFile?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by jaigak** [comment]
In C++/WinRT, the projected type itself is a smart pointer to the object rather than the object itself but it pretends to be the actual object since it provides all the same methods as in a StorageFile object so no need to use the arrow operator (eg: StorageFile is the C++/WinRT equivalent to StorageFile^ or `Microsoft::WRL::ComPtr<StorageFile>`. All of these smart pointer types are structures and not classes so I believe it's a mistake with the documentation. Also you can't create a StorageFile because the constructor is deleted, you can only use a StorageFile you already have.
