### ISSUE TITLE
[C++/WinRT] Async methods don't take parameters by const&

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#1981]
[C++/WinRT] Async methods don't take parameters by const&
---
The documentation shows async methods in C++/WinRT takes parameters by const& but in C++/WinRT async methods take the parameter by value and never by const&.
#### Document Details
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb48ceb-7901-50d7-1748-1b97e543a5dd
* Version Independent ID: f599ae92-4fd9-2c8a-712a-9ed0594b0aa3
* Content: [CoreApplication.RequestRestartForUserAsync(User, String) Method (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplication.requestrestartforuserasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Core/CoreApplication.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Core/CoreApplication.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by stevewhims** [comment]
Hi, @Jaiganeshkumaran, and thanks for filing this issue. This is an interesting point, and it occurred to me, too. I got some info from the C++/WinRT team.

Coroutines must take parameters by value. Everything else is a regular function that should accept params by reference.

But the indications of a function being a coroutine are the presence of a co_await, co_return, or co_yield statement. Not whether the function's name has "Async" in it, and/or it whether it returns IAsyncAction or IAsyncOperation.

"Async" methods in the C++/WinRT language projection such as **CoreApplication::RequestRestartForUserAsync** are actually *not* coroutines, they're just regular functions.

The C++/WinRT language projection's "Async" methods all take params by reference – we don't need to prematurely pessimize them by incurring an extra copy, because the projection method isn't the one doing the work. It might not even be the top-level function on the other side of the API inside Windows that does the work. There could be several layers of indirection before the "async"-ness kicks in; only then does the code need to ensure that it has a local copy of whatever data it's going to stash away for later.

So, the topic for **CoreApplication::RequestRestartForUserAsync** *does* correctly document the parameters. The projection does indeed take those parameters by reference.

Thanks!
Steve
