### ISSUE TITLE
The fields for the HandJointKind enum are ordered alphabetically as opposed to being sorted by their indices. 

### ISSUE THREAD

**Issue by mukapasi-ms** [MicrosoftDocs/winrt-api#1982]
The fields for the HandJointKind enum are ordered alphabetically as opposed to being sorted by their indices. This makes it a bit tricky to navigate the list. Recommend using indices to sort the fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756066c5-79dd-a0d4-6589-c2a87783657f
* Version Independent ID: 82de2d4a-95a3-a9ce-d9eb-65e7147e3262
* Content: [HandJointKind Enum (Windows.Perception.People) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.perception.people.handjointkind?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Perception.People/HandJointKind.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Perception.People/HandJointKind.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for the feedback. I appreciate your argument, but I'm inclined to leave it as-is because I suspect people will most likely use the table with the enum name than the index. For example, I think it's more likely that someone will want to find out what index corresponds to `HandJointKind.Palm` than that they'll want to find out what name corresponds to `HandJointKind[0]`.

Please reopen if I'm missing an important workflow that would create a lot of lookups by index.
