### ISSUE TITLE
Missing a key bit of information about IVectorView

### ISSUE THREAD

**Issue by debun8** [MicrosoftDocs/winrt-api#2003]
Looks like a key missing detail  in this sentence:

"In any case where a Windows Runtime type has implemented IVectorView<T>, .NET code can use the APIs of instead. "

The APIs of what, exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4b26bf-7e6b-70a6-77da-a2e8433d9f63
* Version Independent ID: 82631c7b-0f3f-f634-5df4-e37abde81d01
* Content: [IVectorView&lt;T&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivectorview-1?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IVectorView`1.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IVectorView`1.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
