### ISSUE TITLE
Multiple duplicated links in See Also section

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/winrt-api#2012]
![image](https://user-images.githubusercontent.com/5264795/120940786-e62f4e80-c716-11eb-8f1c-50892982f6b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3577a437-ec13-a2fa-10b5-aa3aeca5c78a
* Version Independent ID: 54ede13c-e6f5-42b9-0d89-c76a02de3088
* Content: [ApplicationExecutionState Enum (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.applicationexecutionstate?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.ApplicationModel.Activation.ApplicationExecutionState);k(TargetFrameworkMoniker-.NETCore,Version%253Dv5.0);k(DevLang-csharp)%26rd%3Dtrue&view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Activation/ApplicationExecutionState.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Activation/ApplicationExecutionState.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to investigate your suggestions. I started looking into the issue, and it looks like the publishing system is removing the class names that should be rendering for each of those PreviousExecutionState properties in the See Also section. If you hover over each one (or click them), you can see they're not duplicates. They're pointing to different properties with the same name. I'm going to see why the name specified in our markdown is being overridden to remove the class name.

The timeline for this may vary. I will circle back when the changes are live. Many thanks!

**Comment by alvinashcraft** [comment]
That turned out to be simpler than I thought. I was able to make changes today and merge them. They should appear on the live site soon. Each of the links will now include the class name so they don't appear as duplicates. Thanks again for submitting this issue!
