### ISSUE TITLE
What is the "Identity" string and how is it used?

### ISSUE THREAD

**Issue by TheJoeFin** [MicrosoftDocs/winrt-api#2014]
I'm trying to better understand how to use the appointment change tracker in Windows 10 and I'm having trouble getting my app to work reliably. This docs page uses a string to get the Change Tracker, but what is this string and how is it used to get the Change Tracker?

Does it represent an appointment ID? Should the Change Tracker be generated every time there is an appointment change? 

The Appointment Sample app does not interact with this API. It would be nice to see a sample app which tracks changes well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fbe4607-3387-96f8-cc5f-98c19be15a60
* Version Independent ID: 14cf0615-b9b1-4033-65ef-191ee4788053
* Content: [AppointmentStore.GetChangeTracker(String) Method (Windows.ApplicationModel.Appointments) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appointments.appointmentstore.getchangetracker?view=winrt-20348#Windows_ApplicationModel_Appointments_AppointmentStore_GetChangeTracker_System_String_)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Appointments/AppointmentStore.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Appointments/AppointmentStore.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to enhance the docs for this method a bit. The change tracker and the "Identity" do not correspond to a particular appointment. It's a way of identifying a change tracking mechanism within your app. You may be tracking appointment changes to update something in your UI, or maybe you have another tracker for sending notifications or kicking off another process. I'm going to add a short example to the docs as well. That example uses a "DashboardUpdater" string as the Identity parameter because any appointment changes detected by this tracker will update the app's dashboard. These changes should be live today or tomorrow. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!

**Comment by TheJoeFin** [comment]
I am interested in a working code sample using this Change Tracker. My attempts to use it found strange behavior. Which is why I opened this issue originally. Here is a repro repo I made a year ago to showcase some of the odd behavior around the AppointmentManager API in Windows.

https://github.com/TheJoeFin/AppointmentStoreReproBug

**Comment by alvinashcraft** [comment]
Hi @TheJoeFin. Thanks again for taking the time to let us know about this and for creating a repro project. It would be great to take this to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding winrt-api and UWP.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. If there's anything that comes out of that discussion that we can use to create another PR to improve the docs for this topic, I would be happy to help with that. Thanks!

**Comment by TheJoeFin** [comment]
@alvinashcraft I did make a thread on the Microsoft Q&A site in May 2021, but the thread went stale. The original response from the engineer there is what led me to make the repro project. Here is the thread for reference:
https://learn.microsoft.com/en-us/answers/questions/389647/best-practice-for-using-appointmentstorestorechang.html?childToView=390354#comment-390354

Do you recommend I start a new thread over at Q&A or will the original suffice?

**Comment by alvinashcraft** [comment]
@TheJoeFin - Leave the current Q&A item active for now. I sent an email to some folks on the product team with links to this issue and your question in Q&A. If it doesn't get any response soon, a new Q&A question might get someone's attention. I'd wait several days due to the U.S. holiday this week though.

**Comment by TheJoeFin** [comment]
@alvinashcraft hello again, checking in to see if you were able to connect with anyone on the product team about this issue.

**Comment by alvinashcraft** [comment]
Hi @TheJoeFin. The email chain got passed from team to team a couple of weeks ago. The APIs for Appointments are no longer in active development, and the maintenance of them is in transition between teams at the moment. What they've been able to tell me is that the identity param for this method is there so the consuming app can define multiple trackers, if necessary. If it's not provided, an internal default value is used as the fallback. I believe that default value is derived from the app package family name (PFN). It allows the API to identify which app is tracking appointment changes.

**Comment by TheJoeFin** [comment]
Hello @alvinashcraft I appreciate the follow up, but I still have a concern that there are issues with the Appointment Manager. Would it be possible for the team to provide some samples or demo code to show how it is expected to work?

I get emailed regularly from users who are not able to refresh their appointment data and I don't know what else I can do since I have no control over the Appointment Manager API.

**Comment by alvinashcraft** [comment]
Hi @TheJoeFin. Did you have any luck in the Q&A forums since your last reply? That's usually the best place to engage the engineering team and other experts. I can send another follow up to the team here. They'll probably respond sometime after the new year's holiday. Most of the teams are out this week.

**Comment by TheJoeFin** [comment]
No luck on the Q&A forum unfortunately.

**Comment by alvinashcraft** [comment]
Ok. I sent another follow up email to the chain I had going here. I pointed to your repro project on [GitHub](https://github.com/TheJoeFin/AppointmentStoreReproBug) and asked if they had any changes that they could recommend to address the issues you're having. I got a bunch of OOO responses, but I'll follow up with them again after the holidays.

**Comment by TheJoeFin** [comment]
@alvinashcraft is it safe to assume this will not be addressed and I should stop waiting the Windows Calendar API to get fixed? 

I would like to know if I should continue to invest in my calendar app or abandon it and tell my customers their issues will never be resolved.

**Comment by alvinashcraft** [comment]
Hi @TheJoeFin. My last email to the engineers never got any replies. I've just asked again if they could look at your sample app in GitHub and offer any suggestions in the Q&A thread.

I can't say from the Docs side when a possible issue in the API would get addressed. The team would have to answer that in the Q&A forums.
