### ISSUE TITLE
Example with errors

### ISSUE THREAD

**Issue by dmitriy-proskurin** [MicrosoftDocs/winrt-api#2022]
Wrong class/event names. Did you mean CoreDragDropManager and TargetRequested?
Could you provide example how to pass Drag & Drop handling to existed control? I want to use this like global filter(only storage files) and if all ok, delegate handling to specified control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd7b484-8ea4-49d5-1dd1-88e8a68badfa
* Version Independent ID: f217ad9e-ae5d-ad3a-b814-1906bf18341b
* Content: [CoreDragDropManager Class (Windows.ApplicationModel.DataTransfer.DragDrop.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.dragdrop.core.coredragdropmanager?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer.DragDrop.Core/CoreDragDropManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer.DragDrop.Core/CoreDragDropManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
