### ISSUE TITLE
Please use a friendlier GUID format for COM GUID identifier

### ISSUE THREAD

**Issue by mqudsi** [MicrosoftDocs/winrt-api#2031]
The GUID format at the top of the page for WinRT COM interfaces is in an extremely non-standard comma-delimited big integer format, rather than the typical hexadecimal GUID format that Microsoft/COM uses everywhere else.

For example:

```
[Windows.Foundation.Metadata.Guid(4224269862, 41290, 19279, 130, 176, 51, 190, 217, 32, 175, 82)]
```

This is ungoogleable and not even greppable given the code base.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9061f282-f1c0-9b73-660a-48a79b237abc
* Version Independent ID: 062bf2c8-baaf-a5f6-517f-2a1e6b2f06c1
* Content: [ILaunchActivatedEventArgs Interface (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.ilaunchactivatedeventargs?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Activation/ILaunchActivatedEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Activation/ILaunchActivatedEventArgs.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks to discuss this docs concern. The part of the document you're concerned about is not human-authored. It is generated by the publishing system. We will see if the system can be improved to change the GUID display. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
