### ISSUE TITLE
Deferral documentation doesn't state whether it must manually be completed if it is disposed

### ISSUE THREAD

**Issue by mqudsi** [MicrosoftDocs/winrt-api#2035]
The documentation on deferrals doesn't state whether this is sufficient:

```csharp
SomeAction += async (s, e) => {
    using var deferral = e.GetDeferral();
    var bar = await foo();
    e.Result = bar;
    // deferral.Complete();
};
```

or if the `deferral.Complete()` line must be commented back in.

i.e. does disposing a deferral also complete it if it hasn't yet been completed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2528635b-e3a1-3e11-8be6-206b2acb1977
* Version Independent ID: b053cbd2-296d-baf4-d036-eec548b79810
* Content: [Deferral Class (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.deferral?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Foundation/Deferral.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation/Deferral.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by MikeHillberg** [comment]
Yes, specifically the Deferral completes automatically in its destructor, same as calling Close/Dispose. But note that in C# the Deferral's destruction won't happen until GC has collected it some random time in the future.

**Comment by mqudsi** [comment]
Thanks, @MikeHillberg. Note that in my sample above, the deferral is in a `using` block/statement so it will be disposed immediately at the end of the scope; so if I understand you correctly, there shouldn't be anything waiting on the actual destructor/finalizer.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
