### ISSUE TITLE
DataPackage `SetData` method should have an example

### ISSUE THREAD

**Issue by hawkerm** [MicrosoftDocs/winrt-api#2036]
The only hint about how to use this method and what to pass in as the second `object` parameter is "RandomAccessStream" which links to a whole article about writing/reading text from files.

It'd be great to have a complete example for how to use the `SetData` method to binary serialize an instance of a C# object to the proper stream format to pass to this method (and how to deserialize it back to the same type again from [`GetData`](https://docs.microsoft.com/uwp/api/windows.applicationmodel.datatransfer.datapackageview.getdataasync)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd0e6e0-c1fc-6f5d-9552-1d11dbff8320
* Version Independent ID: 4aba3b11-3c28-e6a5-865a-5daea64c590c
* Content: [DataPackage.SetData(String, Object) Method (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackage.setdata?view=winrt-20348#Windows_ApplicationModel_DataTransfer_DataPackage_SetData_System_String_System_Object_)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/DataPackage.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/DataPackage.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to work on an example and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
