### ISSUE TITLE
Documentation is incorrect for Certificate.Issuer

### ISSUE THREAD

**Issue by andy-schmidt** [MicrosoftDocs/winrt-api#2043]
The documentation states that Certificate.Issuer
`Gets the name of the certificate issuer.`
This is incorrect. Certificate.Issuer only returns the Common Name (CN) of the certificate issuer and not the full X509 Issuer Distinguished Name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808a8db4-e570-3c65-af3f-0af71c435885
* Version Independent ID: 4105d558-2347-5e2f-fd59-6a733ed17e77
* Content: [Certificate.Issuer Property (Windows.Security.Cryptography.Certificates) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.certificates.certificate.issuer?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography.Certificates/Certificate.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography.Certificates/Certificate.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and completed an internal work item to incorporate your suggestion. The changes should go live shortly. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
