### ISSUE TITLE
Bad formatting for IKeyValuePair page

### ISSUE THREAD

**Issue by j0shuams** [MicrosoftDocs/winrt-api#2052]
This section looks jumbled and doesn't read

![image](https://user-images.githubusercontent.com/70237359/128429409-d543d71a-019c-4934-9119-3f5d7a65cd73.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 125fad61-1bf8-dbc8-60cf-dde5eef30711
* Version Independent ID: cf963483-c0cd-7a0a-93b0-7bae3e7e84ae
* Content: [IKeyValuePair&lt;K,V&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ikeyvaluepair-2?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IKeyValuePair`2.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IKeyValuePair`2.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to incorporate your suggestions. The changes have been merged and should be live shortly.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
