### ISSUE TITLE
would be great to have a pointer to a list of common strings for GetPropertyAsync/SetPropertyAsync

### ISSUE THREAD

**Issue by darax** [MicrosoftDocs/winrt-api#2059]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f963f4ce-3ab5-372f-3126-84e4d96acf26
* Version Independent ID: b82244b1-5c5b-1b13-8adf-7871e4510ce8
* Content: [MediaFrameSourceController.GetPropertyAsync(String) Method (Windows.Media.Capture.Frames) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframesourcecontroller.getpropertyasync?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Media.Capture.Frames/MediaFrameSourceController.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Capture.Frames/MediaFrameSourceController.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@darax I consulted with the PMs for this API and their take on this is that "common" properties are given dedicated properties off of the VideoDeviceController object. So, for example the recently introduced [DigitalWindowControl](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.videodevicecontroller.digitalwindowcontrol?view=winrt-insider) was given a dedicated property, while the [EyeGazeCorrection](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/ksproperty-cameracontrol-extended-eyegazecorrection) was only exposed as a KSPROPERTY value. 

But in order to make all of this more clear, I've added the following remark to the docs for the get and set property APIs, that calls out where the properties are defined and links to a code sample illustrating usage:

Common device properties are exposed as properties of the [VideoDeviceController](videodevicecontroller.md) class. Additional properties are defined in the [KSPROPERTYSETID_ExtendedCameraControl](windows-hardware/drivers/stream/kspropertysetid-extendedcameracontrol) property set. Legacy properties are defined in the [PROPSETID_VIDCAP_CAMERACONTROL](/windows-hardware/drivers/stream/propsetid-vidcap-cameracontrol) property set. For an example of accessing camera properties by ID, see the [Extended Control and Metadata sample](https://github.com/microsoft/Windows-Camera/tree/master/Samples/ExtendedControlAndMetadata/EyeGazeAndBackgroundSegmentation).
