### ISSUE TITLE
Emoji doesn't display correctly

### ISSUE THREAD

**Issue by yume-chan** [MicrosoftDocs/winrt-api#2105]
See screenshot:

![image](https://user-images.githubusercontent.com/1330321/140450655-69337f44-91a2-4bab-8d11-47179a8925df.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee5f189-17ff-c631-6620-cffc26f1a4ad
* Version Independent ID: e6bd888d-43d3-43b5-f67e-8f1d4fe26d5a
* Content: [DesignMode.DesignMode2Enabled Property (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.designmode.designmode2enabled?view=winrt-22000#feedback)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/DesignMode.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/DesignMode.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to resolve this doc bug. The changes have been merged and should appear on the live docs site soon.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
