### ISSUE TITLE
C++/WinRT - Wrong signature for IMapView::Split

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#2106]
The docs says the the signature of IMapView::Split is `void Split(IMapView<K, V> const& & first, IMapView<K, V> const& & second);` while the actual signature is `void Split(IMapView<K, V>& first, IMapView<K, V>& second);`. Out parameters in C++/WinRT are passed with a non-const reference and not a const reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86149f39-6611-d4c1-6c3d-a3d2b8741b43
* Version Independent ID: 6941bc47-b952-0d44-7108-43d1e50ddfff
* Content: [IMapView&lt;K,V&gt;.Split(IMapView&lt;K,V&gt;, IMapView&lt;K,V&gt;) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.imapview-2.split?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IMapView`2.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IMapView`2.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
