### ISSUE TITLE
GetProxyConfigurationAsync uri required?

### ISSUE THREAD

**Issue by ShaneOss** [MicrosoftDocs/winrt-api#2109]
I was wondering why a uri was required to get the proxy configuration? 
At present I have a proxy specified in the Windows settings but not enabled. When trying to get the proxy configuration, it just hangs. I'm guessing because it's trying to get the uri via proxy which isn't enabled. With the proxy enabled it works fine.

`            Uri uri = new Uri("http://www.microsoft.com");
            ProxyConfiguration pc = await NetworkInformation.GetProxyConfigurationAsync(uri);`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 986bcbc3-2b78-3e4f-5228-99790b3c50df
* Version Independent ID: b07ef4df-de28-a687-b9c1-5b38f8f5566e
* Content: [NetworkInformation.GetProxyConfigurationAsync(Uri) Method (Windows.Networking.Connectivity) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkinformation.getproxyconfigurationasync?view=winrt-22000#Windows_Networking_Connectivity_NetworkInformation_GetProxyConfigurationAsync_Windows_Foundation_Uri_)
* Content Source: [winrt-api-build/xml/Windows.Networking.Connectivity/NetworkInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Connectivity/NetworkInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @ShaneOss, is this more of a question about why the API is designed the way it is? If so, then that would be feedback about the product (or a question about the product), and here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Or do you feel that there's missing info, or incorrect info, in this topic about how developers should use this API? That would be feedback about the documentation. If so, then could you help me understand what additional info should be in this topic.

Many thanks!
Steve
