### ISSUE TITLE
Incorrect namespace for windows.printSupportSettingsUI extension

### ISSUE THREAD

**Issue by ppoirier1** [MicrosoftDocs/winrt-api#2112]
Hi, 

The document says:
_your app must declare a uap4:Extension element with the category windows.printSupportSettingsUI_ 
But that's defined in uap12, not uap4.  And uap12 isn't defined here or anywhere else: 
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/extensions

Hope this helps!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8361056a-a139-ac98-d022-0cc4b7ac10aa
* Version Independent ID: a2cbca00-6290-c8d2-f50b-c4a84af9b01a
* Content: [PrintSupportSettingsUISession Class (Windows.Graphics.Printing.PrintSupport) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.printing.printsupport.printsupportsettingsuisession?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Printing.PrintSupport/PrintSupportSettingsUISession.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Printing.PrintSupport/PrintSupportSettingsUISession.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by AKundapur** [comment]
As per Print Support design guide, it says that
https://learn.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide

**Comment by hebbarsdocs** [comment]
@Karl-Bridge-Microsoft, @drewbatgit 

I am getting errors and unable to use windows.printSupportSettingsUI extension is required for the Print support settings UI. I tried the below sample code provided by Microsoft's [Print-support-app-design-guide](https://learn.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide) documentation. 

`xmlns:printsupport="http://schemas.microsoft.com/appx/manifest/printsupport/windows10"`

```
<Extensions>
    <printsupport:Extension Category="windows.printSupportSettingsUI" 
        EntryPoint="PsaSample.PsaSettingsUISample"/>
</Extensions>
```

I also tried declaring a `uap4:Extension` element with the category `windows.printSupportSettingsUI` element  in the package manifest

https://learn.microsoft.com/en-us/uwp/api/windows.graphics.printing.printsupport.printsupportsettingsuisession?view=winrt-22621

Could please help me with this and let me know the syntax to use windows.printSupportSettingsUI extension

**Comment by drewbatgit** [comment]
@mopkmdev3 - I reached out to the printer hardware team and have confirmed that the initial namespace and extension syntax you got from the print support app design guide are current and correct. Side note: The printSupportSettingsUI category was previously introduced in uap12 (not uap4), but the printsupport namespace is the correct one to use, and we will be adding a page in the schema reference docs for this extension in the coming days. Unfortunately, since issues in this repo are specifically for addressing issues in the documentation, I can't help you diagnose why your extension with the correct syntax isn't working. The hardware team recommends that developers use one of the following sites to request help with implementations of hardware support apps:

[windows hardware - Microsoft Q&A](https://learn.microsoft.com/en-us/answers/topics/windows-hardware.html)
[OSR Developer Community](https://community.osr.com/)
