### ISSUE TITLE
Clipboard Changed code missing for C#

### ISSUE THREAD

**Issue by TheJoeFin** [MicrosoftDocs/winrt-api#2115]
For some reason the sample code is only given in JavaScript with no C# examples. Also the API is not explained in a way which can be used in a C# Windows app. What kind of delegate signature does the Clipboard changed event require? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100fb5ed-12d9-c09f-1820-02521ec76f8b
* Version Independent ID: 57d08ba1-0df1-1345-8009-641f40f9713a
* Content: [Clipboard Class (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to resolve this doc bug. The change to swap out the JavaScript snippet for a C# snippet has been merged and should be visible on the live site soon. I'm going to look at some of the related Clipboard content pages to see if other JS snippets can be swapped out in the days ahead.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
