### ISSUE TITLE
Link jumps from winrt to .NET for return type.  Should be  winrt::guid

### ISSUE THREAD

**Issue by marksrasmussen** [MicrosoftDocs/winrt-api#2116]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0bdb5f-ada4-e46d-821e-563c345cdc36
* Version Independent ID: 9483e268-4090-69ad-e6de-333c8c510570
* Content: [GuidHelper.CreateNewGuid Method (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.guidhelper.createnewguid?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Foundation/GuidHelper.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation/GuidHelper.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
Thanks for filing this issue. I'm currently pursuing this issue with our content engineering team (since it's not something that a writer can fix in the actual content). I'll go ahead and track that work internally, and meanwhile I'll close this issue so as not to track it twice. The internal issue I'm tracking has a link to this issue, so once that's resolved I'll be able to come back here and update.

Thanks again!
-Steve

**Comment by stevewhims** [comment]
UPDATE: the issue has been fixed now.
