### ISSUE TITLE
Use C++ namespace notation for namespace names when the docs language is set to C++/CX or C++/WinRT

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#2125]
Today even when the docs language is set to C++/CX or C++/WinRT, the namespace names use the dot notation as in C# and Visual Basic instead of the double colon notation as in C++.

**Comment by stevewhims** [comment]
Hi, @Jaiganeshkumaran, and thanks for filing this issue. This is by design.

There are certain artifacts of the Windows Runtime type system (namespace names and delimiters being one example) that are agnostic of language projection. So for example if you visit the [Uri](https://docs.microsoft.com/uwp/api/windows.foundation.uri) topic, the namespace is displayed in the language-agnostic format "Windows.Foundation" no matter what language you choose from the picker.

You'll see that same, consistent dot notation used in other places in the documentation such as [The Windows Runtime (WinRT) type system](https://docs.microsoft.com/uwp/winrt-cref/winrt-type-system), and in source code examples of MIDL 3.0 itself (see [Introduction to Microsoft Interface Definition Language 3.0](https://docs.microsoft.com/uwp/midl-3/intro)).

However, when you see in-topic code examples presented in C++/WinRT (or C++/CX), then of course the syntax there uses the double colon notation. But that's because those examples are then specific to those language projections, and then of course we use the idioms of that language rather than the language-agnostic style of the Windows Runtime.

Thanks!
Steve

**Comment by jaigak** [comment]
@stevewhims Why not improve the docs to use the correct notation for the specified language on the top of the page? MIDL and WinRT internally use dots for namespace separator doesn't mean the API documentation should also use them. It makes it confusing for developers who just are using the APIs from their preferred language and don't care about the Windows Runtime implementation of it. Maybe also consider having the language option on the main Windows UWP namespaces page so it also uses the correct notation for the language specified.

**Comment by stevewhims** [comment]
Hi, @Jaiganeshkumaran. I've created an internal work item (for the consideration of the content engineering program managers and engineers) capturing your suggestion. Personally, I think that making that change would then be inconsistent with how we think of and represent WinRT namespaces in other places in the docs. Again, to be clear, the namespace name that we show *in WinRT API ref topics* is the WinRT namespace name; AFAIK it's not meant to be the C++ (or C#, or other language) namespace name. Others might differ with me on that, hence I've given the owners a chance to consider the suggestion.

Thanks again!
-Steve

**Comment by jaigak** [comment]
For the API docs referring to namespaces, maybe you could make some sort of web component that displays the namespace in the select language's notation automatically. It makes it more natural for users who are just using Windows Runtime APIs like any other language-specific library and make it easier to copy/paste.

**Comment by stevewhims** [comment]
Thanks, @JaiganeshKumaran. Can you give a link to an example of a topic that contains a namespace that you'd like to select and copy to the clipboard? And identify exactly where in the topic the namespace is that you'd like to copy. That'll help me think about the use case, and alternatives.

Thanks!
-Steve
