### ISSUE TITLE
why giving javascript example when language is cpp/winrt?

### ISSUE THREAD

**Issue by yiyang-msft** [MicrosoftDocs/winrt-api#2132]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 432df070-4dcb-4f54-3a77-a139b35b6ea2
* Version Independent ID: 9f7e3191-a8aa-92b1-61a4-30952484a3d5
* Content: [Clipboard.ContentChanged Event (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard.contentchanged?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Last week, I went ahead and created an internal work item to incorporate your suggestions. The change is now live, and you can see the snippet is C# instead of JS (as are all of the Clipboard snippets), so I will go ahead and close this. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
