### ISSUE TITLE
`Windows.ApplicationModel.Email.EmailMessage` Body getting turned into Chinese(?)

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/winrt-api#2134]
I'm using `Windows.ApplicationModel.Email.EmailMessage` to compose an email from an app.

```
   var emailMessage = new Windows.ApplicationModel.Email.EmailMessage
            {
                Body = messageBody
            };
            var emailRecipient = new Windows.ApplicationModel.Email.EmailRecipient(email);
            emailMessage.To.Add(emailRecipient);
            if (!string.IsNullOrEmpty(salesengineeremail))
            {
                var emailSalesEngineer = new Windows.ApplicationModel.Email.EmailRecipient()
                {
                    Address = salesengineeremail,
                    Name = salesengineername
                };
                emailMessage.CC.Add(emailSalesEngineer);
            }
            emailMessage.Subject = subject;
            emailMessage.Attachments.Add(new Windows.ApplicationModel.Email.EmailAttachment() { FileName = fname, Data = dd });
            await Windows.ApplicationModel.Email.EmailManager.ShowComposeNewEmailAsync(emailMessage);
```

I just received a bug report where a user sometimes sees the email composed with the body in a different language. The problem does not reproduce on the second try. I suspect it's some kind of encoding issue, but I don't know if this is an API problem or a Mail app bug. User is on Windows 11.

It seems to translate into Simplified Chinese, but nothing that makes sense (as expected):

汐慥敳猠敥愠瑴捡敨⁤畱瑯⁥㉑䌲㘱䙁⸶਍਍桔湡⁫潹⁵潦⁲档潯楳杮䤠⵮潐楳楴湯吠捥湨汯杯敩ⅳ਍਍

**Comment by EP012014** [comment]
> 

Most of the characters are Chinese Characters, but they make no sense. This is possibly caused by incorrect character set conversion.

**Comment by myokeeh** [comment]
> > 
> 
> 
> 
> Most of the characters are Chinese Characters, but they make no sense. This is possibly caused by incorrect character set conversion.

any guess where the problem is?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @myokeeh   - This feedback is not specifically about the documentation, but rather a support request. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.

Here is a list of other developer support resources that might be able to help with your issue:

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
