### ISSUE TITLE
Link for ValueType goes to the .NET documentation even if under C++/CX or C++/WinRT

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#2145]
The link for ValueType goes to the .NET documentation even if under C++/CX or C++/WinRT. When under C++, it should point here instead: https://docs.microsoft.com/en-us/cpp/cppcx/platform-valuetype-class?view=msvc-170. The same thing is true for Object and other fundamental types.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Jaiganeshkumaran - can you provide some specific examples we could analyse?

**Comment by jaigak** [comment]
@Karl-Bridge-Microsoft Here's an example: https://docs.microsoft.com/en-us/uwp/api/windows.foundation.datetime?view=winrt-22000. The docs says that DateTime inherits from ValueType but the link takes to the .NET docs even if the selected language isn't a .NET language.

**Comment by jaigak** [comment]
Related issue: #2116.

**Comment by stevewhims** [comment]
Thanks for filing this issue. I'm currently pursuing this issue with our content engineering team (since it's not something that a writer can fix in the actual content). I'll go ahead and track that work internally, and meanwhile I'll close this issue so as not to track it twice. The internal issue I'm tracking has a link to this issue, so once that's resolved I'll be able to come back here and update.

Thanks again!
-Steve
