### ISSUE TITLE
Background caching bug of LockScreen.SetImageFileAsync still not fixed after +2 years!!!!

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#2148]
Just read:
https://stackoverflow.com/questions/56935486/cached-image-not-being-updated-with-lockscreen-setimagefileasyncfile

I am having exactly the same issue on a WPF .NET 4.8 project using SDK Contracts. The image is not updated. When I look into 
C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1876093714-2938738926-92039380-1001\ReadOnly
I see lockscreen folders and in each locksreen folder 'LockScreen___2560_1440_notdimmed.jpg' (the image for my 256x1440 screen resolution) is INCORRECT! The other JPEG in the folder are correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68bece6b-32da-533b-6963-b9d92ebf34c2
* Version Independent ID: 987d9f45-d64c-4d8d-2b84-8ea7bac608d6
* Content: [LockScreen.SetImageFileAsync(IStorageFile) Method (Windows.System.UserProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile.lockscreen.setimagefileasync?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.System.UserProfile/LockScreen.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.UserProfile/LockScreen.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. As mentioned in the comments on that Stack Overflow topic, this is a bug in Windows. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
