### ISSUE TITLE
Why are there no code examples of C++WinRT even after I select C++WinRT from drop-list

### ISSUE THREAD

**Issue by rajendrasp** [MicrosoftDocs/winrt-api#2163]
I have seen that on many pages of UWP documentation, even after I select C++WinRT from the drop down, it still shows the example of C#. That is no useful when I am working on C++WinRT project. This is not just for this Button class but many other classes. Can you provide more examples of C++WinRT? Ideally all C# examples should have corresponding C++WinRT examples. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4b27ae-cdce-8fa5-4798-f9e5fa028810
* Version Independent ID: 0b0c46fa-4df5-eac8-b0d4-bc2b4241c0fb
* Content: [Button Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Button.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Button.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by odyright** [comment]
Not only that page. there are several.
And i found that:  (C++/WinRT) example isn't shown, because it must be factored completely differently than the Microsoft .NET examples, and involves several different code files. As they mentioned.

**Comment by jwmsft** [comment]
Thanks for the feedback, and sorry for the inconvenience. We are still working on adding C++/WinRT examples to many of our docs, with a focus on docs for the Windows App SDK. When a doc doesn't have a sample available in the selected language, it will show the sample in the language that is available rather than showing nothing. In this case, only C# is available, so the C# example is shown regardless of the language selector. However, the syntax block at the top of the page will always respond to the language selector.
