### ISSUE TITLE
The " ULARGE_INTEGER" link is broken on this page

### ISSUE THREAD

**Issue by AMollis** [MicrosoftDocs/winrt-api#2168]
The " ULARGE_INTEGER" link is broken on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad7e856-6c76-20c2-454d-8ad7d2a49186
* Version Independent ID: fcb147aa-2526-db6f-6e00-bf68f5787dd3
* Content: [DateTime Struct (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.DateTime?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Foundation/DateTime.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation/DateTime.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. It looks like this link has been fixed in the meantime.

If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
