### ISSUE TITLE
Add the fact that GetFolderFromPathAsync doesn't accept forward slashes

### ISSUE THREAD

**Issue by BlaiseRideout** [MicrosoftDocs/winrt-api#2186]
The fact that GetFolderFromPathAsync doesn't accept forward slashes is missing from this doc page. Suggest copying the same message from the documentation on GetFileFromPathAsync: "If your path uses slashes, make sure you use backslashes (\). Forward slashes (/) are not accepted by this method."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccce37ac-2c72-f833-c5ac-8cb410d163ca
* Version Independent ID: f8a24e0d-153a-233f-3e28-67f775c0b9b2
* Content: [StorageFolder.GetFolderFromPathAsync(String) Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getfolderfrompathasync?view=winrt-22000#windows-storage-storagefolder-getfolderfrompathasync(system-string))
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFolder.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFolder.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by alvinashcraft** [comment]
Hi @BlaiseRitchie. 
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to resolve this doc bug. The change has been committed and should be visible on the live docs site today.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
