### ISSUE TITLE
this page show C# sample code though i requested C++/WinRT code ?!

### ISSUE THREAD

**Issue by moe-salih** [MicrosoftDocs/winrt-api#2190]
check the sample code provided in the 'EXAMPLE' section !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4b27ae-cdce-8fa5-4798-f9e5fa028810
* Version Independent ID: 0b0c46fa-4df5-eac8-b0d4-bc2b4241c0fb
* Content: [Button Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Button.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Button.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, sorry for the inconvenience. When a doc doesn't have a sample available in the selected language, it will show the sample in the language that is available rather than showing nothing. In this case, only C# is available, so the C# example is shown regardless of the language selector. (However, the syntax block at the top of the page will always respond to the language selector.) We are still working on adding C++/WinRT examples to many of our docs, with a focus on docs for the Windows App SDK.
