### ISSUE TITLE
AudioGraph MediaSourceAudioInputNode outputs no audio data after several minutes

### ISSUE THREAD

**Issue by ivder** [MicrosoftDocs/winrt-api#2210]
I have reported this issue in Microsoft forum : https://docs.microsoft.com/en-us/answers/questions/816040/audiograph-mediasourceaudioinputnode-outputs-no-au-1.html

I'm using MediaSourceAudioInputNode node to direct audio data from stream content using MediaSource, into the audio graph by following [this docs][1]. It works well, but it stops outputting any data and the float buffer becomes constantly 0 after playing the playback for  about 7 minutes.

Easy way to reproduce it is by using the [AudioGraph Sample][2] from Microsoft. I modified the Scenario 3 code (Scenario3_FrameInputNode.xaml.cs) to add a simple method to create AdaptiveMediaSource and connect it to AudioGraph. The modified file is attached below. You can see all my modification under `// Test Modification` comment.

[Scenario3_FrameInputNode.xaml.cs.txt](https://github.com/MicrosoftDocs/winrt-api/files/8520246/Scenario3_FrameInputNode.xaml.cs.txt)

Try to execute Scenario 3, wait a bit for audi load, press Generate Audio button, then wait for around 7 minutes. The audio output will be gone and the `dataInFloat` is always 0. Any help/advice would be appreciated

  [1]: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs#mediasource-input-node
  [2]: https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/audiocreation/

**Comment by ivder** [comment]
Hi any update?

**Comment by drewbatgit** [comment]
@ivder Thanks for the feedback. The issues in this repo are intended to track issues specific to the documentation. I.e. We can't provide technical developer support in this forum. I would normally redirect you to the Q&A site, but it seems you've already been there AND opened an issue through the feedback app, so I'm going to go ahead and close this issue here. I will let you know that I did reach out to the team for this feature to bring the issue to their attention and they will investigate/fix according to their own prioritization/resourcing.
