### ISSUE TITLE
IInstalledDesktopApp isn't accessible (CS1022 error?)

### ISSUE THREAD

**Issue by adrastogi** [MicrosoftDocs/winrt-api#2231]
I was trying out the sample code on this page, and Visual Studio gave me a `CS0122 'IInstalledDesktopApp' is inaccessible due to its protection level` error message. It compiled and executed successfully if I changed the type parameter in the generic to `InstalledDesktopApp`. 

Some build information in case that is necessary (I was using the C# WinAppSDK project template):
Microsoft Visual Studio Enterprise 2022
Version 17.2.1
OS: prerelease build of Windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 207d5cfe-20c7-4d3a-afd2-8b70a9e75f31
* Version Independent ID: 1f4e5844-0ead-3ebc-cd21-01c45cd27378
* Content: [InstalledDesktopApp.GetInventoryAsync Method (Windows.System.Inventory) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.inventory.installeddesktopapp.getinventoryasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System.Inventory/InstalledDesktopApp.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Inventory/InstalledDesktopApp.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created a PR to incorporate your suggestions. The changes should be live soon, so I will go ahead and close this issue. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
