### ISSUE TITLE
RadialController Improvement

### ISSUE THREAD

**Issue by C1rdec** [MicrosoftDocs/winrt-api#2239]
I've been playing with the [RadialController](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Input.RadialController) class and I thinks there's some small improvement that would ease the usability. 

1. `Custom Tool` settings
    - We cannot ignore rotation. 
        - For my use case I just need a Hook when Clicked but there's no way to suppress rotation shortcuts.
        
![image](https://user-images.githubusercontent.com/5436436/174135989-40ac04bd-4780-4f69-87e0-a45fdde1b8c0.png)

2. `Explorer.exe` seems to override the `Custom Tool` settings.
    - Defining the `Custom Tool` settings is the only way to have a 'Global Hook' of the `RadialController` and when you give the focus to the `Windows Desktop` | `Taskbar` all the wheel settings are bypass and only the Volume menu is available.
![image](https://user-images.githubusercontent.com/5436436/174136541-3b3054d2-6382-41aa-bc01-bc5a86813004.png)

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @C1rdec   - This feedback is not specifically about the documentation, but rather product feedback. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

Here is a list of other developer support resources that might be able to help with your issue:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
