### ISSUE TITLE
[UWP] failed to convert winow 'HWND' to 'GraphicsCaptureItem'

### ISSUE THREAD

**Issue by sumithsudesan** [MicrosoftDocs/winrt-api#2249]
Trying to convert HWND to 'GraphicsCaptureItem in UWP app

sample code:
        _public static GraphicsCaptureItem CreateItemForWindow(IntPtr hwnd)
        {

            var factory = WindowsRuntimeMarshal.GetActivationFactory(typeof(GraphicsCaptureItem));
            var interop = (IGraphicsCaptureItemInterop)factory;
            var temp = typeof(GraphicsCaptureItem);
            var itemPointer **= interop.CreateForWindow(hwnd, GraphicsCaptureItemGuid);**
            var item = Marshal.GetObjectForIUnknown(itemPointer) as GraphicsCaptureItem;
            Marshal.Release(itemPointer);

            return item;
        }_

Following code throws exception:   interop.CreateForWindow(hwnd, GraphicsCaptureItemGuid);

exception:

_System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>_

**Comment by stevewhims** [comment]
Hi, @sumithsudesan, and thanks for filing this issue. Is there a particular documentation topic with incorrect info? If so, and if that topic has a **Feedback** > **This page** button, then you can leave feedback about it there. Otherwise, if you could specify a link to the topic, and what's wrong with it (in a new issue), that'd be great.

This issue sounds like a support request. For questions/feedback/support about the platform (Windows and its APIs) or tools, and how they behave, you can click **Feedback** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
-Steve
