### ISSUE TITLE
ISensor Interface does support LocationSensors

### ISSUE THREAD

**Issue by xpeace** [MicrosoftDocs/winrt-api#2267]
The ISensor Interface does support location sensors. Using the WinRT (WindowsRuntime/UWP) Location API I cannot access Satellite data, such as HDOP, satellites used, satellites in view,...
When using the WinRT Location API the position source timestamp is usually not available - while the sensor API does offer the timestamp - as a result there is no GPS Timesync available with many GPS interfaces on Windows10 when using the WinRT Location API.  I`ve also noticed there is a Win10 GNSS Driver Interface, without any API documentation. Please add required content in regard of location sensors. 

BR Desperate Dev.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79053c3c-eab3-244e-3eb1-94b2a87292b6
* Version Independent ID: 8d287c2d-a671-da4d-5e73-c7bf11411531
* Content: [Windows.Devices.Sensors Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors?view=winrt-22621)
* Content Source: [winrt-api-build/xml/ns-Windows.Devices.Sensors.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Devices.Sensors.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@stevewhims - This issue is logged against the Device.Sensors namespace, but actually seems to be related to the devices.geolocation namespace. Can you take a look?

**Comment by stevewhims** [comment]
Hi, @xpeace, and thanks for filing this issue.

In terms of updating/fixing the documentation, could you help me out with more details? If you could visit any specific documentation topic that has missing or incomplete or incorrect information, and leave feedback there explaining what's incorrect, that'd be great. As for "there is a Win10 GNSS Driver Interface, without any API documentation", could you let me know which types (and their namespaces) exist in a public Windows SDK, but that are not documented?

I'll go ahead and close this one for now, since I don't see anything immediately actionable in terms of changing the documentation.

Many thanks!
-Steve

**Comment by xpeace** [comment]
With SENSOR_CATEGORY_LOCATION from the deprecated Win32 SensorApi it is possible to access Satellite specific data.
With the new Windows.Devices.Sensor or Windows.Devices.Geolocation it is not possible to get a similar amount of data.
I`m actually missing a Windows.Devices.Sensor.Location subset with corresponding functionality.

I also wonder why the timestamp capability of the Win32 SensorApi Interface (Location sensor) is not always available in the Windows.Devices.Geolocation Geocoordinate.PositionSourceTimestamp Interface.
