### ISSUE TITLE
The value of a ValueSet

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/winrt-api#2268]
You can't query it, iterate it, serialize it, lacks meaningful methods and functions. Seems like it's only purpose is to get information to and from a service, poorly supported and often not working, after which you have to convert it to something useable with traditional techniques.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b61a29dc-8391-f3a9-fbd0-1839daf9fe01
* Version Independent ID: 93ce88a5-bae0-a0b7-be3b-5736a622b92a
* Content: [ValueSet Class (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.ValueSet?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/ValueSet.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/ValueSet.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jaigak** [comment]
In C# ValueSet does implement IDictionary<string, object> so you should be able to use the usual foreach loop and Linq facilities.

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable in the docs, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. If you have feedback about the API itself, you can open a new question on Microsoft Q&A. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
