### ISSUE TITLE
ProviderId doesn't persist when set to an arbitrary guid

### ISSUE THREAD

**Issue by crnobog** [MicrosoftDocs/winrt-api#2276]
I've tried registering a sync root with StorageProviderSyncRootManager.Register with an arbitrary guid in the ProviderId field and then retrieving the registered sync root with StorageProviderSyncRootManager.GetSyncRootInformationForFolder and the retrieved guid is all zeroes.

Should this GUID be associated with some other type or registered somehow in order to work properly? It would be useful if this page linked to some explanations of how to use it. This field is also not used in the Cloud Mirror sample (https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine)

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
