### ISSUE TITLE
missing enum value

### ISSUE THREAD

**Issue by DHancock** [MicrosoftDocs/winrt-api#2297]
`Overlapped` is missing from enum `AppWindowPresenterKind`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe41abef-4479-d12f-14e6-dc3bdb1a25c1
* Version Independent ID: 0f3e3715-7379-4540-3d64-19006ff88bb3
* Content: [AppWindowPresentationKind Enum (Windows.UI.WindowManagement) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindowpresentationkind?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.WindowManagement/AppWindowPresentationKind.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.WindowManagement/AppWindowPresentationKind.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi @DHancock, the API documentation can be kind of confusing with the similarities between the different UI platforms. You'll find `Overlapped` is listed for the [Microsoft.UI.Windowing.AppWindowPresenterKind](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindowpresenterkind?view=windows-app-sdk-1.1) enum. The doc referenced in this issue is for the Windows.UI.WindowManagment.AppWindowPresentationKind enum, which does not include `Overlapped`.

**Comment by DHancock** [comment]
Oh, yes I see. Sorry to have troubled you.
