### ISSUE TITLE
How to use Miracast API to develop UIBC function  (UWP app)

### ISSUE THREAD

**Issue by DamonPan2014** [MicrosoftDocs/winrt-api#2308]
Hi Microsoft team,

I am developing a UWP app, the function is screen share sink and able to send UIBC to source side. Source side is Android app.
- The screen share function works well by using Miracast API.
- **But I don't know which API supports UIBC function.**

**I want to query which API is used for sending UIBC to source side?** such as: send mouse and keyboard event to source side.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdc18356-805d-3a43-d008-b6ba87010fb6
* Version Independent ID: 54db1584-d0fd-aca5-18c5-24ea1958fa95
* Content: [Windows.Media.Miracast Namespace - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.media.miracast?view=winrt-22621)
* Content Source: [winrt-api-build/xml/ns-Windows.Media.Miracast.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Media.Miracast.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@DamonPan2014 The APIs in the Windows.Media.Miracast namespace have not been updated in a while and if you don't see the API you are looking for, it's likely the scenario you are trying to implement is unsupported. Since this repo is solely for issues with the documentation, I suggest you raise this issue on the [Microsoft Q&A site](https://learn.microsoft.com/en-us/answers/index.html).
