### ISSUE TITLE
Example isn't an example

### ISSUE THREAD

**Issue by terrycox** [MicrosoftDocs/winrt-api#2329]
This looks machine generated. Where's the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7a382ee-476f-d871-4c96-a504d040d3e3
* Version Independent ID: 45187f7c-d05a-524b-b9bb-c23578a97bbf
* Content: [DispatcherQueueHandler Delegate (Windows.System) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuehandler?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueueHandler.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueueHandler.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to add a more substantive example and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.
