### ISSUE TITLE
Continuous Dication in Windows.Media.SpeechRecognition stopped working

### ISSUE THREAD

**Issue by naveenrobo** [MicrosoftDocs/winrt-api#2368]
We are running a Windows Application what uses Windows.Media.SpeechRecognizer. Till day before yesterday it was working and we were able to use Continuous Dictation feature and it was great. For last two days the same application stopped working and Continous Dictaion stopped working. We also tried Continous Dictation on Windows Universal Samples there also same issue exists.

Here is the link to the same issue on that repo. 

[Windows-Universal-Sample SpeechReconizer issue](https://github.com/microsoft/Windows-universal-samples/issues/1385)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 955e7722-7a50-43e3-2d42-5a9401145d2f
* Version Independent ID: 1bf1c5d1-2447-0a76-79ab-2bbba827a224
* Content: [SpeechContinuousRecognitionSession Class (Windows.Media.SpeechRecognition) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechcontinuousrecognitionsession?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Media.SpeechRecognition/SpeechContinuousRecognitionSession.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.SpeechRecognition/SpeechContinuousRecognitionSession.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by livioenrico** [comment]
- Starting from the beginning of April 2023, the the online speech dictation has stopped responding on Windows systems worldwide. Tests have been conducted in numerous countries, including Europe, China, and India, and you can verify it on your own PC in just a few seconds by pressing the WINDOWS - H keys.

- It would be advisable for Microsoft to issue an official statement and encourage its users to be patient while the problem is being resolved. Currently, millions of users are following incorrect advice, such as reinstalling the microphone driver, doing a clean restart, or modifying the system registry. And many users have even reinstalled Windows without success.

**Comment by livioenrico** [comment]
- We have dedicated a lot of time to the development of the Theremino GPT application, which allows people with various disabilities, including the blind, to use the PC through voice commands.

- Until a few days ago, these users could use Skype to call their relatives, control home devices, or have friendly conversations with an assistant who could understand their difficulties and find appropriate solutions.

- Currently, these users, who are already facing many difficulties, have been left to themselves due to the failure to repair the online voice dictation server.

- We are disappointed that Microsoft has not been able to solve the problem after more than ten days.

- Please let us know if we can still rely on these functions, otherwise we will be forced to consider alternatives such as Google Speech Recognition.

**Comment by livioenrico** [comment]
We have tested on the latest builds of Windows 10 (22H2 19045.2846) and also on older builds, on numerous different computers, with 32-bit and 64-bit operating systems, in various languages including US English, Italian, and Chinese.

We have tried the on-screen keyboard microphone and also using the WINDOWS + H keys.

We have also tried to compile the "SpeechRecognitionAndSynthesis" example found in Microsoft's official SDKs.

We have also tried to write CSharp applications for Desktop and UWP.

In all cases, using the System.Speech.Recognition classes works fine, but the OnSpeechRecognized and OnSpeechHypothesized callbacks are never called.

All these examples worked perfectly on all PCs up to a month ago.

**Comment by livioenrico** [comment]
Today 19 April 2023 the voice dictation restarted working in Italy.

**Comment by Karl-Bridge-Microsoft** [comment]
Hello @naveenrobo, @livioenrico - This feedback is not specifically about the documentation, but rather product feedback. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.

Here is a list of other developer support resources that might be able to help with your issue:

- The [Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by livioenrico** [comment]
It seems to be resolved for everyone, all around the world, let's hope it doesn't happen again!
Unfortunately, it has already happened at least three times (April 2023, January 2022, summer 2021)
So let's make a summary to help Microsoft next time.

**SYMPTOMS**
- The "Online Voice Typing" stops working on all Windows 10 computers worldwide.
- The affected systems are Windows 10 Home and Windows 10 Pro, both 64-bit and 32-bit.
- Do not confuse this with "Voice Recognition" which still works (but is terrible).
- Dictation in Office 365 and Cortana continues to work.
- Dictation in Office 2019 and other Desktop or UWP applications does not work.
- Dictation does not work in our desktop application Theremino_GPT (based on OpenAI).

**TESTS**
- Using the WINDOWS + H keys opens the control but does not write in Notepad.
- The WINDOWS + H control after about 30 seconds says "An error occurred. Try again later"
- The on-screen keyboard microphone also produces the same results as WINDOWS + H
- CSharp applications for desktop and UWP also do not work.
- The Windows.Media.SpeechRecognition classes do not return errors,
  but the ResultGenerated and HypothesisGenerated callbacks are never called.
- All these examples worked well until the day the problem started.

**NON-WORKING SOLUTIONS**
Microsoft in these cases suggests various changes but: DO NOT FOLLOW THESE TIPS
- Reinstall the microphone driver.
- Change the user or create a new user.
- Download and install system updates.
- Tinker with the registry in various ways or run commands in the console.
- Reinstall Windows.

**HOW THE PROBLEM WAS SOLVED**
- In April 2023, the bug lasted about two weeks.
- Between April 18th and 20th, all Windows 10 computers worldwide started working again.
- In some countries, it took longer, so it seems there are different servers.
- All PCs started working again without restarting and without receiving updates.
- Therefore, this problem is definitely on Microsoft's servers.

It would be greatly appreciated if someone from Microsoft could add some references below, so as to facilitate the solution the next time the same problem occurs.

**Comment by naveenrobo** [comment]
https://github.com/microsoft/Windows-universal-samples/issues/1385#issuecomment-1517805485

as per this comment, this issue seems to be in server. It is now resolved and works for me.

@Karl-Bridge-Microsoft Thanks for the response.
