### ISSUE TITLE
set localname or flags 's error

### ISSUE THREAD

**Issue by phonixshex** [MicrosoftDocs/winrt-api#2379]
BluetoothLEAdvertisementPublisher publisher = new BluetoothLEAdvertisementPublisher();
publisher.Advertisement.Flags = BluetoothLEAdvertisementFlags.GeneralDiscoverableMode | BluetoothLEAdvertisementFlags.ClassicNotSupported;
string localName = "myDeviceName";
publisher.Advertisement.LocalName = localName;
publisher.Start();

when i run it.
it throw a error “System.ArgumentException”
why? localname or flags can't be set?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c610598-b3b7-ee0b-fbc9-9ef3373f3f59
* Version Independent ID: 66258cc1-4e47-170f-0abd-0697017ceca2
* Content: [BluetoothLEAdvertisement.LocalName Property (Windows.Devices.Bluetooth.Advertisement) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.localname?view=winrt-22621#windows-devices-bluetooth-advertisement-bluetoothleadvertisement-localname)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisement.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @phonixshex, I'm investigating.

-Steve

**Comment by stevewhims** [comment]
UPDATE: Yes, this is by design, and I've now updated the docs to mention it. See [BluetoothLEAdvertisementPublisher.Advertisement property](https://learn.microsoft.com/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementpublisher.advertisement), where I've added the following paragraph:

"When configuring the publisher object, you can't add restricted section types (BluetoothLEAdvertisementPublisher.Advertisement.Flags and BluetoothLEAdvertisementPublisher.Advertisement.LocalName). Trying to set those property values results in a runtime exception. You can still set the manufacturer data section, or any other sections not defined by the list of restrictions."

Thanks!
-Steve
