### ISSUE TITLE
Key validity should be 30 days.

### ISSUE THREAD

**Issue by DangJoRuss** [MicrosoftDocs/winrt-api#2398]
This page says "This key is valid for 90 days."  It should say "This key is valid for 30 days."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13f85bf6-849d-020a-7c1b-fc949e102eee
* Version Independent ID: 26ce2d38-6da1-59f2-88dd-f386ba61f2e1
* Content: [StoreContext.GetCustomerPurchaseIdAsync(String, String) Method (Windows.Services.Store) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.getcustomerpurchaseidasync?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Services.Store/StoreContext.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Services.Store/StoreContext.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Reaching out to Store team.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
