### ISSUE TITLE
Please add C++/WinRT example code

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/winrt-api#2415]
Please add C++/WinRT example code as an alternative to the C# code.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16c14008-04b3-438b-5fae-3577cf233ab9
* Version Independent ID: 52f2f07b-034e-1d24-1b48-b4de7585e71a
* Content: [ContentDialog Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ContentDialog.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ContentDialog.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Thanks, @dr-eck. I've added this work to my backlog. Because there's quite a bit of code in there, and we don't automatically port *all* code examples into C++/WinRT. C# is the priority, and then we port for C++/WinRT for the topics that need it the most (by various criteria). But UI isn't necessarily something that would make the bar. Since I'm tracking it elsewhere, I'll close this issue until (and if) I get around to it.

Meanwhile, see the [C++/WinRT](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/) for examples of UI/XAML code, and also content about porting from C#.

Thanks!
-Steve
