### ISSUE TITLE
I want to know the screenshots in this page come from which software?

### ISSUE THREAD

**Issue by openjz** [MicrosoftDocs/winrt-api#2424]
I want to know the screenshots in this page come from which software? Seems not the Device Manager in Windows 10 or Windows11.

![image](https://github.com/MicrosoftDocs/winrt-api/assets/35456381/89cf9a59-a681-4bef-8718-49cf90ec9659)

like this

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 920fa15c-7455-7b9b-0c5b-ec0310161145
* Version Independent ID: 6b9beb7a-ec8f-7f64-ece6-0f43bfea9552
* Content: [DeviceInformationKind 枚举 (Windows.Devices.Enumeration) - Windows UWP applications](https://learn.microsoft.com/zh-cn/uwp/api/windows.devices.enumeration.deviceinformationkind?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformationKind.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformationKind.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @openjz. I'm investigating.

-Steve

**Comment by openjz** [comment]
Thanks, @stevewhims , have some conclusions?

**Comment by stevewhims** [comment]
Hi, @openjz, and sorry for the delay in responding.

The screenshots in this topic are just for illustrative purposes. They're meant to give insights into the data model that you can access by using these APIs.

To create these screenshots, we used custom software that simply uses the same public APIs and header files that we're documenting here. So anyone can use our public APIs and headers and produce the same result. This topic explains how the objects fit together so that you can, if you like, implement a treeview that's based on the object relationships (just like in the screenshots).

Thanks!
-Steve
