### ISSUE TITLE
Documentation for Incorrect Function error on StorageProviderSyncRootManager.Register 

### ISSUE THREAD

**Issue by fc-lia** [MicrosoftDocs/winrt-api#2465]
Myself and some coworkers have been encountering an issue with a cloud storage application using `StorageProviderSyncRootManager` where the `Register` method fails with the HRESULT error for Incorrect Function. Is it possible to provide documentation or troubleshooting leads for this error, or enumerate some of the possible failures for `StorageProviderSyncRootManager.Register` ? This is proving to be a bit of a dead end for debugging as the failure is completely opaque

We are working with the C++ winrt version

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to incorporate your suggestions. I'll track down somebody from the product team to get some more information about how to handle this error. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

The organization is moving to a new feedback system, so I want to make sure to capture my open issues before the Issues functionality is turned off for this repo.
