### ISSUE TITLE
VoipCallCoordinator: Lacking details on when RequestNewIncoming/OutgoingCall return null

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#271]
Relevant documentation pages in the `Windows.ApplicationModel.Calls.VoipCallCoordinator` namespace:
  - [RequestNewIncomingCall](https://github.com/MicrosoftDocs/winrt-api/blob/3e3939f289e1a0ff84c5541b7ea93eb19780f0e7/windows.applicationmodel.calls/voipcallcoordinator_requestnewincomingcall_402033120.md#L0)
  - [RequestNewOutgoingCall](https://github.com/MicrosoftDocs/winrt-api/blob/3e3939f289e1a0ff84c5541b7ea93eb19780f0e7/windows.applicationmodel.calls/voipcallcoordinator_requestnewoutgoingcall_1560251997.md#L0)

As you can see from the VoIP sample, it looks like these APIs can return `null`:
  - [RequestNewIncomingCall null check](https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/VoIP/cs/VoipTasks/Helpers/VccCallHelper.cs#L130)
  - [RequestNewOutgoingCall null check](https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/VoIP/cs/VoipTasks/Helpers/VccCallHelper.cs#L85)

Here are my questions:
  - When can these APIs return null?
  - When they return null, is there a way to get additional information about why the API call failed?

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you @rigdern for your feedback. @GrantMeStrength can you respond?

**Comment by MatchaMatch** [comment]
Hey Adam - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
