### ISSUE TITLE
VoipCallCoordinator.RequestNewIncomingCall: Lacking details on what kinds of URI schemes are supported

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#277]
Relevant document page:
  - [Windows.ApplicationModel.Calls.VoipCallCoordinator.RequestNewIncomingCall](https://github.com/MicrosoftDocs/winrt-api/blob/42ebb9fdd8ccb74b8c3708755a5a700fb7671a02/windows.applicationmodel.calls/voipcallcoordinator_requestnewincomingcall_402033120.md#L0)

For the `contactImage`, `brandingImage`, and `ringtone` parameters are there any restrictions on the kinds of URIs that are accepted? For example, do `file`, `ms-appx`, and `https` URIs all work?

I ask because I was struggling with `ms-appx` and `http` URIs. Finally, I got a URI with a `file` scheme to work. I suspect the other schemes are not supported. If I am correct about this restriction, it would be great to document it.

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thanks @rigdern for the feedback. @GrantMeStrength, can you address?

**Comment by GrantMeStrength** [comment]
Let me check..

**Comment by MatchaMatch** [comment]
Hey Adam - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
