### ISSUE TITLE
this property doesn't automatically show any meta data on SMTC

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/winrt-api#319]
I tried to set this property right after I created my mediaPlaybackItem and then I added it to my mediaPlaybackList andfinally I assigned the list as source of my mediaPlayer. I used system media transport controls. and not even the title of the video was displayed on SMTC , let alone the thumbnail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d383d71-b3b4-9143-043c-b1616f14a63c
* Version Independent ID: 86a3e461-6b94-25cc-0553-6b6e933aef1f
* Content: [AutoLoadedDisplayPropertyKind Enum (Windows.Media.Playback) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.autoloadeddisplaypropertykind?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Media.Playback.AutoLoadedDisplayPropertyKind)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.autoloadeddisplaypropertykind.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.autoloadeddisplaypropertykind.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Hello, sorry for the long delay in the response to this issue. GitHub issues in this repository are for feedback specifically about the documentation. I was unable to reproduce your issue so it seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
