### ISSUE TITLE
When is it appropriate to set the advertisement filter?

### ISSUE THREAD

**Issue by g-ortuno** [MicrosoftDocs/winrt-api#351]
Could the advertisement filter be set during a scan? Would the scan then be updated to use the new filters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b0d984-20b4-005d-68ca-7827647d6b50
* Version Independent ID: 316280a7-2cc2-f1cf-503d-bbef926cd2ab
* Content: [BluetoothLEAdvertisementWatcher.AdvertisementFilter Property (Windows.Devices.Bluetooth.Advertisement) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher.advertisementfilter#Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher_AdvertisementFilter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @g-ortuno. Thanks for filing this issue, and my apologies for the delay in responding.

I don't have any additional content for your scenario, over and above what's in the documentation. So it might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by g-ortuno** [comment]
Thanks! Will do.
