### ISSUE TITLE
GattProtocolError.UnsupportedGroupType == GattProtocolError.InsufficientEncryption == 15

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#359]
On my system at runtime, both GattProtocolErrors [UnsupportedGroupType ](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattprotocolerror.unsupportedgrouptype) and [InsufficientEncryption](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattprotocolerror.insufficientencryption) equal value 15. Can this be correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ed9dcc-f624-b054-bbf3-f595ecb75255
* Version Independent ID: cac6ba00-b26b-c934-1a48-81ebe74b0ef8
* Content: [GattProtocolError.InsufficientEncryption Property (Windows.Devices.Bluetooth.GenericAttributeProfile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattprotocolerror.insufficientencryption)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattprotocolerror.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattprotocolerror.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @LukeOwlclaw. Thanks for filing this issue, and my apologies for the long delay in responding.

Although we don't document the values of these statics, I can tell you that I also get a value of 15 decimal for both in my experiments.

I don't have any additional content over and above that. If you suspect a bug, or if you have feedback/suggestions, then it might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by ghost** [comment]
I do not remember what my actual problem was. I still find it curious that "group type error" and "insufficient encryption error" have identical error codes. I am not using WinRT at the moment so I cannot investigate further nor provide additional feedback.
