### ISSUE TITLE
My route forked at one point into 2 seperate routes, as if there were 2 endpoints

### ISSUE THREAD

**Issue by davefxy** [MicrosoftDocs/winrt-api#364]
I created a route from Denver to Las Vegas, Morro Bay CA and ending in Los Altos CA. I used a total of 9 geopoints to describe the route. When I used the MapRouteFinder.GetDrivingRouteFromWaypointsAsync()the route forked where I70 hits I15. So 1 leg goes south on I15 towards Morro Bay and the other goes north to I80 and then to the bay area.
Is this a bug or I didn't make the right sequence with the Windows.Services.Maps API ? The following describes how I used the Windows.Services.Maps API.
I created a list of Geopoints: start, end, waypoints. Then I used MapRouteFinder.GetDrivingRouteFromWaypointsAsync(Iterable, MapRouteOptimization, MapRouteRestrictions) to define the route . I then used MapRouteView(MapRouteFinderResult.Route) to get the MapRouteView. Cleared the mapcontrol.Routes.clear(). Added the new MapRouteView to the Routes collection : mapcontrol.Routes.Add(). Fit the MapControl to the route : mapcontrol.TrySetViewBoundsAsync().
Updated:
I found that I needed to use waypoint pairs with MapRouteFinder API. I needed to add all route points like so: start point,waypoint A, waypoint A,Waypoint B, Waypoint B,Waypoint C, .........Waypoint H,end point. I must not have understood the explanation for the API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0182714-e385-4cc9-4c4d-6132e3f535aa
* Version Independent ID: 0f85c120-d434-a09c-aa30-7e534b477ce9
* Content: [MapRouteFinder.GetDrivingRouteFromWaypointsAsync Method (Windows.Services.Maps) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.services.maps.maproutefinder.getdrivingroutefromwaypointsasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.maps.maproutefinder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.maps.maproutefinder.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by normesta** [comment]
Thanks for posting this. That result is very interesting. It does seem cumbersome to have to specify a pair of GeoPoints for each of your stops. 
Have you tried using GetDrivingRouteFromEnhancedWaypointsAsync instead of GetDrivingRouteFromWaypointsAsync? I ask because if you use GetDrivingRouteFromWaypointsAsync, each route leg will have it's own itinerary. I haven't encountered the exact same issue as yours, but it could lead to some interesting paths.  With the GetDrivingRouteFromEnhancedWaypointsAsync method, you can specify "via" waypoints of a route so that the route must pass through your via waypoints. There's a code example for this near the bottom of this topic - https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/routes-and-directions.
