### ISSUE TITLE
There is no .idl or .h to call these APIs in the Windows SDK

### ISSUE THREAD

**Issue by CarePackage17** [MicrosoftDocs/winrt-api#367]
I've installed all Windows SDKs from 10586 to the newest 17134 and these APIs are nowhere to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 754bb165-8c08-90a4-3c4a-d4870990513a
* Version Independent ID: a4a1e091-6b3c-4472-0b75-551e5c721975
* Content: [PerceptionMonitor Class (Windows.Perception.Automation.Monitoring) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.perception.automation.monitoring.perceptionmonitor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.automation.monitoring.perceptionmonitor.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.automation.monitoring.perceptionmonitor.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Holo-Krzysztof** [comment]
It'd be really nice to be able to use this on PC with the Perception Simulation service that Mixed Reality Portal uses internally. 
This would enable us to implement remote rendering from other PCs as well as from Windows Holographic Devices in a reliable way with all features (i.e. image stabilization).

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
