### ISSUE TITLE
StorageFolder status after DeleteAsync()

### ISSUE THREAD

**Issue by NicolasG3** [MicrosoftDocs/winrt-api#370]
Please document if the StorageFolder can still be used after DeleteAsync() call.
Please add an example to reset an existing folder by deleting and recreating it.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 04061719-8b57-32dd-ee2a-92d303d0fd94
* Version Independent ID: 6a1c5dbc-4ec0-a1f3-f62f-4b4de8bd4b28
* Content: [StorageFolder.DeleteAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/fr-fr/uwp/api/windows.storage.storagefolder.deleteasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DFR-FR%26k%3Dk(Windows.Storage.StorageFolder.DeleteAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet have been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
