### ISSUE TITLE
DisplayMonitor.FromIdAsync() always throws exception on 17134.48

### ISSUE THREAD

**Issue by jonitis** [MicrosoftDocs/winrt-api#378]
Verified on two systems and both c# and c++/winrt that usual pattern of
1. getting device selector with DisplayMonitor::GetDeviceSelector();
2. getting device id using DeviceInformation::FindAllAsync(monitorSelector);
3. instantiating monitor instance with DisplayMonitor::FromIdAsync(id);
does not work as last step always throws ERROR_FILE_NOT_FOUND exception. 

See recreation scenario here:
https://gist.github.com/jonitis/c4d35dd3a7ce8cf47d1f4cd5bf665f01

On the other hand DisplayMonitor::FromInterfaceIdAsync(interfaceId); works fine, but then you have to use win32 Win32EnumDisplayDevices() function to obtain device interface name for each monitor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e25d65-ef82-1126-215b-1f3823cd5b31
* Version Independent ID: 627d452f-6d8b-9bd5-dab8-d709edc1c770
* Content: [DisplayMonitor.FromIdAsync(String) Method (Windows.Devices.Display) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.displaymonitor.fromidasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.display.displaymonitor.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.display.displaymonitor.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jonitis** [comment]
Just noticed that if you pass DeviceInformation.Id() to DisplayMonitor::FromInterfaceIdAsync() then it works, as expected. So Id property of DeviceInformation actually matched the interfaceId obtained by Win32 EnumDisplayDevices() with EDD_GET_DEVICE_INTERFACE_NAME flag.
But then question arises that kind of input we are supposed to pass to DisplayMonitor::FromIdAsync() ???

**Comment by jonitis** [comment]
Current documentation clearly states that FromIdAsync() deviceId argument is "The identity of the device (see DeviceInformation.Id)". Is DeviceInformation.Id field then filled with wrong value? Otherwise it would not make sense for existence of DisplayMonitor::FromInterfaceIdAsync() that is documented as used for interop with Win32 APIs.

**Comment by stevewhims** [comment]
Sorry about this, @jonitis. I'm looking into the issue, and I'll update the docs and get back to you when I have a definitive answer. Meanwhile, for what it's worth, I have found that if you pass that Id to FromInterfaceIdAsync instead of to FromIdAsync, then that works. You don't need to use a Win32 API. Here's my listing, in case it helps.

winrt::Windows::Foundation::IAsyncAction DisplayMonitorAsync()
{
    const DeviceInformationCollection deviceInformations = co_await DeviceInformation::FindAllAsync(DisplayMonitor::GetDeviceSelector());

    for (DeviceInformation const& deviceInformation : deviceInformations)
    {
        try
        {
            DisplayMonitor displayMonitor1 = co_await DisplayMonitor::FromInterfaceIdAsync(deviceInformation.Id());
            DisplayMonitor displayMonitor2 = co_await DisplayMonitor::FromIdAsync(deviceInformation.Id()); // throws (see below).
        }
        catch (winrt::hresult_error const& ex)
        {
            HRESULT hr = ex.to_abi(); // ERROR_FILE_NOT_FOUND.
            winrt::hstring message = ex.message(); // The system cannot find the file specified.
        }
    }
}

**Comment by ChrisGuzak** [comment]
This code pass a reference (DeviceInformation const&) across async steps. I suspect if you remove '&' (to make a copy) the bug is fixed.

From: Steven White <notifications@github.com>
Sorry about this, @jonitis<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonitis&data=02%7C01%7Cchrisg%40microsoft.com%7Cdb131fd9c2d7462d78dd08d5c0257060%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636626189397253553&sdata=%2Fdst0tZmJspUDCan%2F0mgJNQj0oEDNnvnCNOlGdTO50w%3D&reserved=0>. I'm looking into the issue, and I'll update the docs and get back to you when I have a definitive answer. Meanwhile, for what it's worth, I have found that if you pass that Id to FromInterfaceIdAsync instead of to FromIdAsync, then that works. You don't need to use a Win32 API. Here's my listing, in case it helps.

winrt::Windows::Foundation::IAsyncAction DisplayMonitorAsync()
{
const DeviceInformationCollection deviceInformations = co_await DeviceInformation::FindAllAsync(DisplayMonitor::GetDeviceSelector());

for (DeviceInformation const& deviceInformation : deviceInformations)

{

    try

    {

        DisplayMonitor displayMonitor1 = co_await DisplayMonitor::FromInterfaceIdAsync(deviceInformation.Id());

        DisplayMonitor displayMonitor2 = co_await DisplayMonitor::FromIdAsync(deviceInformation.Id()); // throws (see below).

    }

    catch (winrt::hresult_error const& ex)

    {

        HRESULT hr = ex.to_abi(); // ERROR_FILE_NOT_FOUND.

        winrt::hstring message = ex.message(); // The system cannot find the file specified.

    }

}

}

**Comment by stevewhims** [comment]
The bug is to do with passing an interface id where a device id is expected (I'm still investigating offline). Can you tell me more about the reference-passing question in this particular case? Do you mean that the variable named deviceInformation is a reference, and it's being passed into an Async method? I'm not clear on how the guidance here (https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency#parameter-passing) is being contravened here. Am I wrong in believing that since the variable named deviceInformation is a reference to an element of the variable named deviceInformations, and deviceInformations will stay in scope for the duration of the coroutine, then the code above is sound? If not, I'd love to know exactly why and what the fix is. Thanks!

**Comment by ChrisGuzak** [comment]
I might have this wrong but try removing the ref and see if it produces a different result.

**Comment by stevewhims** [comment]
Removing the ref produces the same result (but I believe that's b/c I'm passing the wrong type of Id to that function; and the other function took the same ref, and is also async, but that worked). However, I'm thinking that just because removing the ref doesn't fix the issue, that alone doesn't mean that the ref is ok. :) Nor that it's a solid approach in general. I'll take this up on the internal cppwinrt dl and see whether I can get super-crisp on the details there (e.g. I know I have to copy or move a std::vector<hstring> into an async callee but I don't know whether that's what I have to do generally). While it's something I'd like to know, I do believe that this is an orthogonal question from the original issue, so I'm still investigating how to get the actual device Id for a DisplayMonitor (rather than the interface id).

**Comment by ChrisGuzak** [comment]
Yep, I followed up off line and learned that I had this wrong. ref params to a function do suffer from the case I was thinking about.

**Comment by stevewhims** [comment]
@ChrisGuzak: right, it was good to bring that up, I'm now clearer on the best practices there.

@jonitis: I've pushed fixes to these topics to master; I expect those to get to live (that is, published) in the next 24 hours. Essentially the answer is that going back to your steps 1-3 in your original post at the start of this thread, that's all fine except you should call FromInterfaceIdAsync and not FromIdAsync. Steps 1 and 2 give you an interface id. So that's the recommended set of steps, and the topic for FromIdAsync was misleading. I've now fixed up all the affected topics, and added more links so that you'll be directed to the right API and get the right info.

**Comment by jonitis** [comment]
Hi guys. Thanks for feedback.

But I forgot to emphasize that my concern is that it was not problem with wrong documentation, but actually with implementation of Windows::Devices::Display::DisplayMonitor class that is new in Windows 1803. I just have no better place to report platform bug. I've opened ticket at wpdev.uservoice, but not sure whether someone monitors it.
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/34291015-windows-devices-display-displaymonitor-fromidasync

My logic is that UWP has at least 50 concrete classes that implement GetDeviceSelector() method that returns AQS string, then it is passed to DeviceInformation::FindAllAsync() to get collection of DeviceInformation that each has ID property and finally specific classes implement FromIdAsync(id) to instantiate the object. It works this way for SerialDevice, SmartCardReader etc., but not for DisplayMonitor. The fact that there is distinct FromInterfaceIdAsync() method with specific purpose to work with APIs that are returned by e.g. Win32 EnumDisplayDevices() means that it should have different purpose than FromIdAsync(). So I want feedback from developers of that component (Windows.Graphics.dll) what kind of input FromIdAsync() is expecting. And, possibly, FromIdAsync() itself is actually correct, but the DeviceInformation instance for monitors is getting wrong Id() property value. Since id property is working fine when it is passed to FromInterfaceIdAsync() it hints that it is really interface id - not device id. So how do we obtain valid device id that can be used with FromIdAsync()?

Think about that all those 50 places in UWP API must be consistent. So it does sound good to "Always pass id to FromIdAsync(), but in this (broken) case use it FromInterfaceIdAsync()".

Windows SDK does not yet have samples for this new Windows::Devices::Display::DisplayMonitor API family. Searching the web also does not return any information. The only code in Microsoft codebase might be [Settings]-[Display]-[Advanced display settings] that shows the list of monitors. But most likely they do not use FromIdAsync(), but some other means to enumerate monitors.

Please pass this info to developers, not just fix documentation for possibly broken implementation.

P.S.
And there is no problem with passing args by reference - they outlive the function call since I explicitly block with .get() on async results. I've also tested it with C# with same exception.

**Comment by jonitis** [comment]
Of course, I meant "it does NOT sound good to" (hide problem) :)

**Comment by jonitis** [comment]
Here is the output from Win32 EnumDisplayDevices() calls:
Display adapter 0:
  DeviceName = \\.\DISPLAY1
  DeviceString = Intel(R) HD Graphics
  StateFlags = 0x00000005
    ATTACHED_TO_DESKTOP
    PRIMARY_DEVICE
  DeviceId =
  DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Video\{0C0D3190-4DE2-11E8-9D24-00249B13949F}\0000
  Display monitor 0:
    DeviceName = \\.\DISPLAY1\Monitor0
    DeviceString = Generic PnP Monitor
    StateFlags = 0x00000003
    ATTACHED_TO_DESKTOP
    MULTI_DRIVER
    DeviceId = MONITOR\DELA0A3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
    DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
    DeviceId[DEVICE_INTERFACE_NAME] = \\?\DISPLAY#DELA0A3#4&27e3cd2c&0&UID51249920#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}

Display adapter 1:
  DeviceName = \\.\DISPLAY2
  DeviceString = Intel(R) HD Graphics
  StateFlags = 0x00000001
    ATTACHED_TO_DESKTOP
  DeviceId =
  DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Video\{0C0D3190-4DE2-11E8-9D24-00249B13949F}\0001
  Display monitor 0:
    DeviceName = \\.\DISPLAY2\Monitor0
    DeviceString = Generic PnP Monitor
    StateFlags = 0x00000003
    ATTACHED_TO_DESKTOP
    MULTI_DRIVER
    DeviceId = MONITOR\DELA0A3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
    DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
    DeviceId[DEVICE_INTERFACE_NAME] = \\?\DISPLAY#DELA0A3#4&27e3cd2c&0&UID53349120#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}

**Comment by jonitis** [comment]
For some reason attaching output distorted double slashes with single ones. I will attach sample code snippet for EnumDisplayDevices() in a minute

**Comment by jonitis** [comment]
https://gist.github.com/jonitis/c12ec3bc8a21b62241e17dd7586c0b85

**Comment by stevewhims** [comment]
@jonitis, yes, the Windows developer feedback site (https://wpdev.uservoice.com/) is the right place to file a product bug. There's also Microsoft Support (https://support.microsoft.com/contactus/). The comment section here is for feedback about the actual documentation.

However, I've been in touch with the product group for these APIs, and they concur with your analysis. “Thanks for the feedback. We acknowledge that this naming is inconsistent with the other Windows.Devices.* APIs. The reason is that DisplayMonitor.FromIdAsync actually takes PnP device instance paths, whereas DisplayMonitor.FromInterfaceIdAsync takes PnP device interface paths. DisplayMonitor.GetDeviceSelector returns a selector string to retrieve device interfaces and the default overload of DeviceInformation.FindAllAsync uses this to return interface paths from the resulting DeviceInformation.Id properties as well. We wanted to allow you to create a DisplayMonitor from either one in case you discover the device instance path (you can get to it in various ways using DeviceInformation or PnpObject APIs), but we should have made the “default” FromIdAsync method take interfaces since that’s the more common case and introduced a differently named method to take instance paths.”

I've captured the above info in the topics, now. Please let me know if there's anything else I can do to improve the documentation here. And thanks again for the feedback and your diligence in reporting these issues. We do regret the inconvenience.
-Steve

**Comment by jonitis** [comment]
Thank you very much for prompt and detailed reply!

I've verified that indeed if I ask for additional property "System.Devices.DeviceInstanceId" in DeviceInformation::FindAllAsync() I can pass it to DisplayMonitor::FromIdAsync() and it works as expected.

So both API methods work as expected, although slightly confusing for users to figure out right arguments.

Please, please, please add those details about device instance paths vs. interface paths to method description. Mentioning ways how to obtain right ids would also help.

**Comment by stevewhims** [comment]
You're welcome, and yes I have added the details that you mention. There is now a code example for both FromIdAsync and FromInterfaceIdAsync showing how to call FindAllAsync and then construct a DisplayMonitor from a device instance id (using additional properties) and a device interface id, respectively. I've checked in that fix, and I expect it to appear on the live site within 24 hours. Please close this issue whenever you feel it's resolved. Many thanks for pointing this out!  ~Steve

**Comment by stevewhims** [comment]
FYI: currently there's a delay with my change in the publishing system: I'm working with an engineer to see what we can do to get it going. :)

**Comment by jonitis** [comment]
Thanks!
Sample is very helpful. I've learned preferred way to use winrt::unbox_value to access properties :)

Closing as fixed

**Comment by stevewhims** [comment]
Thanks, @jonitis! :)
