### ISSUE TITLE
saveScreenshotToFilesAsync function error on Windows 1803

### ISSUE THREAD

**Issue by cp-fabian-pittroff** [MicrosoftDocs/winrt-api#390]
Hello there,

I have a problem with the saveScreenshotToFilesAsync function. In the previous windows version 1709 it worked somewhat. The promise of the async funtion couldn't be resolved, but the funtion it self worked and I implemented a workaround to get the picture.

With Windows 1803 I get an error, in the promise which didn't work previously.

```
[object Windows.Media.AppRecording.AppRecordingSaveScreenshotResult]: {extendedError: -2147417842, savedScreenshotInfos: Object, succeeded: false}
extendedError: -2147417842
 
savedScreenshotInfos: Object
length: 0
size: 0
```
Some code snipets:

```
const prefix = 'scr'
const tempDir = Windows.Storage.ApplicationData.current.temporaryFolder
const AppRecordingManager = Windows.Media.AppRecording.AppRecordingManager
const AppRecordingSaveScreenshotOption = Windows.Media.AppRecording.AppRecordingSaveScreenshotOption
const requestedFormats = [Windows.Media.MediaProperties.MediaEncodingSubtypes.png]
const asyncResult = AppRecordingManager.getDefault().saveScreenshotToFilesAsync(tempDir, prefix, AppRecordingSaveScreenshotOption.hdrContentVisible, requestedFormats)
asyncResult.then(function (thenResult) {
      console.log("thenResult", thenResult)
}).done(function (doneResult) {
      console.log("doneResult", doneResult)
})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fdc5b98-1fc2-5b9c-27f6-a804ff5e5d3a
* Version Independent ID: cac5005a-6c01-45aa-c826-21ae933cb62c
* Content: [AppRecordingManager.SaveScreenshotToFilesAsync(StorageFolder, String, AppRecordingSaveScreenshotOption, IIterable<String>) Method (Windows.Media.AppRecording) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.apprecording.apprecordingmanager.savescreenshottofilesasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.apprecording.apprecordingmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.apprecording.apprecordingmanager.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by ralfstuckert** [comment]
Any news regarding this issue?

**Comment by drewbatgit** [comment]
I apologize. I missed your comment when you posted it. I have passed this question on to the feature team that owns this feature and will respond to this thread when I get any new info on your issue.

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
