### ISSUE TITLE
Where did "DualApiPartition" go?

### ISSUE THREAD

**Issue by simonbuchan** [MicrosoftDocs/winrt-api#391]
https://msdn.microsoft.com/en-us/library/windows/desktop/mt695951(v=vs.85).aspx suggests the Windows.Devices.Geolocation.Geolocator type as an example of an API that has a "DualApiPartition" attribute, meaning it can be used from a classic desktop application - however it doesn't seem to be shown anywhere in the class or member pages.

In particular, types like CoreApplication are *not* supported, but don't have any indication of such.

There is also https://msdn.microsoft.com/en-us/library/windows/desktop/dn554295(v=vs.85).aspx - but it seems quite out of date (e.g. it doesn't include Geolocator!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61fe67f8-064b-8a64-2c26-99241e2d65d0
* Version Independent ID: 35b06510-3909-8511-f31e-e38ecc7806d1
* Content: [Geolocator Class (Windows.Devices.Geolocation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Geolocation.Geolocator)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.geolocator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.geolocator.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @simonbuchan, if you look right above the "Windows 10 requirements" table, there's an "Attributes" label and a list of attributes. It's the presence or absence of DualApiPartitionAttribute in that list that is the indicator.

The other topic you link to is explicitly out of date since it refers to Windows 8.x. The Windows Runtime API documentation covers Windows 10 and also 8.x. So for example the Geolocator topic that you filed this issue on would be the best place to determine what APIs are callable in this way.

I'll close this for now, but please reopen and/or comment further if you'd like.

~Steve

**Comment by simonbuchan** [comment]
Thanks! That seems to be exactly what I was looking for. Not sure how I could have missed it, but it's definitely been known to happen 🤷‍♂️

**Comment by stevewhims** [comment]
Great, thanks, @simonbuchan!
