### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by BYTEzel** [MicrosoftDocs/winrt-api#394]
More examples of the filter calls would be highly helpful - what are the possible filter settings? How can I combine the wildcard character? Is it possible to delete a filter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ee6b6b-0d99-9eea-7a1c-7913d65a9f65
* Version Independent ID: 79ea33b6-f890-cd16-88c2-64f92cb96cf4
* Content: [FolderPicker.FileTypeFilter Property (Windows.Storage.Pickers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker.filetypefilter?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.Pickers.FolderPicker.FileTypeFilter)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.folderpicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.folderpicker.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mijacobs** [comment]
Thanks for the feedback! You're totally right, some examples would be very useful here--we'll work on adding some.

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the code snippets have been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
