### ISSUE TITLE
FileIO.WriteBufferAsync should return null if failure so check can be made.

### ISSUE THREAD

**Issue by BajaPaul** [MicrosoftDocs/winrt-api#400]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31cb322-6c77-3bd7-ec40-1fac332b2f15
* Version Independent ID: 0837f31c-04d8-3224-a728-517f7c218ec1
* Content: [FileIO.WriteBufferAsync(IStorageFile, IBuffer) Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileio.writebufferasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileio.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
