### ISSUE TITLE
Missing returns precision.

### ISSUE THREAD

**Issue by placasse** [MicrosoftDocs/winrt-api#402]
What happens if the method does not complete successfully ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7ccb10-d178-a7f6-8dfc-fa70983119a7
* Version Independent ID: d9bc420c-1436-f024-f300-c3ae5d728782
* Content: [StorageItemAccessList.GetFolderAsync Method (Windows.Storage.AccessCache) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist.getfolderasync#Windows_Storage_AccessCache_StorageItemAccessList_GetFolderAsync_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
