### ISSUE TITLE
Windows iot

### ISSUE THREAD

**Issue by LMFSoft** [MicrosoftDocs/winrt-api#403]
The method and the example provided is not working on windows iot on ARM (Raspberry PI3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e03739b-1976-072e-a307-9bcab24af651
* Version Independent ID: f8b625f6-8a3f-ab8c-32bf-0d394e6f59bb
* Content: [StorageFolder.GetItemsAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getitemsasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
