### ISSUE TITLE
The definition of "close proximity" please.

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/winrt-api#404]
Could you clarify "close proximity"?  Do5 px, 10 px, 20 px qualify for "close proximity"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f7c5ee-85ee-3098-ba79-91e87139b858
* Version Independent ID: 7dca0d00-0fc1-af08-ed84-1608b89a54c2
* Content: [ApplicationView.AdjacentToLeftDisplayEdge Property (Windows.UI.ViewManagement) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.adjacenttoleftdisplayedge)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.applicationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.applicationview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by GrantMeStrength** [comment]
Sorry for the delay in getting to this. It turns out there is no hard and fast definition for what "proximity" means. If there is a specific scenario which this is blocked, please re-open this issue and we can work on resolving it. Another source of help could be the Microsoft Q&A Forums - https://docs.microsoft.com/en-us/answers/index.html
Sorry we were unable to help in this instance.
