### ISSUE TITLE
Seems to require UI thread

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#408]
It appears an exception is thrown if the constructor is called on other than the UI thread.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f923a4b6-4675-0237-093f-8199c3b9e7f0
* Version Independent ID: da49cd15-3d01-d640-fb60-3d9b64d7a6a7
* Content: [WriteableBitmap(Int32, Int32) Constructor (Windows.UI.Xaml.Media.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap.-ctor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.writeablebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.writeablebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@jesbis In general, XAML objects need to be constructed on the UI thread. Do people expect that this one is special, maybe?

**Comment by jesbis** [comment]
WinRT Xaml types have UI thread affinity, though that can be confusing sometimes because they're technically marked MarshalingBehavior=Agile and Threading=Both. However, there's nothing special about WriteableBitmap in that regard. 

An overview of the threading model for DependencyObject and how to use the Dispatcher to access objects from another thread is available here: 

https://docs.microsoft.com/uwp/api/windows.ui.xaml.dependencyobject.dispatcher
