### ISSUE TITLE
What does it return when this method does not complete successfully?

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/winrt-api#409]
What does it return when this method does not complete successfully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3098bacc-b9eb-3d19-047d-63b385fb8a42
* Version Independent ID: 60c88ad7-f216-256f-8d16-6e096a480770
* Content: [FolderPicker.PickSingleFolderAsync Method (Windows.Storage.Pickers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker.picksinglefolderasync#Windows_Storage_Pickers_FolderPicker_PickSingleFolderAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.folderpicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.folderpicker.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by metathinker** [comment]
In general, what UWP API classes' methods "return" when they fail is dependent on the particular [Windows Runtime language projection](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#language-projections) you use in your code that calls those methods. For C++/WinRT and .NET, this means that the methods throw an exception when failing rather than return a value.

(Without projection you would see that UWP API methods' return type is actually always HRESULT; any "return" values are actually returned as output parameters. When UWP API methods fail they return a failing HRESULT; you can read more error information if it's set with [GetRestrictedErrorInfo() and friends](https://stackoverflow.com/questions/40572998/how-to-get-descriptions-for-hresult-error-codes-for-winrt-windows-10-store-cod). Projections normally take care of that for you.)

While I haven't tried this particular method FolderPicker.PickSingleFolderAsync(), like all UWP API methods I imagine it would project the same since its unprojected form is also the same.

**Comment by metathinker** [comment]
I do agree that this could be clarified a bit, perhaps with a link to an old or new page giving general information about UWP API error messaging and handling.

**Comment by hkhmsft** [comment]
Thanks for the explanation, @metathinker. I'll follow up internally and get a work item started to implement this fix into our documentation. Closing this Issue for now. Updates will be posted here in this thread. Similarly, please feel free to follow-up past the close label and treat this as an open thread for follow-ups. Many thanks!
