### ISSUE TITLE
ArgumentException

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#417]
Throws ArgumentException if try to set to PickerLocationId.Unspecified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577a55a9-0d4b-d002-1a77-ea1dbf211e43
* Version Independent ID: 12240525-cee1-5aa5-811a-c7c646b53067
* Content: [FolderPicker.SuggestedStartLocation Property (Windows.Storage.Pickers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker.suggestedstartlocation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.folderpicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.folderpicker.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
