### ISSUE TITLE
No way to override stop

### ISSUE THREAD

**Issue by geoffmmorgan** [MicrosoftDocs/winrt-api#422]
There does not seem to be a way to subscribe to a StopReceived event when using the Xbox Media Remote. The MediaPlaybackCommandManager does not expose this as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bd65481-2cca-13ae-16b5-e38a426370b0
* Version Independent ID: b8b476fb-5e51-7d4c-3674-4f91a118a8a6
* Content: [MediaPlaybackCommandManager Class (Windows.Media.Playback) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybackcommandmanager)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybackcommandmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybackcommandmanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
