### ISSUE TITLE
Apply this Bluetooth low energy API in Python 

### ISSUE THREAD

**Issue by kennyjudo** [MicrosoftDocs/winrt-api#424]
I would like to build a python program, which use the laptop Bluetooth device to communicate to others BLE devices, how can we use this API? where can we find the  "Windows.Devices.Bluetooth.GenericAttributeProfile.dll“ ？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f9e9d6-6609-bd06-d20d-087010de1e60
* Version Independent ID: ca6d38c2-a6ba-0f58-93db-b6963604d152
* Content: [Windows.Devices.Bluetooth.GenericAttributeProfile Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @kennyjudo. Thanks for filing this issue, and my apologies for the delay in responding.

**Windows.Devices.Bluetooth.GenericAttributeProfile** is a Windows Runtime (WinRT) API, so it's accessible from any language for which there's a WinRT language projection, for example C#, Visual Basic, C++/WinRT, JavaScript. I'm unaware of a WinRT language projection for Python, but others might know of one. There's also the [xlang](https://github.com/microsoft/xlang) project, whose purpose is to author/consume APIs in any language on any platform. Other folks might know of non-WinRT libraries that you can use, too.

That's all I can do from the documentation side. I'll leave you with a list of developer support resources, in case it's useful.

- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve
