### ISSUE TITLE
What happens on failure

### ISSUE THREAD

**Issue by psivaram** [MicrosoftDocs/winrt-api#428]
All the API's return values only specify what is returned "When the method completes successfully". But what happens if the API fails? Do they throw an exception? Do they return null? Something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 489416a5-171f-18d0-1233-db017d6b96f5
* Version Independent ID: 8d09363d-5d0f-5355-3e34-4cccf497d6ab
* Content: [WebAuthenticationCoreManager.FindAccountProviderAsync Method (Windows.Security.Authentication.Web.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.core.webauthenticationcoremanager.findaccountproviderasync#Windows_Security_Authentication_Web_Core_WebAuthenticationCoreManager_FindAccountProviderAsync_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.core.webauthenticationcoremanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.core.webauthenticationcoremanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @psivaram, thanks for raising this issue! To the best of my knowledge that language was meant to refer to whether or not the search operation found an item, and not to refer to failures in calling the API itself. A Windows Runtime API should throw an exception only when it is called incorrectly by dev code. That way, you can catch those exceptions during debug/dev time and fix your own code. Exceptions are not, in Windows Runtime APIs, for general error conditions that the app needs to protect against in production (not finding the item you're looking for is a general condition that would and should not result in an exception).

It's the normal pattern for an object returned from a search operation (synchronous or asynchronous) to be non-null if found, otherwise null.

I've updated the wording in these APIs to be a bit clearer, and to talk about the success (or otherwise) of asynchronous search and retrieval operations (whether the key item was found or not) rather than the success of the method itself (which implies exceptions and error codes). I believe the topics are clearer now. My fixes should be live on Monday morning. I'll close this issue now, optimistic that I've done the right thing, but please reopen or reply if you would like.

Thanks!
~Steve
