### ISSUE TITLE
Missing exception name

### ISSUE THREAD

**Issue by LaurentRicci** [MicrosoftDocs/winrt-api#442]
The type of exception being thrown is missing from this description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13879c56-9f47-db7a-916a-02fd13c1a96a
* Version Independent ID: 673df973-430e-e878-2420-4466a3463f5f
* Content: [HttpResponseMessage.EnsureSuccessStatusCode Method (Windows.Web.Http) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.ensuresuccessstatuscode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpresponsemessage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpresponsemessage.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by fabricebauer** [comment]
This is System.Net.Http.HttpRequestException

**Comment by fabricebauer** [comment]
This is when getting 400 Bad Request, there are probably other cases?

**Comment by stevewhims** [comment]
Hi, @LaurentRicci. Thanks for filing this issue, and my apologies for the delay in responding.

I reached out to the feature team for input. We very rarely document exceptions, partly because an exception is nearly always useful only while debugging, and not to be caught in production. Even though this one is a corner case, our advice is this:

The C# projection will only throw System.Exception, so the exact exception isn’t useful. However, the particular HResult will be the bad HResult (for example, a 404 is HTTP_E_STATUS_NOT_FOUND, 0x80190194). Even so, that's not super-useful you because you can just examine the result.StatusCode and get the exact status returned.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
