### ISSUE TITLE
What topic to choose when submitting an incident

### ISSUE THREAD

**Issue by kwiqniss** [MicrosoftDocs/winrt-api#448]
The note here suggests to submit an incident to ask about publishing VPN app in the store. There are several topics to choose from. Which topic should be picked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a47d2c-61a3-01b3-d0dc-73a4b7d5117f
* Version Independent ID: 4c713fb3-f086-5319-cf44-33346a7a14b7
* Content: [Windows.Networking.Vpn Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Vpn)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @kwiqniss, I'm making enquiries about this now, and I'll get back to you when I have an authoritative answer. Meanwhile, since it's possible that the info on that topic is incorrect (I'll fix it if it is), you might want to try the instructions on this topic: https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities. That talks about requesting the restricted capability during Store ingestion. My only concern there is that you'd want to be certain that you were granted the capability if you'd gotten to the point where you were ready to submit the app. And I don't know how certain one could be at that stage regarding the likelihood or otherwise of being granted the capability. As I say, I'll find out and report back when I know more. -Steve

**Comment by stevewhims** [comment]
Btw, I followed the link from the topic you quote to the Windows Developer Support page and then I clicked > Contact us > Windows 10 UWP app development > Submit an incident > Problem type: Runtime platform > Category: Other > Start request. At that stage I needed to provide payment details, and there was no mention of being reimbursed for things like restricted capability requests. Which seems unsatisfactory. More later, when I get an answer.

**Comment by kwiqniss** [comment]
It looks like some options go to SMC where others go to dev center team. I believe you want to choose an option for dev center support, but it's unclear which options go to proper team for the request.

**Comment by stevewhims** [comment]
I see! Just so you know, I'm still actively seeking information and guidance internally here. -Steve

**Comment by stevewhims** [comment]
Hi, @kwiqniss, I have an answer now (sorry for the delay!). Our guidance is to follow the submission process here: https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities. It's even possible to make your request even if your app is not fully deployed, so uploading packages at the time of submission is very likely optional. After your submission is in place, a ticket is open to a team that then reaches out internally for approval. At that point the approver schedules a meeting with you to understand your app, and establish a relationship. The approver also provides you with sample code during that meeting. I hope that helps! :) Meanwhile I'll fix up any documentation that gives the wrong guidance. ~Steve

**Comment by stevewhims** [comment]
Just an update. I've fixed any docs that I'm aware of that give incorrect guidance around capabilities (whether restricted, custom, or other). So I'll go ahead and close this issue for now, but please let me know if the docs need further corrections.

~Steve
