### ISSUE TITLE
VoipPhoneCall.NotifyCallAccepted: Remarks section seems incorrect

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#468]
The remarks section mentions that after the `AnswerRequested` event is raised, you must call `NotifyCallActive` within 5 seconds. It doesn't talk about `NotifyCallAccepted` anywhere which is what this page is supposed to be about.

What APIs is `NotifyCallAccepted` relevant to? `RequestNewIncomingCall`? `SetupNewAcceptedCall`? It would be helpful to mention this and link to the relevant APIs. Currently, it's difficult for me to understand when to use `NotifyCallAccepted`.

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2fd832-8fd7-7535-c747-efb73729f20b
* Version Independent ID: 803878e5-017c-4213-0426-8ec436601970
* Content: [VoipPhoneCall.NotifyCallAccepted(VoipPhoneCallMedia) Method (Windows.ApplicationModel.Calls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.voipphonecall.notifycallaccepted)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.voipphonecall.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.voipphonecall.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @rigdern, thanks for pointing this out (and my apologies for the really long time it took to respond). The fixes should be visible on the live site tomorrow. Meanwhile, here's some content that I added that should provide clarity.

VoipCallCoordinator.RequestNewAppInitiatedCall requests a new call object from the system. Call this method from your VoIP app to tell the system that there's a new incoming call, and that you want to host an incoming call notification for that new call. Use the method to create a new VoipPhoneCall object. You can use a VoipPhoneCall object to send in-app call notifications, and to handle events that the VoipPhoneCall raises.

VoipPhoneCall. Call the VoipCallCoordinator.RequestNewAppInitiatedCall method to create a new VoipPhoneCall object. You can then use the VoipPhoneCall object to set up a new in-app call notification, and to handle events that the VoipPhoneCall raises.

If the user accepts the call, then your application should call NotifyCallAccepted. If the call is rejected or unanswered, then call NotifyCallEnded. Alternatively, the system itself can raise the AnswerRequested or RejectRequested events, and your VoIP application can handle those events in order to determine whether the user has accepted or rejected the incoming call via the HID device.

The system raises the AnswerRequested event to signal to your VoIP application that the call has been accepted by the system. After the event is raised, your VoIP application must call NotifyCallActive within 5 seconds.

The system raises the RejectRequested event to signal to your VoIP application that the call has been rejected. After this event is raised, your VoIP application must call NotifyCallEnded within 5 seconds.

~Steve
