### ISSUE TITLE
IgnorableServerCertificateErrors not found

### ISSUE THREAD

**Issue by zhangalex** [MicrosoftDocs/winrt-api#469]
Why IgnorableServerCertificateErrors not found?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf0b53f-254c-c214-6b27-b4963818d4f0
* Version Independent ID: dbdce349-b9a6-888a-85e3-b12f5cae43fb
* Content: [IWebSocketControl2.IgnorableServerCertificateErrors Property (Windows.Networking.Sockets) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.iwebsocketcontrol2.ignorableservercertificateerrors)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.sockets.iwebsocketcontrol2.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.sockets.iwebsocketcontrol2.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @zhangalex! Yes, I see the problem here: the code example is incorrect. Instead of accessing myWebSocket.Information.IgnorableServerCertificateErrors, the code SHOULD be accessing myWebSocket.Control.IgnorableServerCertificateErrors. So, "Control" instead of "Information". If you change that, then that will unblock you. In the meantime, I have submitted a fix to the master branch and the code example will be correct on the live site within the next 24 hours. Thank you for bringing this error to my attention! :) ~Steve

**Comment by zhangalex** [comment]
Thanks Steve.
