### ISSUE TITLE
UI.Composition sample throws exceptions.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#473]
I can't find the GitHub for the particular sample, but it's the simplest sample that creates sprites when I click and allows me to move them around, it doesn't change their shape like the other sample I've seen. When I run it, it commonly throws exceptions ..

Exception thrown at 0xAC4ADC9A in Application.exe: 0xC0000008: An invalid handle was specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 336b0c74-9252-5ace-6583-58e178aa3448
* Version Independent ID: 8d4767a4-9b41-1ec6-1e2f-60953a4932ea
* Content: [Windows.UI.Composition Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. It's difficult to assess what might be going on with your app without a link to the specific sample your referring to. I believe that this sample has behavior similar to what you are describing: 

https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/CompositionVisual/cs

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
