### ISSUE TITLE
StorageFile.OpenReadAsync does not document exceptions

### ISSUE THREAD

**Issue by benjamin-bader** [MicrosoftDocs/winrt-api#482]
What exceptions can we expect, and under what conditions?  That would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f083107-b5b1-c02c-a5d5-0816a708b760
* Version Independent ID: 8429f58a-dc60-35b5-3d45-f8bfe1bd5799
* Content: [StorageFile.OpenReadAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.openreadasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content based on [this other thread](https://github.com/MicrosoftDocs/winrt-api/issues/576). The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
