### ISSUE TITLE
Persistance guarantee

### ISSUE THREAD

**Issue by mdmarin** [MicrosoftDocs/winrt-api#501]
Once this API returns, is it guaranteed the changes have been persisted to disk?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91b92c2-9add-bf02-9bba-52e3627c5e65
* Version Independent ID: 23a9f0db-1f2c-ced8-712a-aab6fc560de7
* Content: [ApplicationDataContainer.DeleteContainer(String) Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdatacontainer.deletecontainer#Windows_Storage_ApplicationDataContainer_DeleteContainer_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdatacontainer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdatacontainer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
