### ISSUE TITLE
Issue: Zero value returned ... unless the brightness is changed with SetBrightnessLevel

### ISSUE THREAD

**Issue by loulouMS** [MicrosoftDocs/winrt-api#514]
I can modify the brightness level and then get its new right value. But if I don't change it, a value equal to zero is returned by BrighnessLevel property !
In addition, an error comes up when getting (only read) the system brightness level even with the SystemManagement capability.
It seems that these issues didn't exist before the last version of Windows (1803).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb00e107-4d15-4d52-44c5-21a4751a1824
* Version Independent ID: e5cff65f-4c9b-93ae-8ff6-815580e7e505
* Content: [BrightnessOverride.BrightnessLevel Property (Windows.Graphics.Display) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride.brightnesslevel#Windows_Graphics_Display_BrightnessOverride_BrightnessLevel)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by loulouMS** [comment]
By chance, I have another tablet with the version 1709 of Windows. I made the same test with it and I do get the right value of the brightness level after using GetForCurrentView. With the version 1803, the returned value is equal to zero as mentionned in the initial post.
In both cases (both versions), getting the value after using GetDefaultForSystem returns an error.

**Comment by mtoepke** [comment]
Hi @loulouMS, thanks for your question.

BrightnessOverride is intended only for setting and then temporarily overriding the brightness level, not for querying or retrieving the current brightness level.  The BrightnessLevel property just returns the level specifically set on that particular BrightnessOverride instance (by a previous call to SetBrightnessLevel).

The behavior you were seeing prior to version 1803 was unintentional and has been updated.

Call GetLevelForScenario to determine the brightness level for specific user scenarios.

**Comment by loulouMS** [comment]
Hi @mtoepke, thanks for the information.
But the problem is ... : how to know which scenario is currently active?

And what is the purpose of GetDefaultForSystem method? I remain that it always returns an error even if we add the SystemManagement capability.

**Comment by loulouMS** [comment]
Could you reply to my 2 last questions?

**Comment by mtoepke** [comment]
Hi @loulouMS , thanks for your questions.

These functions are for setting the brightness level, not querying it.  According to the developer, there are no UWP APIs that return the current screen brightness.

You do not know which scenario is currently active unless you're app has overridden the brightness itself.  I mentioned GetLevelForScenario as a way to determine the brightness level to set, in your own app, based on your app's current scenario.

GetDefaultForSystem does not return the system's brightness.  It returns a BrightnessOverride instance that still requires you to set the brightness on the BrightnessOverride before using the BrightnessLevel property to check the value that you have set.  GetDefaultForSystem is the same as GetForCurrentView, except it is used for background IoT apps that don't have a CoreWindow.

I'm also seeing a failure return code (E_FAIL) calling GetDefaultForSystem.  It turns out that call also requires enabling Embedded Mode, which is only supported in IoT.  UWP apps have a CoreWindow, so should use GetForCurrentView instead.  We'll add that to the docs.

If you're working on an IoT app, see https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/embeddedmode for info on embedded mode.

Thanks,
-Mike

**Comment by wolfgangschneider** [comment]
Hi
We have following Use case: 
We are developing an Tablet Kiosk App (Assigned access). The user needs the ability to change the brightness, therefor we add an Slider control to change the brightness. How can I set the slider  initial value , to the current brightness. (It worked proper bevor 1803)
