### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by ChozoMaster** [MicrosoftDocs/winrt-api#515]
When I try to call the method on HoloLens I get a NotImplementedException thrown at the call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8441bf24-e52b-ed00-4e78-4a001c3cfe84
* Version Independent ID: ff73d090-7389-8e5b-744b-5c828f2b884d
* Content: [HolographicSpace.WaitForNextFrameReady Method (Windows.Graphics.Holographic) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicspace.waitfornextframeready#Windows_Graphics_Holographic_HolographicSpace_WaitForNextFrameReady)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicspace.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicspace.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by beteitle** [comment]
This method is now enabled for 1809

**Comment by OlrikSato7** [comment]
I get this same exception when I simply run the BasicHologram windows sample.

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
