### ISSUE TITLE
Which of the methods are static methods vs. instance methods?

### ISSUE THREAD

**Issue by MS-DaveH** [MicrosoftDocs/winrt-api#517]
We should call out if method's / properties are static or instance methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09243f27-7f60-4778-3815-5706b797e70d
* Version Independent ID: 0091221e-6f25-c5ae-6620-9fae55ca537b
* Content: [BrightnessOverride Class (Windows.Graphics.Display) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @MS-DaveH, and apologies for the long delay in responding to this issue. The `static` keyword is present in the syntax block at the top of the topic for static methods, and is absent for instance methods. For example, `public static BrightnessOverride GetDefaultForSystem();`.

-Steve

**Comment by kwiqniss** [comment]
Hi Steve,
The only part of the page that mentions static is at the top, there's 3 instances of the word static, and none of them indicate which methods are static. To quote, "Overrides the screen brightness level setting on a device. This API provides the ability to have per-application brightness control on devices that support controllable brightness. Use the BrightnessOverride object to override the user's brightness level setting temporarily or permanently.

[Windows.Foundation.Metadata.ContractVersion(typeof(Windows.Foundation.UniversalApiContract), 262144)]
[Windows.Foundation.Metadata.MarshalingBehavior(Windows.Foundation.Metadata.MarshalingType.Agile)]
[Windows.Foundation.Metadata.Static(typeof(Windows.Graphics.Display.IBrightnessOverrideStatics), 262144, "Windows.Foundation.UniversalApiContract")]
[Windows.Foundation.Metadata.Threading(Windows.Foundation.Metadata.ThreadingModel.Both)]
public sealed class BrightnessOverride
Inheritance
Object
BrightnessOverride
Attributes
ContractVersionAttribute MarshalingBehaviorAttribute StaticAttribute ThreadingAttribute"

**Comment by stevewhims** [comment]
Hi, @kwiqniss. So, yes, you're quoting content from the "BrightnessOverride class" topic. The class topic doesn't say anything about its methods; instead we leave details about methods to the method topics. So, for example, if you look at the "BrightnessOverride.GetDefaultForSystem method" topic and look in the syntax block for C#, it says `public static BrightnessOverride GetDefaultForSystem();`, so that's the indication that that method is static. For the "BrightnessOverride.GetLevelForScenario(DisplayBrightnessScenario) method" topic, the syntax block for C# says `public double GetLevelForScenario(DisplayBrightnessScenario scenario);`, so that's not a static method.

I'll go ahead and close the issue but you can continue commenting here, or ping me internally (you have my alias on that other thread we had about BrightnessOverride).

-Steve
