### ISSUE TITLE
How to add handler for Complete?

### ISSUE THREAD

**Issue by adigostin** [MicrosoftDocs/winrt-api#523]
Since there's heavy template voodoo around this type that confuses humans as well as your Intellisense, would you care to provide an example of adding a handler for the Complete event? Thank you.
(later edit: that's C++)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488677fc-ecca-cd81-4913-d3a8865dab9d
* Version Independent ID: e84e1eb8-09b4-b5d9-46b3-5fe695759827
* Content: [IAsyncAction Interface (Windows.Foundation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IAsyncAction#Windows_Foundation_IAsyncAction_Completed)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncaction.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncaction.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @adigostin. Yes, I've updated the docs so that the Completed member topics all link to the part of the C++/WinRT content that shows how to do this in code. You can see an example of that link here: https://docs.microsoft.com/uwp/api/windows.foundation.iasyncaction.completed#examples.

And the link goes to [Delegate types for asynchronous actions and operations](/windows/uwp/cpp-and-winrt-apis/handle-events#delegate-types-for-asynchronous-actions-and-operations).

Hope that helps!
~Steve
