### ISSUE TITLE
What value or unit of measurement does this property use?

### ISSUE THREAD

**Issue by tywals** [MicrosoftDocs/winrt-api#544]
Does this take in an offset in terms of pixels? percentage? inches?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd80d99-cd21-9f26-6c01-38e05b423e18
* Version Independent ID: 073b4d81-8716-4703-5fa4-85e70ca4f298
* Content: [Visual.Offset Property (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.visual.offset#Windows_UI_Composition_Visual_Offset)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.visual.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.visual.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. Unless specified otherwise, measurements in WinRT APIs are in [effective pixels](https://docs.microsoft.com/windows/uwp/design/basics/design-and-ui-intro). We'll take this as feedback that the docs could be more clear about this.

(This feedback channel is focused on doc issues. For questions that might be time-sensitive, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question).
