### ISSUE TITLE
What unit of measurement does this property use?

### ISSUE THREAD

**Issue by tywals** [MicrosoftDocs/winrt-api#545]
is this in terms of pixels?

 ie. visual.Size = new Vector2(50, 50); is that 50 pixels wide by 50 pixels tall? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa5430-8227-f8f7-29da-4d2943609ff3
* Version Independent ID: 934554ff-4da1-3073-28fc-99d31d37986a
* Content: [Visual.Size Property (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.visual.size)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.visual.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.visual.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. Unless specified otherwise, measurements in WinRT APIs are in [effective pixels](https://docs.microsoft.com/windows/uwp/design/basics/design-and-ui-intro). We'll take this as feedback that the docs could be more clear about this.

(This feedback channel is focused on doc issues. For questions that might be time-sensitive, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question).
