### ISSUE TITLE
The default encoding isn't really specified

### ISSUE THREAD

**Issue by pedasmith** [MicrosoftDocs/winrt-api#550]
The simpler format -- without an encoding -- says that the encoding will be automatically detected based on byte order marks or "as specified by the encoding". But that's no possible; what if I'm writing a file for the first time? What's the preferred encoding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2be794-a63c-0875-c610-dcb41bd3dae2
* Version Independent ID: 60582cba-1c92-4b1e-1766-4724e441bce3
* Content: [PathIO.WriteTextAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pathio.writetextasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.PathIO.WriteTextAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pathio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pathio.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Hi @pedasmith , thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a PR with changes you'd like to see.

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
