### ISSUE TITLE
Pre-release or Released API?

### ISSUE THREAD

**Issue by HollyAM** [MicrosoftDocs/winrt-api#571]
The class definition description implies that some or all of these APIs are pre-release or for Xbox only. It's unclear to me if that includes this method...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a25fdbf-c4d2-c4f3-fdf7-770efa7721b4
* Version Independent ID: 34e0a66c-2cc0-64d6-3887-3d581ff800a1
* Content: [ChatCapabilitiesManager.GetCapabilitiesFromNetworkAsync(String) Method (Windows.ApplicationModel.Chat) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.chat.chatcapabilitiesmanager.getcapabilitiesfromnetworkasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.chat.chatcapabilitiesmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.chat.chatcapabilitiesmanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
