### ISSUE TITLE
I don't think the "Read" methods read from the stream, they read from the loaded buffer

### ISSUE THREAD

**Issue by MrAntix** [MicrosoftDocs/winrt-api#590]
documentation says "Reads a 16-bit integer value from the input stream." for example
please can you confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61bf27d-d169-da09-5c90-25a4448488a4
* Version Independent ID: ccc5fdef-a25a-6eba-5a91-64d1eae4484c
* Content: [DataReader Class (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
