### ISSUE TITLE
May we have more detail?

### ISSUE THREAD

**Issue by MrAntix** [MicrosoftDocs/winrt-api#592]
Does this lock the file?
Can other streams be created on the same file while this result is open?
Is this the recommended way for readonly access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56720d7-edbd-6626-cdf4-8a3d04331942
* Version Independent ID: 040f0622-c4d4-2230-f7a6-175c93435c55
* Content: [IInputStreamReference.OpenSequentialReadAsync Method (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.iinputstreamreference.opensequentialreadasync#Windows_Storage_Streams_IInputStreamReference_OpenSequentialReadAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.iinputstreamreference.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.iinputstreamreference.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
