### ISSUE TITLE
PivotHeaderFocusVisualPlacement Notworking

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/winrt-api#594]
I've tried set HeaderFocusVisualPlacement of Pivot to SelectedItemHeader. 
- Expected: The header item will be focused every time it's selected
- Actual: One box looks like focused one appear on the first header item. Every time I change the selected pivotheaderitem, The focus box always appear on the first one, does not change the position

Tested on Xbox one, Windows 10 - 10.0.17134.4071, rs4_release_xbox_dev_1806...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29939cb-bab6-f490-b432-652ae7aedf89
* Version Independent ID: 8cfc09f5-b19a-872d-e7e1-d9bf976f2882
* Content: [Pivot.HeaderFocusVisualPlacement Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.pivot.headerfocusvisualplacement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.pivot.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.pivot.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question. 

To engage with the XAML product team or file a product bug, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.
