### ISSUE TITLE
On the tree left pane, the events section of Slider is missing

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/winrt-api#607]
You can see in the following screenshot that "> Events" is missing. There is a "SnapPointsType" that should be inside Properties.

![slider](https://user-images.githubusercontent.com/1608424/45359312-267b3580-b59a-11e8-9ec0-e5d69a64788d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f6d9d8-2160-1320-a6c1-d62fdf6605ab
* Version Independent ID: c810f65e-4fcc-0299-403e-7c57fd0e8e19
* Content: [Slider Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.slider)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.slider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.slider.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi @ArchieCoder, Thanks for taking the time to provide feedback. This is by design. The left tree navigation shows only the direct child members of a class - inherited members are shown only in the members table in the page, not in the tree view. . All the events on Slider are inherited, so they aren't shown in the tree.

SnapPointsType is an enumeration that is not related to Slider. It's a peer of Slider in the tree. As you can also see with SplitViewDisplayMode, enumerations don't have any child pages, so the chevron is not shown for them.
