### ISSUE TITLE
Should be ImageBrush not Image for UWP

### ISSUE THREAD

**Issue by blanthor** [MicrosoftDocs/winrt-api#608]
I found the code provided to fail, because of type. This worked for me:
            ImageBrush img = sender as ImageBrush; //should be ImageBrush not Image
            var uri = new System.Uri("ms-appx:///images/fallback.png");

            img.ImageSource = new BitmapImage(uri);  //should be ImageBrush.ImageSource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49fe0ee-2d38-a76a-530f-e7d15406f092
* Version Independent ID: 8a7ff98b-f711-ac6d-af72-750531ac964b
* Content: [Image.ImageFailed Event (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.imagefailed)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi @blanthor, Thanks for the feedback. If you found _sender_ to be of Type ImageBrush, that indicates that you were handling the [ImageBrush.ImageFailed](https://docs.microsoft.com/uwp/api/windows.ui.xaml.media.imagebrush.imagefailed) event rather than the [Image.ImageFailed](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.image.imagefailed) event. The events are identical except for the Type. The example code is correct for the Image.ImageFailed event, which is the context in which it is shown.
