### ISSUE TITLE
How Secure is the interaction between Webviews and the Xamarin app?

### ISSUE THREAD

**Issue by ali-h2010** [MicrosoftDocs/winrt-api#610]
How secure it's to return data from webview to c#? Can the data be sniffed or an attacker use MITM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1e6f48-d57c-65c1-9f05-1d76db94294f
* Version Independent ID: d69a866b-7f25-5543-6fa2-fbf9b830548b
* Content: [WebView Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview#interacting-with-webview-content)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question. 

To engage with the XAML product team or file a product bug, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.
