### ISSUE TITLE
Do these APIs throw exceptions?

### ISSUE THREAD

**Issue by SamHarrell** [MicrosoftDocs/winrt-api#620]
Through trial and crash, I have found that some of these APIs throw exceptions but I do not see them listed here in the documentation so that I could be more defensive in my programming to provide a better user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c05725-e5f0-32cf-5083-28ef23e0eed0
* Version Independent ID: 1850e51e-dba6-1b48-360f-5928aaad2153
* Content: [WebAuthenticationCoreManager Class (Windows.Security.Authentication.Web.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.core.webauthenticationcoremanager)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.core.webauthenticationcoremanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.core.webauthenticationcoremanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @SamHarrell, thanks for filing this issue. Generally speaking, Windows Runtime APIs are designed not to throw exceptions of the kind that we expect deployed code to handle at runtime. That's why the docs are not in the habit of mentioning them. However, there are some cases where that rule is not followed. So, I'll pass along your findings to the product team and I'll respond to their guidance whether/what to document here regarding exceptions.

On the other hand, it is possible for a Windows Runtime API to return an unsuccessful HRESULT across the application binary interface (ABI) if, for example, the API is passed an invalid argument. And some language projections will turn that into an exception. The remedy there is to find that issue at debug time and change the code so that the API's preconditions are met.

Thanks again!
~Steve

**Comment by stevewhims** [comment]
I have an update, @SamHarrell. The product group has confirmed that these APIs don't throw exceptions. But they do return a failed HRESULT value when the API fails. However, our partners haven’t seen that.

No changes are needed to the documentation. But you have some options if you wish to pursue the matter of any API failures that you are seeing (which would be unexpected). There's the [Windows developer feedback site](https://wpdev.uservoice.com) (to file a product bug). There's [Visual Studio User Voice](https://visualstudio.uservoice.com), the [Developer Community](https://developercommunity.visualstudio.com), and for issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus).

~Steve
