### ISSUE TITLE
Show Axis Layout

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/winrt-api#625]
You need to show an axis layout for this (is +Z up or is it in the front for example) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 903e424e-1b58-e98e-7f5c-d7a5cfe94338
* Version Independent ID: 0e21fe74-1551-669a-74b9-6c2cf642d809
* Content: [AudioNodeEmitter.Position Property (Windows.Media.Audio) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.audio.audionodeemitter.position)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audionodeemitter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audionodeemitter.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. This page has been updated with the following remark:

The positions of all of the emitters in the graph are relative to the position and orientation of the **AudioNodeListener** object assigned to the **AudioDeviceOutputNode** for the audio graph. By default, the listener is located at the origin (0,0,0) facing forward along the Z axis, but you can set it's position and orientation with the **Position** and **Orientation** properties.
