### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by w-Yuan** [MicrosoftDocs/winrt-api#627]
Hi,
I have a quick question. when is this current reading about?
Here is an example. I press Button 'A', and then after one minute i call this method. Will it return 'A' or nothing?
The other equivalent question is that, how to flush this state, or how long will the state last?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95d90aa-f16c-9e3a-89b9-b114a88d2fca
* Version Independent ID: 5757580f-c6e1-0989-29eb-3f650e5c840b
* Content: [Gamepad.GetCurrentReading Method (Windows.Gaming.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad.getcurrentreading)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.gamepad.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.gamepad.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @w-Yuan, this method gets the state of the gamepad at the moment you call it. So in your example, if you press the A button, then release the A button, and then later call **GetCurrentReading**, it will return that the A button is not currently pressed.

For your second question, there is no need to "flush the state" because the state of the gamepad is updated automatically. This method just returns a snapshot of the current state. Does that make sense?
