### ISSUE TITLE
RangesDownloaded & GetDownloadedRanges()

### ISSUE THREAD

**Issue by omansak** [MicrosoftDocs/winrt-api#630]
Why Microsoft.NETCore.UniversalWindowsPlatform 6.1.7 does not have RangesDownloaded & GetDownloadedRanges()?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a23550-5126-e2b0-f2a0-0aa4da29bcc8
* Version Independent ID: 07e6eec6-10e2-09e0-abbb-1a338a25a5bb
* Content: [DownloadOperation Class (Windows.Networking.BackgroundTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.downloadoperation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.downloadoperation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.downloadoperation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @omansak, thanks for filing this issue. I've started investigating, and I'll get back to you when I have more information.

~Steve

**Comment by stevewhims** [comment]
Sorry about the delay in responding, @omansak. I don't have any progress to report, but I haven't forgotten about the issue. ~Steve

**Comment by omansak** [comment]
@stevewhims Thank you for investigating. I waiting

**Comment by stevewhims** [comment]
Hi, @omansak, again I apologize for the delay in getting info to you. Here's some info from the product team, which I hope will help.

Proposed solution: set the app’s Target Version to be at least the Windows 10 Fall Creators update (build 16299).

I can only reproduce the issue in one way: by setting the program’s properties>Application>Targeting Target Version to something less than the Windows 10 Fall Creators Update (Build 16299). Otherwise, it works correctly for me.

Original question: was “Why Microsoft.NETCore.UniversalWindowsPlatform 6.1.7 does not have RangesDownloaded & GetDownloadedRanges()?”

Some background: The NETCore.UniversalWindowsPlatform package is an “wrapper” so that .NET Core UWP applications can use the UWP set of APIs that are part of Windows and the Windows SDK. Different versions are made as the set of available APIs to a user’s program depends on the project target version (but not the min version).

The Ranges was added in the Fall Creators Update last year. 

If you build an app with a target of at least the Fall Creators update and a lower min version, the app will compile but any attempt to use the new APIs will not work.

**Comment by omansak** [comment]
@stevewhims Thank you so much , this infos help to me

edit : Do i need to change "Targeting  Min" version ?

**Comment by stevewhims** [comment]
Based on the info in the product team's reply, it looks like you're not supposed to set the min version lower than the Fall Creators update.
