### ISSUE TITLE
About the Flyout

### ISSUE THREAD

**Issue by Leisvan** [MicrosoftDocs/winrt-api#638]
In the latest Windows 10 update (1809) the RichEditBox shows a flyout (with rich text modifiers such as Bold or Italic) when the user selects some text. That happens even if the app isn't targeting the SDK for that version of Windows. In my case, I use a RichEditBox to manage plain text and this completely ruins the UX in my app. I would be very happy if that behavior would be switch off by default. In any case, do you have any solution for this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a85389d-c2c4-0af2-2422-2c7097cc8b60
* Version Independent ID: d5c572a5-96b9-398e-a03b-e75bea6d54b8
* Content: [RichEditBox Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.RichEditBox)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.richeditbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.richeditbox.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi @Leisvan, the information you're looking for is on the new [Command bar flyout](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/command-bar-flyout#command-bar-flyouts-for-text-controls) page. (We still need to add a link there from the RichEditBox page.)

- ... If you set SelectionFlyout to null, no commands are shown on selection.
- ... If you set ContextFlyout to null, the menu flyout shown in previous versions of the text control is shown instead of the TextCommandBarFlyout.

```
<RichEditBox ContextFlyout="{x:Null}" SelectionFlyout="{x:Null}"/>
```

If you're targeting earlier versions of the SDK, you'll need to use one of the techniques described in [Version adaptive apps](https://docs.microsoft.com/windows/uwp/debug-test-perf/version-adaptive-apps) to set these properties.

**Comment by Leisvan** [comment]
> ... If you set ContextFlyout to null, the menu flyout shown in previous versions of the text control is shown instead of the TextCommandBarFlyout.

I'm targeting SDK Build 17134 (April 2018 Update) as October Update has not yet been release (as far as I know). In my app, I can't access "SelectionFlyout" in a RichEditBox. When I set "ContextFlyout" to null nothing changes. The RichEditBox still shows the Flyout over the selection.
It seems that targeting the latest SDK and change the "SelectionFlyout" property to null is the only way to address this issue. Until the new SDK is released my app is ruined.

**Comment by jwmsft** [comment]
The latest SDK was released on Oct 2. There is more info in the [announcement blog post](https://blogs.windows.com/buildingapps/2018/10/02/start-developing-on-windows-10-october-2018-update-today/#5KIFlUr1YXszmMtV.97) and you can [download it from the dev center](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk).

**Comment by Leisvan** [comment]
Thanks. In that case I think my solution is simple. Target the latest version and change the property in the RichEditBox. Thanks for your answers.
