### ISSUE TITLE
The DisplayName field can't possibly be the device's Bluetooth name

### ISSUE THREAD

**Issue by bviglietta** [MicrosoftDocs/winrt-api#657]
The DisplayName field can't possibly be the device's Bluetooth name. In addition to making zero sense, it would mean that all apps on one device have the same display name. It would mean that the same app on different devices would have different display names. Please double-check this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daedbc71-216f-4a3f-ca88-cdfba53c3b4c
* Version Independent ID: 42296027-66b2-6c72-40d4-e20a38aa11d7
* Content: [RemoteSystemApp Class (Windows.System.RemoteSystems) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.remotesystems.remotesystemapp)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.remotesystems.remotesystemapp.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.remotesystems.remotesystemapp.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
