### ISSUE TITLE
CreateStrokeFromInkPoints

### ISSUE THREAD

**Issue by Ponant** [MicrosoftDocs/winrt-api#66]
Hi, the docs say there is a method to create strokes from inkpoints which accepts date time as parameters, however no method seems to exist, is that expected or when will this be available?
[https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.input.inking/inkstrokebuilder_createstrokefrominkpoints_2009821049.md](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.input.inking/inkstrokebuilder_createstrokefrominkpoints_2009821049.md)

**Comment by mattwojo** [comment]
Hi @Ponant -- Looks like these parameters get pulled in via rendering on the live site doc page, here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkstrokebuilder#Windows_UI_Input_Inking_InkStrokeBuilder_CreateStrokeFromInkPoints_Windows_Foundation_Collections_IIterable_Windows_UI_Input_Inking_InkPoint__Windows_Foundation_Numerics_Matrix3x2_Windows_Foundation_IReference_Windows_Foundation_DateTime__Windows_Foundation_IReference_Windows_Foundation_TimeSpan__

Please let me know if this addresses your issue and I can close this out. 
Thanks! ~Matt

**Comment by Ponant** [comment]
Hi @mattwojo ,
I have only one method `CreateStrokeFromInkPoints`, and it does not allow  for those 2 parameters `IReference<DateTime> strokeStartedTime, IReference<TimeSpan> strokeDuration`. Indeed, the docs say it is a "pre-release", but I cannot access this extension from a uwp app. So, does this method exist, and if so where can I find it  (Nuget?)?.
Thanks

**Comment by mattwojo** [comment]
Hey @Ponant -- Just confirmed that you need to sign up to be a Windows insider and then download the Preview SDK from [developer section on Windows Insider](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) in order to get access to this API. 

The details of the last flight of the OS/SDK are described in this blog: https://blogs.windows.com/buildingapps/2017/03/14/windows-10-sdk-preview-build-15052-released/#wch3XeeZHLvxmGqM.97.

(I don't believe there's currently a way to get this via Nuget)

If you're not already an Insider, but want to take a crack at it, let me know if you get stuck. 
~Matt

**Comment by Ponant** [comment]
@mattwojo , thanks a lot! I think I am already an insider but will check this out again and will let you know if any problems appear. Cheers

**Comment by Ponant** [comment]
@mattwojo , thanks for your help, your insight should be enough. Cheers
