### ISSUE TITLE
No ContainsKey found

### ISSUE THREAD

**Issue by cartwrightluke** [MicrosoftDocs/winrt-api#670]
The inherited methods decribed here are confusingly notated and don't seem to work. I assume that the TKey in ContainsKey is a Platform::String, but I had no success using it.
 error C2039: 'ContainsKey': is not a member of 'Windows::Data::Json::JsonObject'
HasKey(Platform::String) works as expected though, and has the expected interface. It might be better to exclude the inherited types here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03039e6a-a921-e626-1b14-f47f77d0bf89
* Version Independent ID: bf078dda-9c10-4686-6d50-212d359b7a31
* Content: [JsonObject Class (Windows.Data.Json) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.json.jsonobject.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.json.jsonobject.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. It looks like you're using C++, in which case it is by design that you can call the HasKey method of the JsonObject class but not ContainsKey. I believe you commented on an older version of our docs that showed the ContainsKey method. Please see the remarks in the [HasKey](https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject.haskey) article.
