### ISSUE TITLE
About Custom Flyouts

### ISSUE THREAD

**Issue by Leisvan** [MicrosoftDocs/winrt-api#672]
In my app I need to remove the default SelectionFlyout  value because I want to present only plain text in my RichEditBox control. Although, this new property gives me lots of possibilities.
I wanted to create my own Flyout and I did. The problem is that my flyout doesn't shows properly when in certain situations like when a word that is next to the edges of the app.
I can't add images here so I can't give you visual references but the issue is simple to reproduce.

1. Add a RichEditBox full width in a page
2. Add a CommandBarFlyout to the SelectionFlyout property
3. Add some AppBarButton to the CommandBarFlyout.PrimaryCommands property

Now, when you select some text in the corners of the RichEditBox, the Commands Bar shown is partially visible.
I hope you understand my explanation
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8421dc8-3bb6-d61a-6c4e-f5cc6ad59fee
* Version Independent ID: 95f12fe2-b8c5-508b-8e7d-3510ce907130
* Content: [RichEditBox.SelectionFlyout Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.richeditbox.selectionflyout)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.richeditbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.richeditbox.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question. 

To engage with the XAML product team or file a product bug, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.
