### ISSUE TITLE
Is there range of the MediaPlayer.Volume Property?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#676]
Is there range of the MediaPlayer.Volume Property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1a2290-1c59-0a16-e70e-abf6e0222803
* Version Independent ID: a18520e9-609f-21f5-e29e-cac7faf00820
* Content: [MediaPlayer.Volume Property (Windows.Media.Playback) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.volume)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stefangavrilasengage** [comment]
@moyanming if you are asking about the range (min,max) then Minimum is 0 and Maximum is 1...

**Comment by edwiness10** [comment]
If it is a value outside 0 to 1, give an exception.

**Comment by drewbatgit** [comment]
I have updated the documentation to reflect that the allowed range for this property is 0 to 1. The change should be visible on the live site in ~24 hours.

I did make a quick sample app to test the behavior of this property and, in my tests, setting a value outside of this range did not result in an exception, but did result in the value being clamped to within the range (a negative value was reset to 1). For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
