### ISSUE TITLE
Why the MediaPlayer.Volume property can't assign to a double variable?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#677]
Hi all,
I can change the MediaPlayer.Volume successfully, but why there is an exception when assign this Volume property to a double variable?
Best regards.

System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.

![qq 20181022202842](https://user-images.githubusercontent.com/13234209/47292393-5efe3c80-d639-11e8-83fc-b45d8c4bc7d6.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1a2290-1c59-0a16-e70e-abf6e0222803
* Version Independent ID: a18520e9-609f-21f5-e29e-cac7faf00820
* Content: [MediaPlayer.Volume Property (Windows.Media.Playback) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.volume)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by edwiness10** [comment]
This error is due to thread coupling. Because the player works in another thread.

**Comment by drewbatgit** [comment]
Issues in this repo are intended specifically for issues with the documentation. I recommend consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.

That said, I made a quick test app and added the lines of code you show to the OnNavigatedTo event handler of the default page template, and the lines executed without throwing an exception. It sounds like edwiness10's comment is likely correct. You could try making the call on the UI thread using the [CoreDispatcher.RunAsync](https://docs.microsoft.com/uwp/api/windows.ui.core.coredispatcher.runasync) method.
