### ISSUE TITLE
Enumerations no longer display their numeric values

### ISSUE THREAD

**Issue by peterfoot** [MicrosoftDocs/winrt-api#7]
In the old documentation you could view the numeric values for each member but now this information is not displayed. The values are present in the raw markdown content.

**Comment by mattwojo** [comment]
Adding issue https://github.com/MicrosoftDocs/winrt-api/issues/70 filed by @martinsuchan to this thread....

I was just reading this page:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher
and I noticed, that in all places where a specific CoreDispatcherPriority enum value is used, the actual value is not shown in the article, only the type. Because of this issue lots of parts of the text does not make any sense:
image
It's possible this issue with enum values is on much more MSDN pages.

**Comment by kevinyr** [comment]
We are working to resolve this issue.

**Comment by kevinyr** [comment]
No update to report here.  Still in the queue.

**Comment by jwmsft** [comment]
This issue is fixed in the docs.
