### ISSUE TITLE
How can I Config the wireless frequency channel to 5Ghz or 2.4Ghz？

### ISSUE THREAD

**Issue by Thxzzzzz** [MicrosoftDocs/winrt-api#753]
I have seen the selection in Windows 10 Settings , but I can only config the Ssid and Passphrase in this Api ,witch api can config the frequency channel ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e23f3be-25ae-6bf1-62f4-ce28271f7c10
* Version Independent ID: b92e0055-df10-3245-5f9a-3dc9e351139e
* Content: [NetworkOperatorTetheringAccessPointConfiguration Class (Windows.Networking.NetworkOperators) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.NetworkOperators.NetworkOperatorTetheringAccessPointConfiguration)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.networkoperators.networkoperatortetheringaccesspointconfiguration.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.networkoperators.networkoperatortetheringaccesspointconfiguration.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @Thxzzzzz, thanks for raising this issue. I'm working with the product team to see whether we can get you a response. I'll get back to you with any progress. ~Steve

**Comment by stevewhims** [comment]
Would this be a feasible workaround? Append the frequency to the name of your SSID (5Ghz or 2.4Ghz, depending what it's set to). For example, you could name an SSID : MyExampleWiFiSSID_5Ghz.

**Comment by Thxzzzzz** [comment]
@stevewhims Thanks for your help,But name my SSID with 5Ghz or 2.4Ghz dosn't really change the frequency of the mobile hotspot . 
I am using Qualcomm QCA9377 WiFi chip .There is an option in       _Windows 10 settings - Mobile Hotspot - Edit_     can actually config the SSID Passphrase & band frequency (2.4Ghz or 5Ghz),But with  _NetworkOperatorTetheringAccessPointConfiguration_ Class I couldn't config the band frequency. Or maybe is there any way I can call the _Edit_ dialog using any code? Just like _ms-settings:network-mobilehotspotedit_ can call _Mobile Hotspot_ Settings Window. My English is not good enough ,Wish you don't mind.

**Comment by stevewhims** [comment]
I don't know whether this will help, but here are some more thoughts/info. Normally, a physical wireless router supports dual band (5Ghz and 2.4Ghz). By default, many of these routers come with dual band enabled by default. So, setting up two access points doesn't normally require two independent routers - it is simply a configuration change. Also, wireless manufacturers discourage the configuration of dual band routers with the same SSID because clients connecting to the access point can get confused and have connectivity problems if the adapter supports only one band. Hence, it is recommended to set up different SSIDs for different bands.

Are you able to configure the router to broadcast different SSIDs by band? The API doesn't support configuring which to prefer, so that would be your option.

**Comment by Thxzzzzz** [comment]
@stevewhims Really appreciate for your help. There seems no way to meet my needs for now.Thank you for you time.

**Comment by stevewhims** [comment]
Thanks for filing the issue, @Thxzzzzz, and my apologies we couldn't give you a better answer. I'll close this issue now. ~Steve
