### ISSUE TITLE
How to test if AudioGraph is available?

### ISSUE THREAD

**Issue by Heidelberger** [MicrosoftDocs/winrt-api#760]
"AudioGraph cannot be instantiated on the N and KN editions of Windows 8 and Windows 10, unless the optional Media Feature Pack has been installed."

Please add information or link to information on how to test if the system can instantiate AudioGraph.  ApiInformation.IsTypePresent(Windows.Media.Audio.AudioGraph") returns true even on N and KN systems where AudioGraph instantiation fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0d461f-9f22-baac-5900-3057d63dade3
* Version Independent ID: d626d479-c5a4-edf0-7e75-6b6e8d4ecc63
* Content: [AudioGraph Class (Windows.Media.Audio) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Audio.AudioGraph)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audiograph.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audiograph.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
