### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/winrt-api#780]
How can I use Keyboard Accelerators with Ctrl+Tab to navigate through the PivotItems? They're never invoked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f6fa54-d303-a18d-c8bb-2658663fe87b
* Version Independent ID: 1ba3b545-75a0-1849-fb81-6dc5139afe8a
* Content: [Pivot Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Pivot)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.pivot.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.pivot.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
@YuliKl

**Comment by YuliKl** [comment]
@SilverSilence - can you explain in more detail what behavior you're hoping to achieve? What's your desired user interaction?

**Comment by msaifi** [comment]
It seems that the control, when used with ItemTemplateSelector, clears its content when we navigate back from other page even though the cache is required. 
I have a UWP page with a pivot control. I am using MVVM pattern where the "ItemsSource" property of the pivot is binded to an observable collection of my viewmodels. I am using the "ItemTemplateSelector" of the pivot to select the appropriate DataTemplate for each view model based on the Pivot "SelectedItem" which in turn is binded the selected view model. Within the same page, I have a navigation view where the navigationItem click event creates a new view model based on the selected item and adds it to the observable collection "MainPageViewModel.EditViewModels" and set the SelectedViewModel to the newly created one.

The application works fine as expected working arround implicit DataTemplate that is in WPF and missing in UWP. The only problem I am having is that when I navigate from the page hat contains the Pivot controls and comes back, then all the Pivot Items are cleared and not showed.
I have set in the page constructor "Navigation.NavigationCacheMode.Required" and did not override the NavigateTo method.
If I set my usercontrols within the Pivot Items directly without using DataTemplate selector then the Pivot items are maintained when I come back to the page. The pivot items are cleared only when I use the ItemTemplateSelector.

**Comment by jwmsft** [comment]
Hi, The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question. 

To engage with the XAML product team or file a product bug, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.
