### ISSUE TITLE
How about the InitializeComponent method

### ISSUE THREAD

**Issue by ajventi** [MicrosoftDocs/winrt-api#788]
I came here looking for details on the one method that is called by every single blank UWP app created in Visual Studio Page.InitialzeComponent()

Would have thought this may have been the place to look for it, or possibly follow links somewhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cb6376e-2c9f-10e5-24c5-56bd78a6956b
* Version Independent ID: 42069986-5904-e987-b6d4-ccede63326e1
* Content: [Page Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Page#methods)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.page.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.page.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by MikeHillberg** [comment]
Note that InitializeComponent isn't a method on Page itself.  It's a method that's generated by the Xaml compiler during build and added to the subclass (for example MainPage.g.i.cs).  In VS you can F12 on the call to it to get to the definition of it.

**Comment by ajventi** [comment]
So @MikeHillberg I guess this isn't the place to find an answer

https://www.bing.com/search?q=Windows.Ui.Xaml.Controls.MainPage&form=WNSGPH&qs=SW&cvid=775c127287e645a4af519308351c6e58&pq=Windows.Ui.Xaml.Controls.MainPage&cc=US&setlang=en-US&nclid=7EB435A1C7B2AA77B1D126DFFA16A809&ts=1543977126683&wsso=Moderate

**Comment by jevansaks** [comment]
I can't find a page talking about the XamlCompiler's InitializeComponent code and it seems reasonable for us to have one that is at least mentioned here.

**Comment by jwmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
