### ISSUE TITLE
Docs indicate class implement IStorageFolder3, but no such interface exists in docs.

### ISSUE THREAD

**Issue by lisardggY** [MicrosoftDocs/winrt-api#826]
Either the class shouldn't be shown to implement IStorageFolder3, or IStorageFolder3 should be added to the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c1aeee-9b21-dd0b-8766-57f4beb51fbe
* Version Independent ID: b8830c41-14ab-89d6-bc52-92001727ef7c
* Content: [StorageFolder Class (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
