### ISSUE TITLE
It can throw System.IO.PathTooLongException also

### ISSUE THREAD

**Issue by XFox111** [MicrosoftDocs/winrt-api#830]
I cannot retrieve a file from remote server because it's path is too long. Fix it or at least update the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a0b142-3819-3929-bc93-c4d8e0598978
* Version Independent ID: 932a8fe2-dc4e-ade9-e67d-45897840c037
* Content: [StorageFile.GetFileFromPathAsync(String) Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. This sounds like a support request to me. You'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
