### ISSUE TITLE
RepeatCount is inadequately documented/described/defined or malfunctioning

### ISSUE THREAD

**Issue by verelpode** [MicrosoftDocs/winrt-api#833]
Hello. This RepeatCount field is inadequately documented/described/defined.  I tested it (in Win10 version 1803) and I observed that it ALWAYS contains 1 regardless of all these factors:

* Whether the key event is a repeat versus the first notification; and
* How long the user holds the key down; and
* How many times the repeated character appears in a TextBox element; and
* How many times the same key is pressed; and
* Which event you subscribe to (UIElement.PreviewKeyDown/Up, KeyDown/Up, or CharacterReceived).

In contrast, in the old WPF-Classic, System.Windows.Input.KeyEventArgs.IsRepeat returns true when the UIElement.PreviewKeyDown and UIElement.KeyDown (but not KeyUp) events are repeated while the user holds the key down.

Thus I conclude that the UWP RepeatCount seems to be malfunctioning and/or designed in an unclear manner and/or ambiguously named and/or insufficiently documented and defined.

Thanks for any bug fixes and improvements in this place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f60531f-f3ae-8c5d-178a-907470515790
* Version Independent ID: 9537ecab-6b30-2f10-386a-b8c36b36c820
* Content: [CorePhysicalKeyStatus.RepeatCount Field (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corephysicalkeystatus.repeatcount?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Core.CorePhysicalKeyStatus.RepeatCount)%3Bk(vs.objectbrowser)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corephysicalkeystatus.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corephysicalkeystatus.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by verelpode** [comment]
Possibly a better place to document the behavior is in this article:  [https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events)

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @verelpode - Thanks for the feedback! You are correct, I've confirmed with the feature team that this is, indeed, a bug. They are triaging it now and plan to address in a future build of the OS.

**Comment by verelpode** [comment]
Aha, thanks.  The behavior was confusing, but it is good to know that it is a bug that will be fixed.

**Comment by eugenegff** [comment]
Property RepeatCount is used when application pumps key down messages not fast enough and some of them are coalesced. There is another property WasKeyDown that more closely resembles System.Windows.Input.KeyEventArgs.IsRepeat


From documentation of WM_KEYDOWN it seems that RepeatCount is used when several key downs are coalesced, it is explicitly specified that it is not cumulative when several key down events are sent. And probably for application that pump messages fast enough - each event is delivered separately with RepeatCount == 1

https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-keydown

0-15 | The repeat count for the current message. The value is the number of times the keystroke is autorepeated as a result of the user holding down the key. If the keystroke is held long enough, multiple messages are sent. However, the repeat count is not cumulative.

Because of the autorepeat feature, more than one WM_KEYDOWN message may be posted before a WM_KEYUP message is posted. The previous key state (bit 30) can be used to determine whether the WM_KEYDOWN message indicates the first down transition or a repeated down transition.

I did input handling subsystem for Live Home 3D on WinRT, macOS and iOS, and used to fill voids in WinRT documentation by using Win32 docs for underlying technology.

P.S.
Here is a proof, that RepeatCount is reliable, but has somewhat unexpected contract:
https://docs.microsoft.com/en-us/windows/win32/inputdev/about-keyboard-input#keystroke-message-flags

You can check the repeat count to determine whether a keystroke message represents more than one keystroke. The system increments the count when the keyboard generates WM_KEYDOWN or WM_SYSKEYDOWN messages faster than an application can process them. This often occurs when the user holds down a key long enough to start the keyboard's automatic repeat feature. Instead of filling the system message queue with the resulting key-down messages, the system combines the messages into a single key down message and increments the repeat count.
