### ISSUE TITLE
The new Windows.UI.Composition.RedirectVisual - Only One Allowed Per Source?

### ISSUE THREAD

**Issue by seanocali** [MicrosoftDocs/winrt-api#835]
I've [attached ](https://1drv.ms/u/s!AnGu-7rqGecsgZgZ-wvxbr2ttVh6_g)a simple sample app with 3 tests showing some odd behavior of this new addition to the Composition API. It seems no matter what it is limited to one RedirectVisual per source, and a RedirectVisual can be set to only one UIElement at a time. Is this a known limitation/intentional by design, or is it a bug?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6765eab2-ef54-b27f-85ca-ce27ffc15ef6
* Version Independent ID: 98d41a0b-1ab0-22e4-caed-228d1767522f
* Content: [RedirectVisual Class (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.redirectvisual)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.redirectvisual.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.redirectvisual.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. It seems your Issue leans more towards product feedback rather than specific documentation fixes. 

If still relevant, may I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
