### ISSUE TITLE
What is behavior of WriteValueAsync(IBuffer)?

### ISSUE THREAD

**Issue by dlech** [MicrosoftDocs/winrt-api#840]
Is `WriteValueAsync(IBuffer)` equivalent to `WriteValueAsync(IBuffer, GattWriteOption. WriteWithoutResponse)` or `WriteValueAsync(IBuffer, GattWriteOption.WriteWithResponse)`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90524148-a1cb-13ad-922b-7557f64abc00
* Version Independent ID: 05adef7b-05c2-ad83-f476-ae7f4970b57b
* Content: [GattCharacteristic.WriteValueAsync Method (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristic.writevalueasync#Windows_Devices_Bluetooth_GenericAttributeProfile_GattCharacteristic_WriteValueAsync_Windows_Storage_Streams_IBuffer_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattcharacteristic.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattcharacteristic.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @dlech. Thanks for filing this issue, and my apologies for the very long delay in responding.

Unfortunately, the short answer is "neither". The current implementation depends on the Gatt characteristic properties that have been reported by the specific device in use. The current implementation queries for those properties in a particular sequence, and so its behavior depends on whether one or neither of the Write/WriteWithoutResponse characteristic properties are reported by the device. Since this logic is somewhat complex, and since we haven't documented it in the topic, I'd recommend not depending on it if you need to be sure what option is used.

If you need that high level of determinism, then I'd recommend calling the other override, and supplying an option explicitly.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Comment by dlech** [comment]
Thanks for the info. That answers my question.
