### ISSUE TITLE
App package information sample app does not display Package Id

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/winrt-api#888]
Through `VS2017 - ver 15.9.5`, I deployed your [App package information sample](http://code.msdn.microsoft.com/windowsapps/Package-sample-46e239fa) on my `Windows 10 Pro - version 1809`, but the main window of the sample app does not display the `Package Id`.

**Question**: How can I display the Package Id of the package as well. Or, maybe, I'm misunderstanding the concept of `Package.Id`. Using C#, I'm looking for a way to find full unique identifier of the specific version of my package?

**Main window of the sample app [when I run it in VS2017]**:

![untitled](https://user-images.githubusercontent.com/10931726/51795395-989e9080-21b0-11e9-9805-424d4ae9ddb2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d0f663f-5e33-ca25-c06f-1c8ad1824955
* Version Independent ID: 072e92d9-1b15-27da-0250-07bf693a599e
* Content: [Package.Id Property (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.id#Windows_ApplicationModel_Package_Id)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by mcleanbyron** [comment]
Hi @saf-itpro - The sample uses the [Package.Id](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.id) property to access package identity metadata via the [PackageId](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageid) object, including the package name, architecture, and other metadata shown in your screenshot above. See the scenario1_identity.xaml.cs file for the code.

I'm not sure if this API exposes the exact metadata you're looking for. If I'm understanding you correctly, it sounds like you're either interested in the [Version](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageid.version) property or the [FullName](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageid.fullname) property (which includes the version string). 

This repo is specifically for capturing bugs and feedback on the docs. Since your question appears to be a technical question about the packaging API itself, I'm closing this issue for now. I hope the information above is helpful.

**Comment by saf-itpro** [comment]
@mcleanbyron Thank you for explaining the concept of `Package.Id`. I was looking for full unique identifier of the specific version of my package that it seems is `FullName` property of the package. You've provided the required info.
