### ISSUE TITLE
Samples need review

### ISSUE THREAD

**Issue by bgavrilMS** [MicrosoftDocs/winrt-api#894]
1. Protect() is an async method, but you fire and forget about it
2. Protect() is an async method, so it should not return void. It should return Task.
3. All async methods should be suffixed with "Async"
4. When awaiting a method, you should call ConfigureAwait(false) to setup a continuation context
5. Inconsistent naming of variables (e.g. Provider  instead of provider)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7d92f04-6d6c-54e0-dcaf-0c2b3b63b2ac
* Version Independent ID: 32ad8a6f-2de7-2f1b-2ef7-b5d0ea69b6e4
* Content: [DataProtectionProvider Class (Windows.Security.Cryptography.DataProtection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.dataprotection.dataprotectionprovider)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.dataprotection.dataprotectionprovider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.dataprotection.dataprotectionprovider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **misatranjr**
* Microsoft Alias: **misatran**

**Comment by GrantMeStrength** [comment]
Thanks for the comment, and sorry for the delay in addressing it. 

You are correct - this sample does not follow the guidance for fully implementing async methods, or naming variables. I have flagged it so that the team that created it can decide if they should improve it for not, or if I can add a note pointing out the shortcomings. 

Thanks for taking the time to leave feedback, and again, sorry for the delay. We do read bugs as they come in, but may not add comments immediately, which gives a poor impression - I apologize. -John
