### ISSUE TITLE
EventHandler<Platform::Object> in C==/Winrt

### ISSUE THREAD

**Issue by mkamilov** [MicrosoftDocs/winrt-api#897]
[Enter feedback here]
This is example code given in `C++/Winrt`

`event_token Resuming(EventHandler<Platform::Object> const& handler) const;`

Not getting what is `Platform::Object` as I could not find any information in `C+/WinRT`. Is it supposed to be `IInspectable`? Please fix the document or provide link that explains what is  `Platform::Object` in `C+/WinRT`

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4f55ef-95b1-92f6-c043-06e0f9b243e2
* Version Independent ID: 1828726c-9a46-044e-a3ac-70726c9f3e74
* Content: [Application.Resuming Event (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.resuming)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @mkamilov, thank you for raising this issue. You're right that this syntax is of course incorrect for C++/WinRT and you're also right that it should be IInspectable (technically, winrt::Windows::Foundation::IInspectable). I'll go ahead and file an internal bug for this and we'll deal with it. I'll go ahead and close this issue so that we're not tracking it in two places.
