### ISSUE TITLE
Exception: Element not found. (Exception from HRESULT: 0x80070490)

### ISSUE THREAD

**Issue by simovic1** [MicrosoftDocs/winrt-api#904]
I'm having an issue with all method called from this class. Every method throws an Exception System.Error Element not found. (Exception from HRESULT: 0x80070490).

e.g Method for creation TPM VirtualSmartCard
SmartCardProvisioning cardProvisioning = await SmartCardProvisioning.RequestVirtualSmartCardCreationAsync(firendlyName, adminKey, pinPolicy);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3d4915-eda2-8a16-7c02-21c0e17f87ff
* Version Independent ID: 3c41840c-75cd-8523-9945-107970ea64ae
* Content: [SmartCardProvisioning Class (Windows.Devices.SmartCards) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.smartcards.smartcardprovisioning)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.smartcards.smartcardprovisioning.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.smartcards.smartcardprovisioning.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @simovic1. Thanks for filing this issue, and my apologies for the very long delay in responding.

This feels like a support question about the product, rather than feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve
