### ISSUE TITLE
Minimum Freshness Time

### ISSUE THREAD

**Issue by Chrissteven81** [MicrosoftDocs/winrt-api#920]
The  constructor has a minimum freshness time of 15 min. If you try to use the background task to trigger any faster then that it will give you a value out of range error. This is not currently documented on this thread and it is implied when you go to the freshnesstime thread but is not stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd39caf5-b4db-ba32-fbee-49580a61c4d1
* Version Independent ID: c62bdc13-5a3f-a4e7-5a38-fdb293828729
* Content: [TimeTrigger Class (Windows.ApplicationModel.Background) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Background.TimeTrigger)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.timetrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.timetrigger.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **msatranjr**
* Microsoft Alias: **misatran**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
