### ISSUE TITLE
Please indicate which Kind each subtype is for.

### ISSUE THREAD

**Issue by StevenEdwardWood** [MicrosoftDocs/winrt-api#940]
Since this list includes Audio, Video, and Image subtypes...we need for the documentation to indicate which kind each subtype is for.  Some are indicated in the property, for example Wvc1 indicates that it is a subtype for Video.  But, Rgb24 and Rgb32 while are obviously not Audio subtypes could be for either Image or Video kinds...or both?

Applications need to know which Kind these subtypes are for so that they can be made available for the users to select them for the specific Audio or Video Encoding Properties or as an Image type for frame capture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a34c7cf0-5486-5150-f8a1-f1adab0f8308
* Version Independent ID: 7cdd7aa2-0217-82d0-4d08-6742dd1b6d63
* Content: [MediaEncodingSubtypes Class (Windows.Media.MediaProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.mediaencodingsubtypes)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.mediaencodingsubtypes.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.mediaencodingsubtypes.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by StevenEdwardWood** [comment]
It also occurred to me that some of these may be selected for the Container Encoding Properties, for example avi.

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

Though most of the media subtypes refer to specific and well-defined formats, I don't believe it makes sense to add the requested information for each subtype, but I did add some text to clarify that RGB24 and RGB32 are image formats.

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!

**Comment by StevenEdwardWood** [comment]
Thanks for taking a look at it. It would have been nice to be able to program an app to read the type for each subclass and present them for the right purpose. But, at least they are available if we want to spend the time testing them.
