### ISSUE TITLE
Dead link in: Troubleshooting for flicker during transition to the extended splash screen 

### ISSUE THREAD

**Issue by ninolhail** [MicrosoftDocs/winrt-api#947]
The links to "Troubleshoot" and "Guidelines and checklist for splash screens" dont't work. I noticed this since on my workstation (iMac 2017 with parallels), there is a noticable flicker when transitioning to the extended splash screen even in the Windows universal samples project (Splash screen sample). Any approach to troubleshoot this issue would therefore be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af984981-86dc-55a1-38f9-7cd17ee40a3c
* Version Independent ID: 6218f863-c0a4-8143-2472-4018f5ff383b
* Content: [SplashScreen Class (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.splashscreen)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.splashscreen.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.splashscreen.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for bringing this to my attention. I'll investigate and fix the links on this page.

For support with your issue I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

For feedback about the flickering you're seeing, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record.
