### ISSUE TITLE
Arguments for lambda in C++/winrt

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#955]
By analogy with the KeyDown event I assume that in C++/winrt I'd declare (for code-behind) a lambda with a sender and args. The docs for the keydown event - described exactly as above - identify the args field as KeyRoutedEventArgs. What would be the args for this? Could you provide an example of usage in C++/winrt on that model? For example, my keydown looks like this and works fine:
m_item.KeyDown([&](winrt::Windows::Foundation::IInspectable const & sender, IKeyRoutedEventArgs const & args)
		{
			HandleKeyDown(args);

		});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5dd209-6c71-3908-48f1-ef2ae1cca125
* Version Independent ID: b9d3210e-df95-d0e1-b9aa-11de9bc45c74
* Content: [Popup.Closed Event (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.popup.closed)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.popup.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.popup.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @jevansAN, that analogy is generally a sound approach. But to be really certain, I'd recommend the following approach (and, by the way, I'm going up to add these details to the 
[Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events) topic.)

First, go to the topic for the event itself. That's Popup.Closed in this case. Select C++/WinRT as the **Language**, and then look in the syntax block for the event, where the register and unregister functions are documented. Under the "Register" comment in the syntax block you'll see the delegate type that you pass to the registration function when you register your delegate with the event. In this case, that's documented as EventHandler\<Platform::Object\>, which is of course a rendering bug (which I've filed, and I'm following up on), but we should read that as EventHandler\<IInspectable\> (which is what it'll say when the bug's fixed). So, then you go to the EventHandler\<T\> topic. On that topic, the syntax block contains a function call operator which takes an **IInspectable** as the sender, and a T as the args, and in this case T is **IInspectable** (because that's the **EventHandler**'s type parameter ) as the args.

That's the general workflow for discovering the type of the delegate and the type and number of the delegate's parameters. Once you have the signature of that function call operator in the delegate topic, you can write a matching member function or a lambda. If you don't actually need to access the sender nor the args then you can short-circuit this whole process and declare your member function or lambda as taking `auto&&...`, like this:

```cppwinrt
        myPopup().Closed([&](auto&& ...)
        {
            // do something that doesn't depend on the sender nor args.
        });

```

**Comment by jevansAN** [comment]
Steven,

	Thank you. The form you supplied below works fine in my class that uses a popup:

	m_popup.Closed([&](auto && ...)
	{
			//Do something
	});

	I believe I am too thick to comprehend the bit about EventHandler<T> . I don’t see a way to determine from the documentation of EventHandler<T> the nature of the arguments needed for the popup’s Closed event.
	However! I don’t need those arguments and can do it as you suggest above, so that will be fine.
	 In general I think recipes are great. I learn from recipes and can often adapt them to other cases. If it were practical to include a line or two of real-world C++/winrt usage for every method then progress would be smooth, or at least smoother. As it is, your responses have been invaluable.

	Yours, Jeff


On Mar 4, 2019, at 1:50 PM, Steven White <notifications@github.com> wrote:

Hi, @jevansAN, that analogy is generally a sound approach. But to be really certain, I'd recommend the following approach (and, by the way, I'm going up to add these details to the
Handle events by using delegates in C++/WinRT topic.)

First, go to the topic for the event itself. That's Popup.Closed in this case. Select C++/WinRT as the Language, and then look in the syntax block for the event, where the register and unregister functions are documented. Under the "Register" comment in the syntax block you'll see the delegate type that you pass to the registration function when you register your delegate with the event. In this case, that's documented as EventHandler<Platform::Object>, which is of course a rendering bug (which I've filed, and I'm following up on), but we should read that as EventHandler<IInspectable> (which is what it'll say when the bug's fixed). So, then you go to the EventHandler<T> topic. On that topic, the syntax block contains a function call operator which takes an IInspectable as the sender, and a T as the args, and in this case T is IInspectable (because that's the EventHandler's type parameter ) as the args.

That's the general workflow for discovering the type of the delegate and the type and number of the delegate's parameters. Once you have the signature of that function call operator in the delegate topic, you can write a matching member function or a lambda. If you don't actually need to access the sender nor the args then you can short-circuit this whole process and declare your member function or lambda as taking auto&&..., like this:

        myPopup().Closed([&](auto&& ...)
        {
            // do something that doesn't depend on the sender nor args.
        });


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
I realize that you said you don't need to know this, since you don't need the delegate arguments, but just in case you're curious and just in case it helps... :) (plus, the time might come when you do need the args)

So, you start at the API reference topic for the [Popup.Closed event](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.primitives.popup.closed), and you see that the `// Register` function in the syntax block takes `EventHandler<Platform::Object> const&`. That's the delegate type for this event. It's EventHandler\<T\> and, even better than that, you can even see what the `T` is. It's Platform::Object. But, wait! Platform::Object is a C++/CX type, and not a C++/WinRT type, so it looks like there's a bug in the rendering of this topic. And, yes, there is, and I've filed that. However, in C++/CX, Platform::Object just means "the base type from which all other types in the platform derive". And in C++/WinRT, that's IInspectable. So T is really IInspectable. And that's what this topic will render when the bug's fixed. So, now that we know that the delegate type for the Popup.Closed is EventHandler\<T\>, and that T is IInspectable, we then go to the topic for [EventHandler\<T\>](https://docs.microsoft.com/uwp/api/windows.foundation.eventhandler) and look at the function call operator which, for EventHandler\<T\>, is `void operator()(winrt::Windows::Foundation::IInspectable const& sender, T const& args) const;` So your delegate's parameters need to match the parameters of that function call operator. In other words, your delegate needs to take an IInspectable, and a T. And T, like we said, is IInspectable. It won't always be, of course, but coincidentally, it is here. So your delegate for the Popup.Closed event takes IInspectable and IInspectable. There are other events that use EventHandler of some T and of course T will be different things in different cases. But you should be able to tell from the API reference topics, as described.

**Comment by jevansAN** [comment]
Thanks, Steven - I guess I can comprehend that.


Jeff


On Mar 4, 2019, at 7:00 PM, Steven White <notifications@github.com> wrote:

I realize that you said you don't need to know this, since you don't need the delegate arguments, but just in case you're curious and just in case it helps... :) (plus, the time might come when you do need the args)

So, you start at the API reference topic for the Popup.Closed event <https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.primitives.popup.closed>, and you see that the // Register function in the syntax block takes EventHandler<Platform::Object> const&. That's the delegate type for this event. It's EventHandler<T> and, even better than that, you can even see what the T is. It's Platform::Object. But, wait! Platform::Object is a C++/CX type, and not a C++/WinRT type, so it looks like there's a bug in the rendering of this topic. And, yes, there is, and I've filed that. However, in C++/CX, Platform::Object just means "the base type from which all other types in the platform derive". And in C++/WinRT, that's IInspectable. So T is really IInspectable. And that's what this topic will render when the bug's fixed. So, now that we know that the delegate type for the Popup.Closed is EventHandler<T>, and that T is IInspectable, we then go to the topic for EventHandler<T> <https://docs.microsoft.com/uwp/api/windows.foundation.eventhandler> and look at the function call operator which, for EventHandler<T>, is void operator()(winrt::Windows::Foundation::IInspectable const& sender, T const& args) const; So your delegate's parameters need to match the parameters of that function call operator. In other words, your delegate needs to take an IInspectable, and a T. And T, like we said, is IInspectable. It won't always be, of course, but coincidentally, it is here. So your delegate for the Popup.Closed event takes IInspectable and IInspectable. There are other events that use EventHandler of some T and of course T will be different things in different cases. But you should be able to tell from the API reference topics, as described.

**Comment by stevewhims** [comment]
My additions to [Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events) are live now. That essentially captures what we talked about in this thread. So, I'll go ahead and close this, but as always please reopen any time. ~Steve

**Comment by jevansAN** [comment]
Steven - that link doesn’t work, but if it gets fixed I’ll certainly read it.

Don’t want to be overburdening MS, but I was just trying to enter a content comment on the page for the FlyoutBase Closed event and that page freezes up every time - tried it from a couple of different computers. I can enter a topic; it freezes on trying to enter a comment.

The Closed event is described as triggering when the flyout closes, but in testing I find it is triggered when the flyout opens. This hinders my plan to change keyboard focus upon the closing of any popup or flyout. I’m using your suggestion to call it with 
theFlyout.Closed(auto &&…)(
{
	DoSomething();
};)

And the trigger does work fine. I don’t know if this is a bug or whether the documentation has something else it could say about this event. 

Thanks, Jeff

On Mar 5, 2019, at 11:59 AM, Steven White <notifications@github.com> wrote:

My additions to Handle events by using delegates in C++/WinRT <https://docs.microsoft.comwindows/uwp/cpp-and-winrt-apis/handle-events> are live now. That essentially captures what we talked about in this thread. So, I'll go ahead and close this, but as always please reopen any time. ~Steve

**Comment by stevewhims** [comment]
Hmm, that link works when I try it, and it looks well-formed. It goes to 
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events 
or, without the language tag:
https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events 

As for the FlyoutBase.Closed event, I just tried an experiment where I handle the Closed event of a MenuFlyout. I set a break point in my delegate (I'm using a lambda for my delegate in this case). I then debug the app and I DON'T stop at the breakpoint when I right-click the flyout's parent element. That's what causes the flyout to open. However, if I right-click, or choose an item, or soft dismiss (all of which cause the flyout to close), then I do stop at the breakpoint. So, I'm seeing evidence that the event is only raised on close. I'm attaching the delegate immediately after InitializeComponent in my MainPage.

```cppwinrt
        myMenuFlyout().Closed([&](auto&& ...)
        {
            // Put some token code here, and put a breakpoint on it.
        });
```

**Comment by jevansAN** [comment]
Thanks as usual, Steven. There may be something tricky here:; I attach the menu flyout to a Button, and I set the Button’s click mode to Hover.  So when the mouse gets over the button the menu pops up. And if I set a breakpoint in the DoSomething that is called by the lambda responding to the flyout’s Closed event, the method is called the moment the moment the cursor gets over the button!

But I found a workaround: in the DoSomething I first check the IsOpen of the flyout,

void myClass::DoSomething()
{
if (! m_menu_flyout.IsOpen())
	ThenDoTheThing();
}

And that works fine. It appears that when I first get the Closed event for the flyout, it’s actually opening and is marked as Open, so I ignore the event.  Later on when it really does close, IsOpen returns false and I go ahead with the action I wanted to take upon closing.

II can’t quite figure the explanation for Closed being called when the flyout first opens - it might have something to do with responding to Hover, which is different from your case.  Seems a little kooky but I’m happy if a workaround takes care of it (so long as it’s stable). 


Jeff



On Mar 6, 2019, at 7:33 PM, Steven White <notifications@github.com> wrote:

Hmm, that link works when I try it, and it looks well-formed. It goes to
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events
or, without the language tag:
https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events

As for the FlyoutBase.Closed event, I just tried an experiment where I handle the Closed event of a MenuFlyout. I set a break point in my delegate (I'm using a lambda for my delegate in this case). I then debug the app and I DON'T stop at the breakpoint when I right-click the flyout's parent element. That's what causes the flyout to open. However, if I right-click, or choose an item, or soft dismiss (all of which cause the flyout to close), then I do stop at the breakpoint. So, I'm seeing evidence that the event is only raised on close. I'm attaching the delegate immediately after InitializeComponent in my MainPage.

        myMenuFlyout().Closed([&](auto&& ...)
        {
            // Put some token code here, and put a breakpoint on it.
        });

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
Yes, that does seem tricky. The issue with leaving feedback on topics is resolved now, so feel free to leave info on the topic for the event in question if you get further problems. Thanks for keeping me posted, I'm glad you worked around the behavior. ~Steve

**Comment by jevansAN** [comment]
Steven,

	Since you’ve been a big help I’ve posted another issue, this one relating to the docs for Printing.

The docs at https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Printing.PrintDocument seem to have an incorrect namespace for PrintDocument. It is described, for C++/winrt, as winrt::Windows::UI::Xaml::Printing::PrintDocument, but that is not accepted by VS2019 4.1 and Intellisense says there is no “Printing” in winrt::Windows::UI::Xaml.

	Is this just an error in the documentation, or is it possible that changes need to be made to the project in order to support printing? I’ve seen no mention of that.

	Thanks, Jeff


On Mar 7, 2019, at 6:36 PM, Steven White <notifications@github.com> wrote:

Yes, that does seem tricky. The issue with leaving feedback on topics is resolved now, so feel free to leave info on the topic for the event in question if you get further problems. Thanks for keeping me posted, I'm glad you worked around the behavior. ~Steve

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
Thanks, @jevansAN, I've replied to the GitHub issue on that topic. ~Steve
