### ISSUE TITLE
Geotag-Support for .HEIC files

### ISSUE THREAD

**Issue by tipa** [MicrosoftDocs/winrt-api#956]
This method currently seems to be unable to gather geotags from .HEIC files, although Windows can show the geotag in the properties window and the Windows photo app is able to show the location as well. Are they using a different API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399f1d5b-21c8-b160-6dc8-688e398b385e
* Version Independent ID: c57be2e4-c3bf-0f2d-48e2-76cd17df8d70
* Content: [GeotagHelper.GetGeotagAsync(IStorageFile) Method (Windows.Storage.FileProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.geotaghelper.getgeotagasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.geotaghelper.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.geotaghelper.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.
