### ISSUE TITLE
How do I get a writable thumbnail?

### ISSUE THREAD

**Issue by BlueEmb3r** [MicrosoftDocs/winrt-api#959]
Every time I try to get the [WriteAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.storageitemthumbnail.writeasync#Windows_Storage_FileProperties_StorageItemThumbnail_WriteAsync_Windows_Storage_Streams_IBuffer_) method, I get an exception that says my access is denied, and it's because I do not get a writable thumbnail, how do I get one?

**Comment by knicholasa** [comment]
Thanks for reaching out. Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.
