### ISSUE TITLE
Restart my uwp failed by using this api

### ISSUE THREAD

**Issue by AceLearnGit** [MicrosoftDocs/winrt-api#963]
After restarting the UWP using this API, the UWP restarts and then minimizes to the taskbar. The window cannot be displayed to the foreground, and the value of CoreWindow..ActivationMode is read as CoreWindowActivationMode.Deactivated. What is the reason why I can't show it to the front desk? How can I solve this problem?(My windows ver:1809, 17763. 195)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccf02bc-c2a1-6f69-5c02-a73f34b004c1
* Version Independent ID: 070e0499-b6dd-e3a9-5109-ec5cdb621a60
* Content: [CoreApplication.RequestRestartAsync(String) Method (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplication.requestrestartasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplication.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplication.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi! Feedback left here is meant for improvements to the documentation you're commenting on. However, there are some other resources you can use. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for other support options.

**Comment by ghost** [comment]
I meet the same issue.

**Comment by knicholasa** [comment]
Hi! Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.
