### ISSUE TITLE
Cannot use IBufferByteAccess from robuffer.h in a C++/WinRT project

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/winrt-api#966]
The purpose of the `WriteableBitmap` type is to allow user code to modify bitmap content in-place. The prescribed steps to gain access to the bitmap buffer (by querying for the `IBufferByteAccess` interface on the `IBuffer`) doesn't appear to be a workable solution for C++/WinRT projects. Any attempt to `#include <robuffer.h>` (which defines the `IBufferByteAccess` type) causes the compiler to emit ambiguous symbol errors on the namespace.

The only way I found around this was to use C++/WinRT's internal `winrt::impl::IBufferByteAccess` type instead, although this doesn't appear to be a sustainable solution.

To solve this issue I'm requesting either of the following:

* Update the *robuffer.h* header file to allow it to be used from a C++/WinRT project.
* Move C++/WinRT's `IBufferByteAccess` into the public API surface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7912fc-bc9f-acdd-968b-272cad6cde31
* Version Independent ID: 4c2c9d7a-f8fd-da0e-1c96-fd696690505a
* Content: [WriteableBitmap Class (Windows.UI.Xaml.Media.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Imaging.WriteableBitmap)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.writeablebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.writeablebitmap.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @tim-weis, thanks for filing this issue. I've updated the topic(s) as a result of this feedback. You're right that robuffer.h's definition of IBufferByteAccess is problematic if you have `using namespace winrt` in your project (which is default, and common). To use the IBufferByteAccess COM interface, you can either a) avoid `using namespace winrt` and include robuffer.h, or b) define the IBufferByteAccess COM interface yourself in one place in your project. You can see a C++/WinRT code example of b) in the [WriteableBitmap.PixelBuffer](https://docs.microsoft.com/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap.pixelbuffer#Windows_UI_Xaml_Media_Imaging_WriteableBitmap_PixelBuffer) topic. In that example, I declared the COM interface at global scope (rather than in the ambiguous Windows::Storage::Streams that the header uses).

However, you can avoid IBufferByteAccess altogether with C++/WinRT by retrieving the byte* returned from WriteableBitmap.PixelBuffer().data(). `data` is a helper function.

Also, you're right to be cautious of using winrt::impl::IBufferByteAccess. Developers should never use *any* type in winrt::impl, since those are implementation details, and could well change in future.

Since the remarks and code examples were largely duplicated between the WriteableBitmap and WriteableBitmap.PixelBuffer topics, I consolidated that info into the latter, and added a link from the former. Please let me know if there's anything else I can do here.

~Steve

**Comment by tim-weis** [comment]
Thanks for the feedback, @stevewhims. Very helpful indeed, and much appreciated.

I was immediately sold on the `data()` helper, only to find out, that it is defined on the `consume_Windows_Storage_Streams_IBuffer` type, living a hidden life in the `winrt::impl` namespace. It is undocumented, too, presumably for that reason.

The ultimate solution I went for was to write my own helper function, isolated into its own compilation unit, allowing me to `#include <robuffer.h>` after all. Information on the availability of the `IBufferByteAccess` type in that header file is gone from the documentation after the update, though. It may be helpful to keep that information around, although I do acknowledge that documenting the implications on using it in a C++/WinRT setting may well be prohibitively laborious.

Ideally, the `data()` helper should be moved into the public API surface, although that is probably something that needs to be filed as product feedback as opposed to documentation feedback.

**Comment by stevewhims** [comment]
I've updated the topic again, so I may have addressed this in the process. But, I don't understand this feedback well enough to map it to the specific content that I may have lost previously: "Information on the availability of the IBufferByteAccess type in that header file is gone from the documentation after the update, though. It may be helpful to keep that information around."

In any case, if you get the chance to check, could you let me know whether that's still an issue?

The part I updated is in the code example and the Remarks sections in this topic: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap.pixelbuffer#Windows_UI_Xaml_Media_Imaging_WriteableBitmap_PixelBuffer. The WriteableBitmap topic (this topic) links to that topic from both the code examples and the remarks sections.

Thanks!
~Steve

**Comment by stevewhims** [comment]
Hi, @jevansaks, I'll go ahead and close this issue now since it feels resolved. ~Steve

**Comment by tim-weis** [comment]
The documentation looks fine now, thank you for that. Although this should really appear on (or at least be linked from) the documentation for [IBuffer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.ibuffer).

**Comment by stevewhims** [comment]
Good thought, so I've made a change to the IBuffer topic with the link you suggest. I hope to have that change propagate out to the live site in the next 24-48 hours or so; I'm just working with folks on this side to make that happen. Thanks again! ~Steve

**Comment by leonardder** [comment]
I'm a bit confused. I'm not seeing c++ code exampls [Here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap.pixelbuffer#Windows_UI_Xaml_Media_Imaging_WriteableBitmap_PixelBuffer), only a C# example even though the text mentions a C++ example several times.
