### ISSUE TITLE
Example needed

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#970]
What we really could use would be a clear example of a printing request carried through to completion - but not in HTML/Javascript. Something in C++/winrt would be best.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf04a641-46e1-73a7-badc-f9d81186426b
* Version Independent ID: acd8c7aa-fd74-85d6-084e-6d6df1ad3349
* Content: [PrintTaskSourceRequestedHandler Delegate (Windows.Graphics.Printing) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.printing.printtasksourcerequestedhandler)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.printtasksourcerequestedhandler.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.printtasksourcerequestedhandler.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. I have created an internal work item to investigate the usage statistics for these APIs and potentially add sample code for this printing scenario.
