### ISSUE TITLE
Methods to set SPI and symmetric encryption key for UDP encapsulated IPSec channel

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#978]
Dear Microsoft support,
I am looking for interfaces to set SPI (security parameter index) and symmetric encryption key for the IPSec channel from my application code itself by avoiding IPSec key-exchange. 

Is there a way available in the Vpn UWP interfaces? I tried searching through. But, didn't find one. 

Appreciate your answers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a47d2c-61a3-01b3-d0dc-73a4b7d5117f
* Version Independent ID: 4c713fb3-f086-5319-cf44-33346a7a14b7
* Content: [Windows.Networking.Vpn Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @defaultshr, thanks for filing this issue. If there's a gap in the documentation then I'll be keen to fill that. However, I've taken your question and I've written to the product team, since I'm unable to answer it myself. I'll let you know what response I get from them, and if the docs need updating then I'll do that.

Incidentally, this is not Microsoft Support. When you leave a GitHub issue on a documentation topic, as you did here, that issue is addressed by the folks who write the documentation. For problems/errors/omissions with the actual documentation, this is the right forum to raise those.

I'll do what I can to help, if the docs need updating. And, just FYI, here are some other resources in case you ever need them.

The [Windows developer feedback site](https://wpdev.uservoice.com) is the right place to file a product bug.

For Visual Studio issues, you could try the
[Visual Studio User Voice](https://visualstudio.uservoice.com) feedback website, or the [Developer Community](https://developercommunity.visualstudio.com).

For issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a product bug or something else.

~Steve

**Comment by defaultshr** [comment]
This is not a relevant issue for the programming model supported by UWP VPN framework to develop a custom VPN implementation. 

One may refer https://github.com/defaultshr/UWPVPNPluginSample for a sample application code to write custom VPN plugin. The SPI/Encryption keys are in the scope of the custom plugin and not in the UWP framework.
