### ISSUE TITLE
UWP SerialDevice Unpredictable Read Behavior

### ISSUE THREAD

**Issue by timali** [MicrosoftDocs/winrt-api#980]
The UWP SerialDevice class currently only allows you to set "ReadTimeout", which under the hood, sets the "ReadIntervalTimeout" of the actual serial device (https://docs.microsoft.com/en-us/windows/desktop/api/winbase/ns-winbase-_commtimeouts). There are two other timeout values which dramatically affect the read operations behavior: 1) ReadTotalTimeoutMultiplier and 2) ReadTotalTimeoutConstant.

The UWP SerialDevice class does not allow the user to set these two other read timeout values, and even worse, the UWP SerialDevice class does not set these two other timeout values to known values when the serial device is opened. This means that the two other timeout values will be whatever default value the serial driver uses, or worse still, whatever value some serial port application happened to set these two values to be when the other application was last executed.

The overall effect of this is that your UWP application's serial device read behavior is undefined and cannot reliably be used. For example, if these two other timeout values happen to be set one way, then a read operation may block forever waiting on the first byte of data to be read, but if the other timeout values happen to be set a different way, then the read operation may return immediately, with no data read at all. Currently, a UWP application cannot control this behavior, and the behavior will be different across different serial ports, and even perhaps different every time the UWP application is executed.

The UWP SerialDevice class either needs to
1) Allow the user to set these two other read timeout values (preferred), OR
2) Initialize these two other timeout values to known values when the serial device is opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cd1f0e-b9f9-78b4-936f-7239ae21128a
* Version Independent ID: 32b282e1-0525-12d3-da26-cd666a5a41b5
* Content: [SerialDevice.ReadTimeout Property (Windows.Devices.SerialCommunication) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication.serialdevice.readtimeout#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.serialcommunication.serialdevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.serialcommunication.serialdevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @timali. Thanks for filing this issue, and my apologies for the long delay in responding.

This is a request for a change in the behavior of the APIs (in other words, the product), rather than feedback about the documentation (there's nothing that I can action, as a writer). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve
