### ISSUE TITLE
How to speech and not speech the punctuation?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#989]
Hi,
Why the punctuation is not speech by default? Is there method can be used for set the TTS to speech and not speech the punctuation?
For example, the '(', ')', ',', '-', '.', '/', etc. are all can't speech in German TTS.
How to fix this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d584af5-1efc-1150-d7fe-70a78d84c147
* Version Independent ID: 0e8070e4-173d-4dec-a4be-b0beedc23190
* Content: [SpeechSynthesizerOptions.PunctuationSilence Property (Windows.Media.SpeechSynthesis) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizeroptions.punctuationsilence)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechsynthesis.speechsynthesizeroptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechsynthesis.speechsynthesizeroptions.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. 

Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
