### ISSUE TITLE
Custom URI schema length issue

### ISSUE THREAD

**Issue by werwolfby** [MicrosoftDocs/winrt-api#990]
I can't find any documentation of URI lengths.

Because on Windows 10 version 1607 the limit is 2083 symbols, I still can pass more, but it will be truncated to 2083. Starting from 1709 the limit is 32768 what is expected because it is limit for URI itself. I wasn't able to test on 1703.

Should we add this limits to doc as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3fbf004-b4cd-3d07-7963-f111d4c7e1ff
* Version Independent ID: cae8c616-951e-a727-35ae-4ec96505e616
* Content: [Launcher.LaunchUriAsync Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchuriasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.launcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.launcher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by sseyod** [comment]
Hi - I've just investigated this on Windows 11, and can confirm the limit seems to be only around 32768 bytes of UTF-8 text.
This is at odds with the documentation for Launcher.LaunchUriAsync, so there is a bug somewhere.
Can somebody please confirm where the bug is - the documentation, or the implementation of URI handling.

That said, I have a specific use case where I would like support for URIs of the order of 1MB or more.

Is there any reason for having such a tiny limit? Is this even the correct place to ask?

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks, find the answers, and resolve this doc bug. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

We have moved to a new feedback system, and I want to ensure that we don't lose access to the feedback in our open issues. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks.

**Comment by sseyod** [comment]
c.f. my question above - is this actually a documentation bug, or *as seems more likely to me* surely this is an actual bug due to much older conceptions of what URLs can be used for; I really can't see why the system would be limited to tiny URL lengths! Best wishes, Pete
