### ISSUE TITLE
How can I get the AllContactsReadWrite level of access?

### ISSUE THREAD

**Issue by Lion-HC** [MicrosoftDocs/winrt-api#996]
Hi, I'm wondering:
1. What steps must be done to use the AllContactsReadWrite level of access in production?
2. Can the AllContactsReadWrite level of access be used in development? Is there specific Capability needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd5d392-d1cd-0686-3b24-2a7ae57b8c41
* Version Independent ID: e7cdc4c2-209c-4bea-d104-1c5c8293c0a3
* Content: [ContactStoreAccessType Enum (Windows.ApplicationModel.Contacts) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Contacts.ContactStoreAccessType#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.contacts.contactstoreaccesstype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.contacts.contactstoreaccesstype.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, thanks for reaching out with your feedback. Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support here. The pages lists "contactsSystem" in the capabilities section of the "Windows 10 requirements" table, so it's likely that that capability is required, but I'd encourage you to reach out to our developer support channels to reach someone who can give you thorough support. 

For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

**Comment by Lion-HC** [comment]
Thank you very much!
xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
<rescap:Capability Name="contactsSystem"/>
does work.

**Comment by knicholasa** [comment]
Great! Glad that was helpful.
